Repository featurebyte/featurebyte, pull requests merged in 2023-11, with the labels that each got.

#1893 [DEV-2518] Change feature list catalog output column name from `primary_entities` to `primary_entity`
  .changelog/DEV-2518.yaml
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/api/feature_or_target_mixin.py
  featurebyte/api/target.py
  featurebyte/routes/feature_list_namespace/controller.py
  featurebyte/service/base_document.py
  featurebyte/service/entity.py
  featurebyte/service/entity_serving_names.py
  featurebyte/service/feature_list_namespace.py
  tests/unit/api/test_feature_list.py
Labels: breaking, Documentation Changes Confirmed

#1889 [DEV-2526] Fix session failure with spark 3.4.1 and later
  .changelog/DEV-2526.yaml
  .github/workflows/test_gen.yaml
  Taskfile.yaml
  docker/docker-compose.yml
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/session/base_spark.py
  featurebyte/session/spark.py
  poetry.lock
  tests/fixtures/expected_preview_sql_databricks.sql
  tests/integration/service/test_working_schema_service.py
  tests/unit/query_graph/interpreter/test_interpreter.py
Labels: bug

#1899 [chore] syncing workflow with infra repo
  .github/workflows/changelog_gen.yaml
  .github/workflows/documentation_gen.yaml
  .github/workflows/lint_gen.yaml
  .github/workflows/publish-dev_gen.yaml
  .github/workflows/test-notebooks_gen.yaml
  .github/workflows/test_gen.yaml
Labels: github_actions, Skip Changelog

#1907 [chore] Bumping vuln versions
  .github/workflows/documentation_gen.yaml
  Taskfile.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies, Documentation Changes Confirmed

#1914 [DEV-2611] Make data warehouse session creation asynchronous
  .changelog/DEV-2611.yaml
  featurebyte/exception.py
  featurebyte/middleware.py
  featurebyte/session/manager.py
  tests/integration/conftest.py
  tests/unit/session/test_manager.py
Labels: bug

#1916 [chore] sync workflow
  .github/workflows/dependencies_gen.yaml
  .github/workflows/documentation_gen.yaml
Labels: github_actions, Skip Changelog

#1917 [chore] docs: update docs for context, use_case, obs table and historical feature table
  featurebyte/api/context.py
  featurebyte/api/historical_feature_table.py
  featurebyte/api/observation_table.py
  featurebyte/api/use_case.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/schema/context.py
  tests/unit/api/test_context.py
Labels: Documentation Changes Confirmed

#1919 [DEV-2591] observation_table: add way to update purpose
  .changelog/DEV-2591.yaml
  featurebyte/api/observation_table.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/schema/observation_table.py
  tests/unit/api/test_observation_table.py
Labels: Documentation Changes Confirmed

#1927 Remove `attributes` from `ColumnInfo` class
  featurebyte/api/aggregator/vector_validator.py
  featurebyte/common/utils.py
  featurebyte/core/accessor/vector.py
  featurebyte/enum.py
  featurebyte/models/observation_table.py
  featurebyte/query_graph/model/column_info.py
  featurebyte/query_graph/node/agg_func.py
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/query_graph/sql/ast/tile.py
  featurebyte/query_graph/sql/groupby_helper.py
  featurebyte/query_graph/sql/tiling.py
  featurebyte/routes/common/base_table.py
  featurebyte/routes/dimension_table/controller.py
  featurebyte/routes/event_table/controller.py
  featurebyte/routes/item_table/controller.py
  featurebyte/routes/registry.py
  featurebyte/routes/scd_table/controller.py
  featurebyte/service/specialized_dtype.py
  tests/integration/api/test_column_attributes.py
  tests/unit/api/conftest.py
  tests/unit/api/test_change_view.py
  tests/unit/api/test_dimension_table.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_item_table.py
  tests/unit/api/test_scd_table.py
  tests/unit/api/test_scd_view.py
  tests/unit/api/test_source_table.py
  tests/unit/api/test_table_column.py
  tests/unit/conftest.py
  tests/unit/core/test_frame.py
  tests/unit/models/test_dimension_table.py
  tests/unit/models/test_event_table.py
  tests/unit/models/test_scd_table.py
  tests/unit/query_graph/model/test_table_data.py
  tests/unit/routes/base.py
  tests/unit/routes/relationship_info/test_api.py
  tests/unit/routes/test_batch_feature_table.py
  tests/unit/routes/test_context.py
  tests/unit/routes/test_deployment.py
  tests/unit/routes/test_dimension_table.py
  tests/unit/routes/test_event_table.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_job_setting_analysis.py
  tests/unit/routes/test_feature_list.py
  tests/unit/routes/test_feature_list_namespace.py
  tests/unit/routes/test_feature_namespace.py
  tests/unit/routes/test_feature_store.py
  tests/unit/routes/test_historical_feature_table.py
  tests/unit/routes/test_item_table.py
  tests/unit/routes/test_observation_table.py
  tests/unit/routes/test_scd_table.py
  tests/unit/routes/test_target.py
  tests/unit/routes/test_target_namespace.py
  tests/unit/routes/test_use_case.py
  tests/unit/routes/test_user_defined_function.py
  tests/unit/service/test_specialized_dtype.py
  tests/unit/service/test_table_columns_info.py
Labels: Documentation Changes Confirmed

#1908 [DEV-2527] Update critical data info cleaning operation validation
  .changelog/DEV-2527.yaml
  featurebyte/api/base_table.py
  featurebyte/api/feature.py
  featurebyte/api/view.py
  featurebyte/enum.py
  featurebyte/query_graph/model/column_info.py
  featurebyte/query_graph/node/cleaning_operation.py
  featurebyte/service/table_columns_info.py
  tests/fixtures/sdk_code/complex_multi_table_feature.py
  tests/fixtures/sdk_code/event_view_with_column_clean_ops.py
  tests/integration/api/test_table_column_critical_data_info.py
  tests/unit/api/test_change_view.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_sdk_code.py
  tests/unit/query_graph/model/test_column_info.py
  tests/unit/query_graph/model/test_table_data.py
  tests/unit/service/validator/test_production_ready_validator.py
Labels: Documentation Changes Confirmed

#1926 [DEV-2626] Support renaming of context, use case, observation table and historical feature table
  .changelog/DEV-2626.yaml
  featurebyte/routes/context/controller.py
  featurebyte/routes/historical_feature_table/api.py
  featurebyte/routes/historical_feature_table/controller.py
  featurebyte/routes/observation_table/api.py
  featurebyte/routes/observation_table/controller.py
  featurebyte/routes/use_case/controller.py
  featurebyte/schema/context.py
  featurebyte/schema/historical_feature_table.py
  featurebyte/schema/observation_table.py
  featurebyte/schema/use_case.py
  featurebyte/service/observation_table.py
  tests/unit/routes/test_context.py
  tests/unit/routes/test_historical_feature_table.py
  tests/unit/routes/test_observation_table.py
  tests/unit/routes/test_use_case.py
Labels: enhancement

#1923 [chore] docs: add TableColumn#update_description to docs
  featurebyte/common/documentation/documentation_layout.py
Labels: Documentation Changes Confirmed

#1933 [chore] bumping build and runtime Docker image to 3.10
  docker/Dockerfile
Labels: Skip Changelog

#1932 [DEV-2629][DEV-2625][DEV-2622][DEV-2620][DEV-2602][DEV-2601][DEV-2600] Docs updates
  featurebyte/api/catalog.py
  featurebyte/api/deployment.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/enum.py
  featurebyte/models/observation_table.py
Labels: Documentation Changes Confirmed

#1936 [chore] Changelog for 0.6.1
  CHANGELOG.md
Labels: Skip Changelog

#1909 [DEV-2569] Use published featurebyte SDK in notebook tests
  .changelog/DEV-2569.yaml
  .github/workflows/test-notebooks_gen.yaml
  Taskfile.yaml
  featurebyte/api/target.py
  featurebyte/routes/target_table/api.py
  featurebyte/routes/target_table/controller.py
  featurebyte/schema/target_table.py
  featurebyte/worker/task/target_table.py
  tests/unit/routes/test_target.py
  tests/unit/schema/test_target_table.py
  tests/unit/worker/task/test_target_table.py
Labels: enhancement, github_actions

#1921 [DEV-2623] databricks_unity: add session and migrate one udf
  .changelog/DEV-2623.yaml
  .github/workflows/test_gen.yaml
  Taskfile.yaml
  featurebyte/enum.py
  featurebyte/query_graph/node/input.py
  featurebyte/query_graph/sql/adapter/__init__.py
  featurebyte/query_graph/sql/common.py
  featurebyte/session/base_spark.py
  featurebyte/session/databricks_unity.py
  featurebyte/session/manager.py
  featurebyte/sql/databricks_unity/F_COUNT_DICT_ENTROPY.sql
  featurebyte/worker/task/feature_job_setting_analysis.py
  tests/integration/conftest.py
  tests/integration/udf/conftest.py
  tests/integration/udf/test_count_dict_entropy.py
  tests/source_types.py
Labels: Documentation Changes Confirmed

#1937 [DEV-2656] Update create observation table check
  .changelog/DEV-2656.yaml
  docs/notebooks/quick start model training - final.ipynb
  featurebyte/api/view.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_observation_table.py
  tests/unit/api/test_event_view.py
  tests/unit/api/test_observation_table.py
  tests/unit/conftest.py
Labels: Documentation Changes Confirmed

#1938 [DEV-2659] Support latest aggregation for vector columns
  .changelog/DEV-2659.yaml
  featurebyte/api/aggregator/vector_validator.py
  featurebyte/query_graph/sql/groupby_helper.py
  featurebyte/query_graph/sql/tiling.py
  featurebyte/query_graph/sql/vector_helper.py
  tests/integration/api/fixtures/vector_data.csv
  tests/integration/api/test_vector_aggregation_operations.py
  tests/unit/api/aggregator/test_vector_validator.py
Labels: enhancement

#1940 [DEV-2669] Use DBFS API for DataBricks storage access
  .changelog/DEV-2669.yaml
  featurebyte/api/credential.py
  featurebyte/query_graph/node/schema.py
  featurebyte/session/base_spark.py
  featurebyte/session/databricks.py
  featurebyte/session/spark.py
  poetry.lock
  pyproject.toml
  tests/integration/conftest.py
  tests/unit/session/test_databricks_session.py
  tests/unit/worker/task/test_feature_job_setting_analysis.py
Labels: dependencies, Documentation Changes Confirmed

#1944 [chore] Add feast dependency
  poetry.lock
  pyproject.toml
Labels: dependencies

#1943 [chore] Handle databricks describe table output format
  featurebyte/session/base_spark.py
  tests/unit/session/test_databricks_session.py
Labels: bug

#1945 [DEV-2680][DEV-2691] Refactor `ObservationTable` api object
  featurebyte/__init__.py
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/api/feature_or_target_mixin.py
  featurebyte/api/observation_table.py
  featurebyte/api/primary_entity_mixin.py
  featurebyte/api/target.py
  featurebyte/api/templates/entity_doc.py
  featurebyte/api/templates/feature_or_target_doc.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/models/observation_table.py
  tests/unit/api/base_feature_or_target_test.py
  tests/unit/api/test_catalog.py
  tests/unit/api/test_observation_table.py
Labels: Documentation Changes Confirmed

#1947 [DEV-2679] Fix observation table file upload error
  .changelog/DEV-2679.yaml
  featurebyte/routes/observation_table/controller.py
  tests/unit/routes/test_observation_table.py
Labels: bug

#1952 [DEV-2629] add DBVarType to docs layout
  featurebyte/common/documentation/documentation_layout.py
Labels: Documentation Changes Confirmed
