Repository featurebyte/featurebyte, pull requests merged in 2023-07, with the labels that each got.

#1466 [DEV-1864] Refactor FeatureManager and TileManager as services
  .changelog/DEV-1864.yaml
  featurebyte/common/tile_util.py
  featurebyte/query_graph/sql/feature_historical.py
  featurebyte/routes/registry.py
  featurebyte/service/feature_manager.py
  featurebyte/service/historical_features.py
  featurebyte/service/online_enable.py
  featurebyte/service/preview.py
  featurebyte/service/tile_cache.py
  featurebyte/service/tile_manager.py
  featurebyte/service/working_schema.py
  featurebyte/tile/tile_cache.py
  featurebyte/worker/task/historical_feature_table.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/conftest.py
  tests/integration/feature_manager/test_feature_manager.py
  tests/integration/query_graph/test_online_serving.py
  tests/integration/service/test_working_schema_service.py
  tests/integration/tile/conftest.py
  tests/integration/tile/test_tile_cache.py
  tests/integration/tile/test_tile_manager.py
  tests/integration/tile/test_tile_scheduler.py
  tests/unit/common/test_tile_util.py
  tests/unit/conftest.py
  tests/unit/feature_manager/test_unit_snowflake_feature.py
  tests/unit/query_graph/test_feature_historical.py
  tests/unit/routes/test_historical_feature_table.py
  tests/unit/service/conftest.py
  tests/unit/service/test_historical_features.py
  tests/unit/service/test_preview.py
  tests/unit/tile/test_unit_snowflake_tile.py
Labels: refactoring

#1465 feature: add user defined function endpoints & tests
  .changelog/DEV-1835.yaml
  featurebyte/app.py
  featurebyte/enum.py
  featurebyte/models/feature.py
  featurebyte/models/user_defined_function.py
  featurebyte/query_graph/graph.py
  featurebyte/query_graph/node/function.py
  featurebyte/query_graph/sql/ast/function.py
  featurebyte/routes/common/base.py
  featurebyte/routes/registry.py
  featurebyte/routes/user_defined_function/__init__.py
  featurebyte/routes/user_defined_function/api.py
  featurebyte/routes/user_defined_function/controller.py
  featurebyte/schema/info.py
  featurebyte/schema/user_defined_function.py
  featurebyte/service/feature_store_warehouse.py
  featurebyte/service/user_defined_function.py
  featurebyte/session/base.py
  tests/fixtures/backward_compatibility/get_routes.txt
  tests/fixtures/request_payloads/user_defined_function.json
  tests/unit/api/test_feature.py
  tests/unit/models/test_feature.py
  tests/unit/models/test_user_defined_function.py
  tests/unit/query_graph/test_function.py
  tests/unit/query_graph/test_graph_pruning.py
  tests/unit/routes/test_user_defined_function.py
  tests/unit/service/test_user_defined_function.py
  tests/unit/test_generate_payload_fixtures.py
Labels: enhancement

#1469 [DEV-1869] Refactor tile task to use dependency injection
  .changelog/DEV-1869.yaml
  featurebyte/models/tile.py
  featurebyte/routes/registry.py
  featurebyte/schema/worker/task/tile.py
  featurebyte/service/feature_manager.py
  featurebyte/service/tile/__init__.py
  featurebyte/service/tile/tile_task_executor.py
  featurebyte/service/tile_manager.py
  featurebyte/service/tile_scheduler.py
  featurebyte/sql/base.py
  featurebyte/sql/tile_common.py
  featurebyte/sql/tile_generate_entity_tracking.py
  featurebyte/sql/tile_schedule_online_store.py
  featurebyte/worker/task/tile_task.py
  tests/integration/tile/conftest.py
  tests/integration/tile/test_schedule_generate_tile.py
  tests/integration/tile/test_tile_scheduler.py
  tests/unit/tile/test_unit_snowflake_tile.py
Labels: refactoring

#1471 [DEV-1875] Fix incorrect point-in-time value when updating online store tables
  .changelog/DEV-1875.yaml
  featurebyte/models/tile.py
  featurebyte/service/tile/tile_task_executor.py
  featurebyte/service/tile_manager.py
  featurebyte/sql/tile_generate.py
  featurebyte/sql/tile_monitor.py
  featurebyte/sql/tile_registry.py
  tests/integration/tile/test_generate_tile.py
  tests/integration/tile/test_monitor_tile.py
  tests/integration/tile/test_schedule_generate_tile.py
  tests/unit/service/conftest.py
  tests/unit/service/tile/__init__.py
  tests/unit/service/tile/test_tile_task_executor.py
Labels: bug

#1470 feature: add user defined function SDK api object
  .changelog/DEV-1835.yaml
  featurebyte/__init__.py
  featurebyte/api/api_handler/user_defined_function.py
  featurebyte/api/api_object.py
  featurebyte/api/catalog.py
  featurebyte/api/catalog_get_by_id_mixin.py
  featurebyte/api/user_defined_function.py
  featurebyte/api/user_defined_function_injector.py
  featurebyte/enum.py
  featurebyte/models/user_defined_function.py
  featurebyte/query_graph/node/function.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  tests/unit/api/test_catalog.py
  tests/unit/api/test_user_defined_function.py
  tests/unit/api/test_user_defined_function_injector.py
  tests/unit/common/documentation/test_documentation_layout.py
  tests/unit/models/test_user_defined_function.py
  tests/unit/query_graph/test_function.py
  tests/unit/query_graph/test_graph_pruning.py
  tests/unit/routes/test_user_defined_function.py
Labels: enhancement

#1475 [Workflow] sync with infrastructure + upgrade to larger runner
  .github/workflows/test_gen.yaml
Labels: Skip Changelog

#1478 fix: revise SDK code generation for UDF
  featurebyte/api/aggregator/base_aggregator.py
  featurebyte/api/user_defined_function.py
  featurebyte/api/user_defined_function_injector.py
  featurebyte/api/view.py
  featurebyte/query_graph/node/function.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  tests/fixtures/sdk_code/feature_with_udf_used_in_view.py
  tests/unit/api/test_user_defined_function.py
  tests/unit/query_graph/test_function.py
Labels: Skip Changelog

#1480 [DEV-1886] Temporary skip databrick integration tests
  .github/workflows/test_gen.yaml
Labels: Skip Changelog

#1483 [chore] Update SDK api reference docs for `UserDefinedFunction`
  featurebyte/api/user_defined_function.py
  featurebyte/common/documentation/constants.py
  featurebyte/common/documentation/custom_nav.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/common/documentation/pydantic_field_docs.py
  featurebyte/models/user_defined_function.py
  scripts/test-docs-setup.py
  tests/unit/common/documentation/test_documentation_layout.py
Labels: Documentation Changes Confirmed

#1488 [chore] Refactor `FeatureModel` & `FeatureNamespaceModel` for target models
  featurebyte/__init__.py
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/api/feature_namespace.py
  featurebyte/models/__init__.py
  featurebyte/models/feature.py
  featurebyte/models/feature_list.py
  featurebyte/models/feature_namespace.py
  featurebyte/models/target_namespace.py
  featurebyte/routes/feature/controller.py
  featurebyte/routes/feature_list/controller.py
  featurebyte/routes/feature_list_namespace/controller.py
  featurebyte/routes/feature_namespace/controller.py
  featurebyte/schema/feature.py
  featurebyte/schema/feature_list_namespace.py
  featurebyte/schema/feature_namespace.py
  featurebyte/schema/info.py
  featurebyte/schema/target_namespace.py
  featurebyte/service/default_version_mode.py
  featurebyte/service/deploy.py
  featurebyte/service/feature.py
  featurebyte/service/feature_list.py
  featurebyte/service/feature_namespace.py
  featurebyte/service/feature_readiness.py
  featurebyte/service/online_enable.py
  featurebyte/service/target.py
  featurebyte/service/validator/production_ready_validator.py
  featurebyte/worker/task/batch_feature_create.py
  tests/integration/feature_manager/conftest.py
  tests/integration/tile/conftest.py
  tests/unit/api/test_api_object.py
  tests/unit/api/test_change_view.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_feature_list.py
  tests/unit/api/test_item_view.py
  tests/unit/api/test_version.py
  tests/unit/conftest.py
  tests/unit/models/test_feature.py
  tests/unit/routes/test_feature.py
  tests/unit/service/test_feature_readiness.py
Labels: refactoring, Documentation Changes Confirmed

#1511 [chore] Refactor target api object
  featurebyte/api/feature.py
  featurebyte/api/feature_or_target_mixin.py
  featurebyte/api/target.py
  featurebyte/api/templates/doc_util.py
  featurebyte/api/templates/feature_or_target_doc.py
  featurebyte/query_graph/graph.py
  tests/unit/api/aggregator/test_forward_aggregator.py
  tests/unit/api/base_feature_or_target_test.py
  tests/unit/api/test_dimension_view.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_target.py
Labels: Documentation Changes Confirmed

#1526 [DEV-1943] Fix `JoinNode` operation structure extraction bug
  .changelog/DEV-1943.yaml
  featurebyte/api/item_view.py
  featurebyte/query_graph/graph.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/node/metadata/operation.py
  tests/integration/api/test_scd_view_operations.py
  tests/unit/api/test_feature_store.py
  tests/unit/api/test_scd_view.py
  tests/unit/conftest.py
  tests/unit/query_graph/test_extract_operation_structure.py
  tests/unit/query_graph/test_graph_pruning.py
  tests/unit/query_graph/test_metadata_operation.py
  tests/unit/session/test_snowflake_session.py
Labels: bug

#1532 [chore][DEV-1831] target: add target to documentation
  featurebyte/__init__.py
  featurebyte/api/target.py
  featurebyte/api/target_namespace.py
  featurebyte/common/documentation/constants.py
  featurebyte/common/documentation/custom_nav.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/common/documentation/pydantic_field_docs.py
  tests/unit/common/documentation/test_extract_csv.py
Labels: Documentation Changes Confirmed

#1539 [DEV-1956] api/target: add primary_entity property
  .changelog/DEV-1956.yaml
  featurebyte/api/feature.py
  featurebyte/api/feature_or_target_mixin.py
  featurebyte/api/target.py
  featurebyte/api/templates/feature_or_target_doc.py
  featurebyte/common/documentation/documentation_layout.py
Labels: Documentation Changes Confirmed

#1541 [chore] add some target endpoints to catalog docs
  featurebyte/api/catalog_get_by_id_mixin.py
  featurebyte/api/groupby.py
  featurebyte/common/documentation/documentation_layout.py
  tests/unit/api/test_catalog.py
Labels: Documentation Changes Confirmed

#1548 [DEV-1960] Fix feature readiness bug & add tests
  .changelog/DEV-1960.yaml
  featurebyte/service/feature_readiness.py
  tests/unit/api/test_version.py
Labels: bug

#1543 [chore][DEV-1952] target: update docstrings for a couple of series fns
  featurebyte/api/feature.py
  featurebyte/api/target.py
  featurebyte/api/templates/series_doc.py
Labels: Documentation Changes Confirmed

#1556 bug fix on generated SDK code using static versioning
  tests/unit/api/test_feature.py
  tests/unit/api/test_target.py
Labels: bug, Skip Changelog, port/backport

#1557 fix: on generated SDK code using static versioning
  tests/unit/api/test_feature.py
  tests/unit/api/test_target.py
Labels: port/backport

#1563 [0.4][DEV-1976] Fix incorrect entity_id for columns derived from add_feature() (#1562)
  .changelog/DEV-1976.yaml
  featurebyte/api/event_view.py
  tests/unit/api/test_event_view.py
  tests/unit/conftest.py
Labels: bug

#1565 [changelog] porting DEV-1979 changelog to CHANGELOG.md
  .changelog/DEV-1976.yaml
  CHANGELOG.md
Labels: Skip Changelog

#1566 [chore] api/target: add a couple more docs for target
  featurebyte/api/target.py
  featurebyte/api/target_table.py
  featurebyte/common/documentation/constants.py
  featurebyte/common/documentation/custom_nav.py
  featurebyte/common/documentation/documentation_layout.py
  tests/integration/api/test_target_correctness.py
Labels: Documentation Changes Confirmed

#1569 [chore] yanked 0.4.0 and adding dates Changelog.md
  CHANGELOG.md
Labels: documentation, Skip Changelog, Documentation Changes Confirmed

#1570 [chore] Refactor feature related services
  Taskfile.yaml
  featurebyte/routes/feature/controller.py
  featurebyte/routes/feature_namespace/controller.py
  featurebyte/routes/registry.py
  featurebyte/service/feature_facade.py
Labels: refactoring, Skip Changelog

#1553 [DEV-1969] Configurations refactoring to singleton
  .changelog/DEV-1969.yaml
  .github/workflows/changelog_gen.yaml
  Taskfile.yaml
  featurebyte/__init__.py
  featurebyte/api/api_object.py
  featurebyte/api/feature.py
  featurebyte/api/target.py
  featurebyte/config.py
  featurebyte/core/generic.py
  featurebyte/core/series.py
  featurebyte/core/util.py
  featurebyte/logging.py
  featurebyte/query_graph/node/nested.py
  featurebyte/query_graph/sql/ast/aggregate.py
  featurebyte/query_graph/sql/ast/base.py
  featurebyte/query_graph/sql/specs.py
  featurebyte/service/mixin.py
  featurebyte/worker/task_executor.py
  poetry.lock
  pyproject.toml
  tests/unit/api/test_deployment.py
  tests/unit/api/test_feature_list.py
  tests/unit/conftest_config.py
  tests/unit/test_config.py
  tests/unit/test_generate_payload_fixtures.py
  tests/unit/test_init.py
Labels: bug, breaking

#1579 [chore] Refactor feature list related services
  featurebyte/routes/feature_list/controller.py
  featurebyte/routes/feature_list_namespace/controller.py
  featurebyte/routes/registry.py
  featurebyte/service/feature_facade.py
  featurebyte/service/feature_list_facade.py
Labels: refactoring

#1580 [chore] Refactor redis into app container component
  featurebyte/app.py
  featurebyte/migration/run.py
  featurebyte/routes/lazy_app_container.py
  featurebyte/worker/__init__.py
  featurebyte/worker/task/base.py
  featurebyte/worker/task_executor.py
  tests/integration/conftest.py
  tests/unit/conftest.py
  tests/unit/routes/relationship_info/test_api.py
  tests/unit/routes/test_lazy_app_container.py
  tests/unit/service/conftest.py
  tests/unit/worker/task/base.py
  tests/unit/worker/test_task_executor.py
Labels: refactoring

#1576 [DEV-1983] Make sure catalog.list_*() output dataframe is JSON serializable
  .changelog/DEV-1983.yaml
  featurebyte/api/api_handler/base.py
  featurebyte/api/api_handler/catalog.py
  featurebyte/api/api_object_util.py
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/feature_utility.py
  tests/unit/api/base_materialize_table_test.py
  tests/unit/api/conftest.py
  tests/unit/api/test_api_object.py
  tests/unit/api/test_batch_feature_table.py
  tests/unit/api/test_batch_request_table.py
  tests/unit/api/test_catalog.py
  tests/unit/api/test_credential.py
  tests/unit/api/test_deployment.py
  tests/unit/api/test_entity.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_feature_job_setting_analysis.py
  tests/unit/api/test_feature_list.py
  tests/unit/api/test_feature_store.py
  tests/unit/api/test_observation_table.py
  tests/unit/api/test_static_source_table.py
  tests/unit/api/test_user_defined_function.py
Labels: bug

#1586 [DEV-1985] Add support for updating column descriptions
  .changelog/DEV-1985.yaml
  featurebyte/api/base_table.py
  featurebyte/middleware.py
  featurebyte/query_graph/model/column_info.py
  featurebyte/routes/common/base_table.py
  featurebyte/routes/dimension_table/api.py
  featurebyte/routes/event_table/api.py
  featurebyte/routes/item_table/api.py
  featurebyte/routes/scd_table/api.py
  featurebyte/schema/info.py
  featurebyte/schema/table.py
  tests/unit/api/test_change_view.py
  tests/unit/api/test_dimension_table.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_item_table.py
  tests/unit/api/test_scd_table.py
  tests/unit/api/test_table_column.py
  tests/unit/core/test_frame.py
  tests/unit/models/test_dimension_table.py
  tests/unit/models/test_event_table.py
  tests/unit/models/test_scd_table.py
  tests/unit/query_graph/model/test_table_data.py
  tests/unit/routes/base.py
Labels: enhancement

#1587 [DEV-1971] Store more information in celery task results
  featurebyte/common/progress.py
  featurebyte/models/task.py
  featurebyte/query_graph/sql/feature_historical.py
  featurebyte/schema/task.py
  featurebyte/service/deploy.py
  featurebyte/service/historical_features.py
  featurebyte/service/target_helper/base_feature_or_target_computer.py
  featurebyte/service/task_manager.py
  featurebyte/service/tile_cache.py
  featurebyte/service/tile_manager.py
  featurebyte/tile/tile_cache.py
  featurebyte/utils/messaging.py
  featurebyte/worker/__init__.py
  featurebyte/worker/task/base.py
  featurebyte/worker/task/batch_feature_create.py
  featurebyte/worker/task/feature_job_setting_analysis.py
  featurebyte/worker/task/feature_list_batch_feature_create.py
  featurebyte/worker/task/test_task.py
  featurebyte/worker/task_executor.py
  tests/integration/conftest.py
  tests/integration/tile/test_tile_scheduler.py
  tests/integration/worker/test_task_manager.py
  tests/unit/conftest.py
  tests/unit/query_graph/test_feature_historical.py
  tests/unit/service/test_task_manager.py
  tests/unit/tile/test_unit_snowflake_tile.py
  tests/unit/worker/task/base.py
  tests/unit/worker/test_task_executor.py
  tests/util/task.py
Labels: enhancement, Skip Changelog

#1574 [DEV-1996] update compute_target to return observation table instead
  .changelog/DEV-1996.yaml
  featurebyte/api/catalog.py
  featurebyte/api/catalog_get_by_id_mixin.py
  featurebyte/api/target.py
  featurebyte/api/target_table.py
  featurebyte/common/documentation/constants.py
  featurebyte/common/documentation/custom_nav.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/models/observation_table.py
  featurebyte/models/request_input.py
  featurebyte/schema/target_table.py
  featurebyte/schema/worker/task/target_table.py
  featurebyte/worker/task/target_table.py
  tests/integration/api/test_target_correctness.py
  tests/unit/api/test_catalog.py
  tests/unit/api/test_target_table.py
  tests/unit/routes/test_target_table.py
  tests/unit/test_generate_payload_fixtures.py
Labels: Documentation Changes Confirmed
