Repository featurebyte/featurebyte, pull requests merged in 2023-09, with the labels that each got.

#1705 [DEV-2206] make update_description update namespaces for versioned assets [0.4]
  .changelog/DEV-2206.yaml
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/api/target.py
  tests/unit/api/base_feature_or_target_test.py
  tests/unit/api/test_feature_list.py
Labels: enhancement

#1708 [chore][DEV-2209] deployment: add get_feature_jobs_status docs
  featurebyte/api/deployment.py
  featurebyte/common/documentation/documentation_layout.py
Labels: Documentation Changes Confirmed

#1709 [DEV-2198] Use Context name instead of Context id for the API signature
  .changelog/DEV-2198_3.yaml
  featurebyte/api/source_table.py
  featurebyte/api/view.py
  tests/unit/conftest.py
Labels: enhancement, Documentation Changes Confirmed

#1712 [DEV-2215] Organize exceptions to reduce verbosity in middleware
  .changelog/DEV-2215.yaml
  featurebyte/exception.py
  featurebyte/middleware.py
  tests/unit/service/test_base_document.py
  tests/unit/test_middleware.py
Labels: enhancement

#1719 [Release] 0.5.0 release chores
  .changelog/DEV-1849.yaml
  .changelog/DEV-1964.yaml
  .changelog/DEV-1969.yaml
  .changelog/DEV-1970.yaml
  .changelog/DEV-1973.yaml
  .changelog/DEV-1974.yaml
  .changelog/DEV-1985.yaml
  .changelog/DEV-1987.yaml
  .changelog/DEV-1991.yaml
  .changelog/DEV-2026-2.yaml
  .changelog/DEV-2026.yaml
  .changelog/DEV-2034.yaml
  .changelog/DEV-2038.yaml
  .changelog/DEV-2041.yaml
  .changelog/DEV-2063.yaml
  .changelog/DEV-2065.yaml
  .changelog/DEV-2067.yaml
  .changelog/DEV-2068.yaml
  .changelog/DEV-2069.yaml
  .changelog/DEV-2075.yaml
  .changelog/DEV-2076.yaml
  .changelog/DEV-2077.yaml
  .changelog/DEV-2078.yaml
  .changelog/DEV-2082.yaml
  .changelog/DEV-2083.yaml
  .changelog/DEV-2087.yaml
  .changelog/DEV-2093.yaml
  .changelog/DEV-2129.yaml
  .changelog/DEV-2134.yaml
  .changelog/DEV-2135.yaml
  .changelog/DEV-2161.yaml
  .changelog/DEV-2165.yaml
  .changelog/DEV-2166.yaml
  .changelog/DEV-2167-2.yaml
  .changelog/DEV-2167.yaml
  .changelog/DEV-2169.yaml
  .changelog/DEV-2173.yaml
  .changelog/DEV-2177.yaml
  .changelog/DEV-2194.yaml
  .changelog/DEV-2195.yaml
  .changelog/DEV-2198.yaml
  .changelog/DEV-2198_3.yaml
  .changelog/DEV-2200.yaml
  .changelog/DEV-2206.yaml
  .changelog/DEV-2207.yaml
  .changelog/DEV-2215.yaml
  .changelog/DEV-2216.yaml
  .changelog/DEV-2219.yaml
  .changelog/chore-python-constraint.yaml
  .changelog/chore-vuln.yaml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: documentation, dependencies, Skip Changelog, Documentation Changes Confirmed

#1721 [chore][workflow] remove building docker image to artifact registry
  .github/workflows/publish-dev_gen.yaml
Labels: github_actions, Skip Changelog

#1718 [chore] Fix batch feature create task description
  featurebyte/worker/task/batch_feature_create.py
  tests/unit/worker/task/test_batch_feature_create.py
Labels: bug, Skip Changelog

#1725 [DEV-2233] Restore missing cryptography dependency
  .changelog/DEV-2233.yaml
  poetry.lock
  pyproject.toml
Labels: bug, dependencies

#1727 [DEV-2233] [Cherrypick] Restore missing cryptography dependency (#1725)
  .changelog/DEV-2233.yaml
  poetry.lock
  pyproject.toml
Labels: bug, dependencies

#1728 [chore][Cherrypick] Optimize feature readiness computation
  .changelog/chore-optimize-feature-readiness-service.yaml
  featurebyte/routes/deployment/controller.py
  featurebyte/routes/feature_namespace/controller.py
  featurebyte/service/base_document.py
  featurebyte/service/feature.py
  featurebyte/service/feature_list.py
  featurebyte/service/feature_readiness.py
  featurebyte/service/validator/production_ready_validator.py
  tests/unit/service/test_feature.py
  tests/unit/service/test_feature_list.py
  tests/unit/service/test_feature_readiness.py
Labels: dependencies

#1730 [Release] version to 0.5.1 and removed changelog entries
  .changelog/DEV-2233.yaml
  .changelog/chore-optimize-feature-readiness-service.yaml
  CHANGELOG.md
  pyproject.toml
Labels: Skip Changelog

#1732 [chore] Add retry for feature readiness update
  featurebyte/service/feature_readiness.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#1733 [chore] Add request retry for api client
  featurebyte/config.py
  pyproject.toml
  tests/unit/conftest.py
  tests/unit/test_config.py
Labels: enhancement

#1737 [chore] Cherry pick fixes to 0.5
  featurebyte/config.py
  featurebyte/service/feature_store_warehouse.py
  featurebyte/session/base.py
  featurebyte/session/hive.py
  pyproject.toml
  tests/unit/api/test_observation_table.py
  tests/unit/api/test_static_source_table.py
  tests/unit/conftest.py
  tests/unit/routes/test_feature_store.py
  tests/unit/test_config.py
Labels: dependencies

#1744 adding missing changelogs
  .changelog/api-client.yaml
  .changelog/error-validation.yaml
  .changelog/hive-connection.yaml
Labels: dependencies

#1742 [chore] cherry pick vector items onto release/0.5
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/session/base_spark.py
  featurebyte/session/snowflake.py
  featurebyte/sql/snowflake/F_VECTOR_COSINE_SIMILARITY.sql
  hive-udf/lib/src/main/java/com/featurebyte/hive/udf/VectorCosineSimilarity.java
  tests/integration/udf/snowflake/util.py
  tests/integration/udf/spark/util.py
  tests/integration/udf/test_vector_cosine_similarity.py
  tests/unit/query_graph/sql/adapter/base_adapter_test.py
  tests/unit/query_graph/sql/adapter/test_snowflake.py
Labels: dependencies

#1748 [DEV-2242] distance: add haversine distance calculation
  .changelog/DEV-2242-2.yaml
  .github/workflows/test_gen.yaml
  featurebyte/__init__.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/common/documentation/gen_ref_pages_docs_builder.py
  featurebyte/core/distance.py
  featurebyte/query_graph/enum.py
  featurebyte/query_graph/node/distance.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/query_graph/sql/ast/distance.py
  tests/integration/api/fixtures/distance.csv
  tests/integration/api/test_distance_operations.py
  tests/unit/core/test_haversine.py
  tests/unit/query_graph/sql/adapter/base_adapter_test.py
  tests/unit/query_graph/sql/adapter/test_snowflake.py
  tests/unit/query_graph/test_sdk_code_generation.py
Labels: Documentation Changes Confirmed

#1754 [DEV-2254] Support rprefix parameter when joining views
  .changelog/DEV-2254.yaml
  featurebyte/api/item_table.py
  featurebyte/api/view.py
  featurebyte/common/join_utils.py
  featurebyte/query_graph/model/table.py
  featurebyte/query_graph/node/generic.py
  tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
  tests/fixtures/sdk_code/event_view_with_tz_offset_column.py
  tests/unit/api/test_join_utils.py
  tests/unit/api/test_scd_view.py
  tests/unit/api/test_view.py
  tests/unit/query_graph/test_graph_pruning.py
Labels: Documentation Changes Confirmed

#1756 [DEV-1517] Update feature list create new version
  .changelog/DEV-1517.yaml
  featurebyte/api/feature_list.py
  featurebyte/schema/feature_list.py
  featurebyte/service/version.py
  tests/unit/api/test_feature_list.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_list.py
Labels: Documentation Changes Confirmed

#1757 [DEV-2311] Add last_updated_at in FeatureModel
  .changelog/DEV-2311.yaml
  featurebyte/models/feature.py
  featurebyte/service/feature.py
  featurebyte/service/tile/tile_task_executor.py
  tests/unit/api/test_feature.py
  tests/unit/models/test_feature.py
  tests/unit/service/test_feature.py
Labels: enhancement

#1771 [DEV-2325] Use primary entity parameter in Target and Context creation
  .changelog/DEV-2325.yaml
  featurebyte/api/context.py
  featurebyte/api/target_namespace.py
  scripts/test-docs-setup.py
  tests/unit/api/test_context.py
  tests/unit/api/test_target_namespace.py
Labels: Documentation Changes Confirmed

#1777 [DEV-2332] Refactor online serving code template generation
  .changelog/DEV-2332.yaml
  featurebyte/api/deployment.py
  featurebyte/exception.py
  featurebyte/routes/deployment/api.py
  featurebyte/routes/deployment/controller.py
  featurebyte/schema/info.py
  featurebyte/service/online_serving.py
  featurebyte/service/templates/__init__.py
  featurebyte/service/templates/online_serving/__init__.py
  featurebyte/service/templates/online_serving/python.tpl
  featurebyte/service/templates/online_serving/sh.tpl
  tests/unit/api/test_deployment.py
Labels: documentation, Documentation Changes Confirmed

#1780 [DEV-2334] Handle null values when converting string to variant types
  .changelog/DEV-2334.yaml
  featurebyte/common/utils.py
  featurebyte/session/spark.py
Labels: bug

#1759 [DEV-2314] observation_table: tag entity_ids when creating observation table
  .changelog/DEV-2314.yaml
  featurebyte/api/observation_table.py
  featurebyte/models/materialized_table.py
  featurebyte/service/batch_request_table.py
  featurebyte/service/historical_feature_table.py
  featurebyte/service/materialized_table.py
  featurebyte/service/observation_table.py
  featurebyte/service/static_source_table.py
  featurebyte/service/target_table.py
  featurebyte/worker/task/observation_table.py
  featurebyte/worker/task/static_source_table.py
  featurebyte/worker/task/target_table.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_target_correctness.py
  tests/unit/service/test_observation_table.py
  tests/util/helper.py
Labels: Documentation Changes Confirmed

#1782 [DEV-2354] Context entity renamed to primary_entity & Add Validation when Creation
  .changelog/DEV-2335.yaml
  featurebyte/api/context.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/models/context.py
  featurebyte/routes/context/api.py
  featurebyte/routes/context/controller.py
  featurebyte/routes/use_case/controller.py
  featurebyte/schema/context.py
  featurebyte/schema/info.py
  featurebyte/service/context.py
  featurebyte/service/observation_table.py
  featurebyte/service/use_case.py
  tests/fixtures/request_payloads/context.json
  tests/unit/api/test_context.py
  tests/unit/conftest.py
  tests/unit/routes/test_context.py
  tests/unit/routes/test_use_case.py
  tests/unit/service/test_context.py
  tests/unit/test_generate_payload_fixtures.py
Labels: Documentation Changes Confirmed
