Repository featurebyte/featurebyte, pull requests merged in 2023-10, with the labels that each got.

#1789 [chore] docs: add key_with_(lowest|highest)_value
  featurebyte/common/documentation/documentation_layout.py
Labels: Documentation Changes Confirmed

#1781 [DEV-2318] observation_table: validate entities are present on creation
  .changelog/DEV-2318.yaml
  featurebyte/api/source_table.py
  featurebyte/api/target.py
  featurebyte/api/view.py
  featurebyte/schema/observation_table.py
  featurebyte/schema/target_table.py
  featurebyte/service/observation_table.py
  featurebyte/worker/task/observation_table.py
  featurebyte/worker/task/target_table.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_observation_table.py
Labels: Documentation Changes Confirmed

#1792 [chore][DEV-2365] sample: update docs to indicate upper bound of 10k rows
  featurebyte/api/base_table.py
  featurebyte/api/batch_feature_table.py
  featurebyte/api/batch_request_table.py
  featurebyte/api/historical_feature_table.py
  featurebyte/api/materialized_table.py
  featurebyte/api/observation_table.py
  featurebyte/api/source_table.py
  featurebyte/api/static_source_table.py
  featurebyte/api/view.py
  featurebyte/core/mixin.py
Labels: Documentation Changes Confirmed

#1795 [chore][DEV-1502] docs: mv table#catalog_id to table>lineage
  featurebyte/common/documentation/documentation_layout.py
Labels: Documentation Changes Confirmed

#1799 Documentation for UseCase and Context
  .changelog/DEV-2395.yaml
  featurebyte/api/context.py
  featurebyte/api/use_case.py
Labels: Documentation Changes Confirmed

#1801 [DEV-2399] observation_table: track earliest point in time and entity count
  .changelog/DEV-2399.yaml
  featurebyte/models/observation_table.py
  featurebyte/query_graph/sql/materialisation.py
  featurebyte/service/observation_table.py
  featurebyte/worker/task/observation_table.py
  featurebyte/worker/task/target_table.py
  tests/integration/api/test_observation_table.py
  tests/unit/service/test_observation_table.py
Labels: Documentation Changes Confirmed

#1803 [chore] Implement route to retrieve sample entity_serving_names for a deployment
  Taskfile.yaml
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/routes/deployment/api.py
  featurebyte/routes/deployment/controller.py
  featurebyte/schema/info.py
  featurebyte/service/online_serving.py
  poetry.lock
  pyproject.toml
  tests/integration/conftest.py
  tests/unit/api/test_deployment.py
  tests/unit/routes/test_deployment.py
Labels: dependencies

#1804 [chore] Fix sample_entity_serving_names request counts exceed unique values
  featurebyte/service/online_serving.py
  tests/unit/routes/test_deployment.py
Labels: bug, Skip Changelog

#1808 [DEV-2409] observation_table: add route to allow users to upload a CSV file to create OT
  .changelog/DEV-2409.yaml
  featurebyte/enum.py
  featurebyte/models/observation_table.py
  featurebyte/models/request_input.py
  featurebyte/routes/observation_table/api.py
  featurebyte/routes/observation_table/controller.py
  featurebyte/schema/observation_table.py
  featurebyte/schema/worker/task/observation_table_upload.py
  featurebyte/service/observation_table.py
  featurebyte/worker/task/observation_table_upload.py
  tests/integration/api/fixtures/observation_table.csv
  tests/integration/api/test_observation_table.py
  tests/unit/routes/test_observation_table.py
  tests/unit/worker/task/test_observation_table_upload.py
Labels: Documentation Changes Confirmed

#1810 [Release] Cut branch 0.6
  .changelog/DEV-1517.yaml
  .changelog/DEV-2230.yaml
  .changelog/DEV-2241.yaml
  .changelog/DEV-2242-2.yaml
  .changelog/DEV-2242.yaml
  .changelog/DEV-2254.yaml
  .changelog/DEV-2259.yaml
  .changelog/DEV-2285-2.yaml
  .changelog/DEV-2285.yaml
  .changelog/DEV-2293.yaml
  .changelog/DEV-2311.yaml
  .changelog/DEV-2314.yaml
  .changelog/DEV-2318.yaml
  .changelog/DEV-2321.yaml
  .changelog/DEV-2324.yaml
  .changelog/DEV-2324_2.yaml
  .changelog/DEV-2325.yaml
  .changelog/DEV-2326.yaml
  .changelog/DEV-2331.yaml
  .changelog/DEV-2332.yaml
  .changelog/DEV-2334.yaml
  .changelog/DEV-2335.yaml
  .changelog/DEV-2352.yaml
  .changelog/DEV-2355.yaml
  .changelog/DEV-2356.yaml
  .changelog/DEV-2364.yaml
  .changelog/DEV-2366.yaml
  .changelog/DEV-2385.yaml
  .changelog/DEV-2385_2.yaml
  .changelog/DEV-2393.yaml
  .changelog/DEV-2395.yaml
  .changelog/DEV-2398.yaml
  .changelog/DEV-2399.yaml
  .changelog/DEV-2408.yaml
  .changelog/DEV-2409.yaml
  .changelog/api-client.yaml
  .changelog/error-validation.yaml
  .changelog/hive-connection.yaml
  CHANGELOG.md
  pyproject.toml
Labels: Skip Changelog

#1820 [DEV-2345] Enable ObservationTable with multiple use cases - Part 1
  .changelog/DEV-2435_1.yaml
  featurebyte/exception.py
  featurebyte/models/observation_table.py
  featurebyte/routes/observation_table/controller.py
  featurebyte/schema/observation_table.py
  featurebyte/service/observation_table.py
  tests/unit/routes/test_observation_table.py
Labels: Documentation Changes Confirmed

#1836 [chore] Bump fastapi version to speed up get_app
  poetry.lock
  pyproject.toml
  tests/unit/test_app.py
Labels: dependencies

#1838 [chore] Cleanup feature list default version mode
  featurebyte/api/feature_list.py
  featurebyte/models/feature_list.py
  featurebyte/schema/info.py
  featurebyte/service/feature_list.py
  featurebyte/service/feature_list_facade.py
  featurebyte/service/feature_list_namespace.py
  tests/unit/api/test_feature_list.py
  tests/unit/models/test_feature_list.py
  tests/unit/routes/test_feature_list.py
  tests/unit/routes/test_feature_list_namespace.py
  tests/unit/service/conftest.py
  tests/unit/service/test_feature_list_namespace.py
Labels: Documentation Changes Confirmed

#1839 [DEV-2463] observation_table: add minimum interval between entities
  .changelog/DEV-2463.yaml
  featurebyte/models/observation_table.py
  featurebyte/service/observation_table.py
  tests/integration/api/fixtures/observation_table_time_interval.csv
  tests/integration/api/test_observation_table.py
  tests/unit/service/test_observation_table.py
Labels: Documentation Changes Confirmed

#1859 [DEV-2485] Bump freeware to include bug fix for feature job setting analysis deserialization
  .changelog/DEV-2485.yaml
  poetry.lock
Labels: bug

#1865 [DEV-2491] Fix Feature Job Settings Analysis failing for DataBricks Feature Store
  .changelog/DEV-2491.yaml
  featurebyte/worker/task/feature_job_setting_analysis.py
  tests/unit/worker/task/test_feature_job_setting_analysis.py
Labels: bug

#1877 [DEV-2503] use_case: look up target namespace instead of target
  .changelog/DEV-2503.yaml
  featurebyte/api/use_case.py
  tests/unit/api/conftest.py
  tests/unit/api/test_context.py
  tests/unit/api/test_use_case.py
Labels: Documentation Changes Confirmed
