Repository featurebyte/featurebyte, pull requests merged in 2023-08, with the labels that each got.

#1589 [DEV-1992] Remove `version_mode` from `FeatureList` asset
  featurebyte/api/feature_list.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/routes/feature_list_namespace/controller.py
  featurebyte/routes/registry.py
  featurebyte/schema/feature_list_namespace.py
  featurebyte/service/default_version_mode.py
  featurebyte/service/deploy.py
  featurebyte/service/feature_facade.py
  featurebyte/service/feature_list_facade.py
  featurebyte/service/feature_readiness.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_feature_list.py
  tests/unit/api/test_version.py
  tests/unit/routes/test_feature_list.py
  tests/unit/routes/test_feature_list_namespace.py
  tests/unit/service/test_default_version_mode.py
  tests/unit/service/test_deploy.py
  tests/unit/service/test_feature_readiness.py
  tests/unit/service/test_version.py
Labels: breaking, Documentation Changes Confirmed

#1594 [chore] docs: rm links from method names
  featurebyte/common/documentation/autodoc_processor.py
Labels: Documentation Changes Confirmed

#1590 [DEV-1985] make table update service backward compatible to earlier clients
  featurebyte/routes/common/base_table.py
  featurebyte/schema/table.py
  tests/unit/routes/base.py
Labels: bug

#1596 [DEV-2001] Support creation of feature job analysis without using event table id
  featurebyte/models/feature_job_setting_analysis.py
  featurebyte/routes/feature_job_setting_analysis/controller.py
  featurebyte/schema/feature_job_setting_analysis.py
  featurebyte/service/feature_job_setting_analysis.py
  featurebyte/worker/task/feature_job_setting_analysis.py
  tests/unit/api/test_event_table.py
  tests/unit/routes/test_feature_job_setting_analysis.py
  tests/unit/worker/task/test_feature_job_setting_analysis.py
Labels: Documentation Changes Confirmed

#1600 [CHORE] skip vulnerability for cryptography package
  Taskfile.yaml
Labels: Skip Changelog

#1603 [DEV-2024] forward_aggregate: add fill_value and skip_fill_na
  .changelog/DEV-2024.yaml
  featurebyte/api/aggregator/base_aggregator.py
  featurebyte/api/aggregator/forward_aggregator.py
  featurebyte/api/groupby.py
  featurebyte/query_graph/node/generic.py
  tests/unit/api/aggregator/test_forward_aggregator.py
  tests/unit/api/test_target.py
Labels: Documentation Changes Confirmed

#1599 [ISSUES-1598] Update is_notebook to support Google Colab and Databricks
  .changelog/ISSUES-1598.yaml
  featurebyte/common/env_util.py
Labels: bug

#1609 [DEV-1939] api/view: add as_target to view column
  .changelog/DEV-1939-2.yaml
  featurebyte/api/aggregator/base_aggregator.py
  featurebyte/api/aggregator/forward_aggregator.py
  featurebyte/api/event_view.py
  featurebyte/api/item_view.py
  featurebyte/api/scd_view.py
  featurebyte/api/view.py
  featurebyte/api/window_validator.py
  tests/unit/api/test_dimension_view.py
Labels: Documentation Changes Confirmed

#1610 [DEV-2031] Speed up operation structure extraction by caching the result of _extract()
  .changelog/DEV-2031.yaml
  featurebyte/query_graph/transform/base.py
Labels: bug

#1615 [0.4][DEV-2031] Speed up operation structure extraction by caching the result of _extract()
  .changelog/DEV-2031.yaml
  featurebyte/query_graph/transform/base.py
Labels: bug

#1622 [chore][workflow] adding DATABRICKS_HTTP_PATH as a secret
  .github/workflows/test_gen.yaml
  featurebyte/session/base_spark.py
Labels: Skip Changelog, Documentation Changes Confirmed

#1621 [DEV-2035] Track backtest summary in feature job setting analyses
  featurebyte/models/feature_job_setting_analysis.py
  featurebyte/service/feature_job_setting_analysis.py
  featurebyte/worker/task/feature_job_setting_analysis.py
  tests/unit/routes/test_feature_job_setting_analysis.py
  tests/unit/worker/task/test_feature_job_setting_analysis_backtest.py
Labels: Skip Changelog, Documentation Changes Confirmed

#1632 [chore] Allow task commands to be overridden
  featurebyte/worker/task/base.py
  tests/unit/worker/test_task_executor.py
Labels: Skip Changelog

#1635 [DEV-2048] Fix feature materialisation error due to ambiguous internal column names
  .changelog/DEV-2048.yaml
  featurebyte/query_graph/sql/ast/aggregate.py
  featurebyte/query_graph/sql/ast/base.py
  featurebyte/query_graph/sql/ast/generic.py
  tests/integration/api/test_item_view_operations.py
  tests/unit/api/test_dimension_view.py
  tests/unit/query_graph/sql/ast/test_special_operations.py
  tests/unit/query_graph/test_sql.py
Labels: bug

#1634 [chore] to_timedelta: update examples
  featurebyte/core/timedelta.py
Labels: Documentation Changes Confirmed

#1640 [0.4][DEV-2044] Fix error when retrieving feature info for some features
  .changelog/DEV-2044.yaml
  featurebyte/models/feature.py
  featurebyte/routes/common/feature_metadata_extractor.py
  featurebyte/routes/feature/controller.py
  featurebyte/routes/target/controller.py
  tests/unit/api/conftest.py
  tests/unit/api/test_scd_view.py
Labels: bug

#1633 [DEV-1851] Update README to mention hosted tutorials
  README.md
Labels: Skip Changelog

#1641 [0.4][DEV-2048] Fix feature materialisation error due to ambiguous internal column names
  .changelog/DEV-2048.yaml
  featurebyte/query_graph/sql/ast/aggregate.py
  featurebyte/query_graph/sql/ast/base.py
  featurebyte/query_graph/sql/ast/generic.py
  tests/integration/api/test_item_view_operations.py
  tests/unit/api/test_dimension_view.py
  tests/unit/query_graph/sql/ast/test_special_operations.py
  tests/unit/query_graph/test_sql.py
Labels: bug

#1636 [chore] mv notebooks into docs to be able to render them
  .gitignore
  Taskfile.yaml
  docs/notebooks/deep dive data modeling - final.ipynb
  docs/notebooks/deep dive feature engineering - final.ipynb
  docs/notebooks/deep dive materializing features - final.ipynb
  docs/notebooks/playground credit cards.ipynb
  docs/notebooks/playground healthcare.ipynb
  docs/notebooks/prebuilt_catalogs.py
  docs/notebooks/quick start end-to-end workflow - final.ipynb
  docs/notebooks/quick start feature engineering - final.ipynb
  docs/notebooks/quick start feature management - final.ipynb
  docs/notebooks/quick start model training - final.ipynb
  docs/notebooks/quick start reusing features - final.ipynb
  mkdocs.yaml
  poetry.lock
  pyproject.toml
  tests/notebooks/test_notebooks.py
Labels: dependencies, Documentation Changes Confirmed

#1649 [DEV-2051][DEV-2079] Fix item table default job setting not synchronized with event table
  .changelog/DEV-2051.yaml
  featurebyte/api/item_table.py
  featurebyte/schema/historical_feature_table.py
Labels: bug, documentation, Documentation Changes Confirmed

#1651 [DEV-2087] Tag semantics for all special columns during table creation
  .changelog/DEV-2087.yaml
  featurebyte/enum.py
  featurebyte/routes/common/base_table.py
  featurebyte/routes/dimension_table/controller.py
  featurebyte/routes/event_table/controller.py
  featurebyte/routes/item_table/controller.py
  featurebyte/routes/scd_table/controller.py
  featurebyte/service/table_info.py
  tests/unit/api/test_change_view.py
  tests/unit/api/test_dimension_table.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_item_table.py
  tests/unit/api/test_scd_table.py
  tests/unit/routes/test_dimension_table.py
  tests/unit/routes/test_event_table.py
  tests/unit/routes/test_item_table.py
  tests/unit/routes/test_scd_table.py
Labels: enhancement

#1655 [chore] source_table: fix typo in create_scd_table docs
  featurebyte/api/source_table.py
Labels: Documentation Changes Confirmed

#1656 [DEV-2105] Skip scheduling of duplicate online store cleanup job with a warning
  featurebyte/service/online_store_cleanup_scheduler.py
Labels: bug

#1660 [chore] target: some minor updates to target and feature docs
  featurebyte/api/feature.py
  featurebyte/common/documentation/custom_nav.py
  featurebyte/common/documentation/documentation_layout.py
  tests/unit/common/documentation/test_documentation_layout.py
Labels: Documentation Changes Confirmed

#1667 [DEV-2137] Support case insensitive substring search on asset names
  featurebyte/service/base_document.py
  tests/unit/service/test_base_document.py
Labels: enhancement, Skip Changelog

#1668 [DEV-2140] Fix logic for determining timezone offset column in datetime accessor
  .changelog/DEV-2140.yaml
  featurebyte/core/accessor/datetime.py
  tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
  tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
  tests/fixtures/sdk_code/scd_table.py
  tests/unit/api/test_change_view.py
  tests/unit/api/test_scd_table.py
  tests/unit/api/test_scd_view.py
  tests/unit/api/test_timezone_offset.py
  tests/unit/conftest.py
Labels: bug

#1672 [chore] Include description in text indexing
  featurebyte/models/batch_feature_table.py
  featurebyte/models/batch_request_table.py
  featurebyte/models/catalog.py
  featurebyte/models/context.py
  featurebyte/models/credential.py
  featurebyte/models/deployment.py
  featurebyte/models/entity.py
  featurebyte/models/feature.py
  featurebyte/models/feature_job_setting_analysis.py
  featurebyte/models/feature_list.py
  featurebyte/models/feature_namespace.py
  featurebyte/models/feature_store.py
  featurebyte/models/historical_feature_table.py
  featurebyte/models/observation_table.py
  featurebyte/models/semantic.py
  featurebyte/models/static_source_table.py
  featurebyte/models/task.py
  featurebyte/models/use_case.py
  featurebyte/models/user_defined_function.py
  tests/unit/models/test_index.py
Labels: Skip Changelog

#1675 [DEV-2156] Fix invalid identifier error when combining simple aggregate and window aggregate features
  .changelog/DEV-2156.yaml
  featurebyte/query_graph/algorithm.py
  featurebyte/query_graph/model/graph.py
  featurebyte/query_graph/sql/feature_compute.py
  tests/fixtures/expected_feature_sql_combined_simple_aggregate_and_window_aggregate.sql
  tests/integration/api/test_features.py
  tests/unit/api/test_event_table.py
  tests/unit/conftest.py
  tests/unit/query_graph/sql/test_complex_feature.py
  tests/unit/query_graph/test_algorithm.py
Labels: bug

#1677 [0.4][DEV-2156] Fix invalid identifier error when combining simple aggregate and window aggregate features
  .changelog/DEV-2156.yaml
  featurebyte/query_graph/algorithm.py
  featurebyte/query_graph/model/graph.py
  featurebyte/query_graph/sql/feature_compute.py
  tests/fixtures/expected_feature_sql_combined_simple_aggregate_and_window_aggregate.sql
  tests/integration/api/test_features.py
  tests/unit/api/test_event_table.py
  tests/unit/conftest.py
  tests/unit/query_graph/sql/test_complex_feature.py
  tests/unit/query_graph/test_algorithm.py
Labels: bug

#1678 [0.4][DEV-2162] Fix conditional assignment sdk code generation bug
  .changelog/DEV-2162.yaml
  featurebyte/query_graph/node/generic.py
  tests/unit/api/test_sdk_code.py
Labels: bug

#1681 [DEV-2165] Cast online store columns to expected types when creating tables
  .changelog/DEV-2165.yaml
  featurebyte/sql/tile_schedule_online_store.py
Labels: bug

#1682 [DEV-2169] Fix feature saving issue due to tile sql generation bug
  .changelog/DEV-2169.yaml
  featurebyte/query_graph/sql/interpreter/tile.py
  tests/fixtures/graph/PRODUCT_vs_PRODUCTGROUP_item_TotalCost_across_customer_PostalCodes_28d.json
  tests/unit/query_graph/interpreter/test_interpreter.py
Labels: bug

#1684 [chore] Fix cleaning operation representation
  featurebyte/api/base_table.py
  featurebyte/api/view.py
  featurebyte/query_graph/node/cleaning_operation.py
  tests/unit/api/test_sdk_code.py
  tests/unit/query_graph/test_critical_data_info.py
  tests/unit/service/validator/test_production_ready_validator.py
Labels: Documentation Changes Confirmed

#1685 [DEV-2174][chore] docs: add list_deployment docs
  featurebyte/__init__.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/common/documentation/gen_ref_pages_docs_builder.py
  featurebyte/list_utility.py
Labels: Documentation Changes Confirmed

#1690 [chore] support profile registration using python client
  featurebyte/__init__.py
  tests/unit/test_init.py
Labels: enhancement

#1689 [DEV-2184] Populate description for asynchronous tasks
  featurebyte/models/task.py
  featurebyte/worker/task/base.py
  featurebyte/worker/task/batch_feature_create.py
  featurebyte/worker/task/batch_feature_table.py
  featurebyte/worker/task/batch_request_table.py
  featurebyte/worker/task/deployment_create_update.py
  featurebyte/worker/task/feature_job_setting_analysis.py
  featurebyte/worker/task/feature_list_batch_feature_create.py
  featurebyte/worker/task/historical_feature_table.py
  featurebyte/worker/task/materialized_table_delete.py
  featurebyte/worker/task/observation_table.py
  featurebyte/worker/task/online_store_cleanup.py
  featurebyte/worker/task/static_source_table.py
  featurebyte/worker/task/target_table.py
  featurebyte/worker/task/test_task.py
  featurebyte/worker/task/tile_task.py
  featurebyte/worker/task_executor.py
  tests/unit/api/test_event_table.py
  tests/unit/worker/task/test_batch_feature_create.py
  tests/unit/worker/task/test_batch_feature_table.py
  tests/unit/worker/task/test_batch_request_table.py
  tests/unit/worker/task/test_deployment_create_update.py
  tests/unit/worker/task/test_feature_job_setting_analysis.py
  tests/unit/worker/task/test_feature_job_setting_analysis_backtest.py
  tests/unit/worker/task/test_feature_list_batch_feature_create.py
  tests/unit/worker/task/test_historical_feature_table.py
  tests/unit/worker/task/test_materialized_table_delete.py
  tests/unit/worker/task/test_observation_table.py
  tests/unit/worker/task/test_online_store_cleanup.py
  tests/unit/worker/task/test_static_source_table.py
  tests/unit/worker/task/test_target_table.py
  tests/unit/worker/task/test_tile_task.py
  tests/unit/worker/test_task_executor.py
  tests/util/task.py
Labels: Skip Changelog

#1691 [chore] support profile registration using python client (#1690) [0.4]
  featurebyte/__init__.py
  tests/unit/test_init.py
Labels: enhancement

#1692 [DEV-2166] Implement API Object for UseCase
  .changelog/DEV-2166.yaml
  featurebyte/__init__.py
  featurebyte/api/api_object_util.py
  featurebyte/api/catalog.py
  featurebyte/api/catalog_get_by_id_mixin.py
  featurebyte/api/use_case.py
  featurebyte/models/use_case.py
  featurebyte/routes/use_case/api.py
  featurebyte/routes/use_case/controller.py
  featurebyte/schema/use_case.py
  featurebyte/service/use_case.py
  scripts/test-docs-setup.py
  tests/unit/api/test_catalog.py
  tests/unit/api/test_use_case.py
  tests/unit/common/documentation/test_documentation_layout.py
  tests/unit/conftest.py
  tests/unit/routes/test_use_case.py
Labels: enhancement

#1696 [chore] updated scipy dependency, reduced python valid range to >=3.8,<3.12
  .changelog/chore-python-constraint.yaml
  .changelog/chore-vuln.yaml
  .github/workflows/publish-dev_gen.yaml
  Taskfile.yaml
  poetry.lock
  pyproject.toml
Labels: bug, dependencies

#1700 [DEV-2198] Integrate Context API Object into UseCase
  .changelog/DEV-2198.yaml
  Taskfile.yaml
  featurebyte/api/source_table.py
  featurebyte/api/target.py
  featurebyte/api/use_case.py
  featurebyte/api/view.py
  featurebyte/models/use_case.py
  featurebyte/routes/use_case/api.py
  featurebyte/routes/use_case/controller.py
  featurebyte/schema/use_case.py
  featurebyte/service/use_case.py
  scripts/test-docs-setup.py
  tests/unit/api/test_context.py
  tests/unit/api/test_use_case.py
  tests/unit/conftest.py
  tests/unit/routes/test_use_case.py
Labels: Documentation Changes Confirmed

#1702 [DEV-2200] Associate Deployment with UseCase
  .changelog/DEV-2200.yaml
  featurebyte/api/feature_list.py
  featurebyte/api/use_case.py
  featurebyte/models/deployment.py
  featurebyte/routes/deployment/controller.py
  featurebyte/routes/use_case/api.py
  featurebyte/schema/deployment.py
  featurebyte/schema/info.py
  featurebyte/schema/worker/task/deployment_create_update.py
  featurebyte/service/deploy.py
  featurebyte/worker/task/deployment_create_update.py
  tests/unit/api/conftest.py
  tests/unit/api/test_deployment.py
  tests/unit/api/test_use_case.py
  tests/unit/routes/test_deployment.py
  tests/unit/routes/test_use_case.py
Labels: Documentation Changes Confirmed

#1704 [DEV-2206] make update_description update namespaces for versioned assets
  .changelog/DEV-2206.yaml
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/api/target.py
  tests/unit/api/base_feature_or_target_test.py
  tests/unit/api/test_feature_list.py
Labels: enhancement
