Repository featurebyte/featurebyte, pull requests merged in 2023-05, with the labels that each got.

#1277 docs: add feature string accessor
  featurebyte/api/feature.py
  featurebyte/common/documentation/gen_ref_pages_docs_builder.py
  featurebyte/core/accessor/feature_string.py
  featurebyte/core/accessor/string.py
Labels: Skip Changelog, Documentation Changes Confirmed

#1279 Use absolute urls for images in README
  README.md
Labels: documentation, Skip Changelog

#1280 [DEV-1686] Use embedded styles for code html formatting
  featurebyte/common/utils.py
  tests/unit/common/test_utils.py
Labels: bug, Skip Changelog

#1282 [DEV-1686] Remove background color for code string html
  featurebyte/common/utils.py
  tests/unit/common/test_utils.py
Labels: bug, Skip Changelog

#1285 fix: featurebyte dependencies fix
  poetry.lock
  pyproject.toml
Labels: bug, dependencies

#1283 [chore] docs: add more examples to docstrings
  featurebyte/api/base_table.py
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/api/source_table.py
Labels: Documentation Changes Confirmed

#1287 [PORT] removed unneeded dependencies in client #e6897c08
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: Documentation Changes Confirmed, port/backport

#1292 [chore] docs: add test to catch methods without examples
  featurebyte/common/documentation/extract_csv.py
  tests/unit/common/documentation/test_extract_csv.py
Labels: Skip Changelog

#1294 Drop a materialized table only if it exists when cleaning up on error
  CHANGELOG.md
  featurebyte/session/base.py
  featurebyte/worker/task/mixin.py
  tests/unit/api/test_source_table.py
Labels: bug

#1296 documentation: update example for consistency with the doc
  README.md
Labels: documentation, Skip Changelog

#1298 [DEV-1695] Add Google Cloud Storage support for spark
  .github/workflows/test.yml
  CHANGELOG.md
  featurebyte/__init__.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/enum.py
  featurebyte/models/credential.py
  featurebyte/session/base_spark.py
  featurebyte/session/simple_storage.py
  poetry.lock
  pyproject.toml
  tests/unit/session/test_simple_storage.py
  tests/unit/session/test_spark.py
Labels: enhancement, dependencies, Documentation Changes Confirmed

#1295 [DEV-1683] Add special handling to query graph nodes with side effect
  CHANGELOG.md
  featurebyte/query_graph/node/base.py
  featurebyte/query_graph/node/count_dict.py
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/node/input.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  featurebyte/query_graph/node/nested.py
  featurebyte/query_graph/node/request.py
  featurebyte/query_graph/transform/sdk_code.py
  tests/fixtures/sdk_code/complex_multi_table_feature.py
  tests/fixtures/sdk_code/event_view_with_tz_offset_column.py
  tests/fixtures/sdk_code/event_view_with_tz_offset_column_manual.py
  tests/fixtures/sdk_code/event_view_with_tz_offset_constant.py
  tests/fixtures/sdk_code/event_view_with_tz_offset_constant_manual.py
  tests/fixtures/sdk_code/feature_fraction.py
  tests/fixtures/sdk_code/feature_operating_system_filter_assign.py
  tests/fixtures/sdk_code/feature_operating_system_series_assign.py
  tests/fixtures/sdk_code/feature_with_cleaned_tz_offset_column.py
  tests/unit/api/test_sdk_code.py
  tests/unit/query_graph/test_metadata_sdk_code.py
  tests/unit/query_graph/test_sdk_code_generation.py
Labels: bug

#1301 [DEV-1271] Update SDK code to pass `on` parameter to explicitly
  CHANGELOG.md
  featurebyte/api/view.py
  featurebyte/query_graph/node/generic.py
  tests/fixtures/sdk_code/event_view_with_tz_offset_column.py
  tests/unit/api/test_scd_view.py
  tests/unit/api/test_view.py
  tests/unit/query_graph/test_graph_pruning.py
Labels: enhancement

#1303 [DEV-1710] Update SDK code generation by removing unused variables
  CHANGELOG.md
  featurebyte/query_graph/node/metadata/sdk_code.py
  tests/fixtures/sdk_code/feature_operating_system_filter_assign.py
  tests/unit/query_graph/test_metadata_sdk_code.py
  tests/unit/query_graph/test_sdk_code_generation.py
Labels: enhancement

#1304 [chore] docs: add and remove a couple methods into docs
  featurebyte/__init__.py
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/common/documentation/gen_ref_pages_docs_builder.py
  featurebyte/common/documentation/resource_extractor.py
  featurebyte/feature_utility.py
Labels: Documentation Changes Confirmed

#1305 [chore] docs: update example for column_cleaning_operations
  featurebyte/api/base_table.py
Labels: Documentation Changes Confirmed

#1309 [chore] Fix snowflake logging level
  featurebyte/session/snowflake.py
Labels: Skip Changelog

#1310 [DEV-980] Adding different start commands for worker | updated pymdowm-extensions to 10.0
  CHANGELOG.md
  docker/entrypoint.sh
  poetry.lock
Labels: bug, enhancement, dependencies

#1308 [DEV-1423] relationship: ensure get_by_id works for None updated_by
  CHANGELOG.md
  featurebyte/api/relationship.py
  tests/unit/api/test_relationship.py
Labels: Documentation Changes Confirmed

#1312 chore: base python set 3.8.12 | upgrade to ubuntu-latest
  .github/workflows/daily-cron.yml
  .github/workflows/dependencies.yml
  .github/workflows/documentation.yml
  .github/workflows/lint.yml
  .github/workflows/publish-dev.yml
  .github/workflows/publish-public.yml
  .github/workflows/test.yml
Labels: github_actions, Skip Changelog

#1314 [DEV-1285] Update feature/feature_list version format from `dict` to `str`
  CHANGELOG.md
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/models/feature.py
  featurebyte/models/feature_list.py
  tests/integration/session/test_simple_storage.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_feature_list.py
  tests/unit/api/test_version.py
Labels: enhancement, Documentation Changes Confirmed

#1307 [DEV-1712] Implement HTML representation for API Object information result
  CHANGELOG.md
  featurebyte/api/api_object.py
  featurebyte/api/api_object_util.py
  featurebyte/api/base_table.py
  featurebyte/api/catalog.py
  featurebyte/api/credential.py
  featurebyte/api/deployment.py
  featurebyte/api/entity.py
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/api/feature_store.py
  featurebyte/api/periodic_task.py
  featurebyte/api/savable_api_object.py
  featurebyte/common/formatting_util.py
  featurebyte/common/utils.py
  tests/fixtures/feature_info.html
  tests/fixtures/feature_list_info.html
  tests/unit/api/test_catalog.py
  tests/unit/api/test_entity.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_item_table.py
  tests/unit/common/test_formatting_util.py
  tests/unit/common/test_utils.py
Labels: enhancement

#1315 [DEV-1387] Add `column_cleaning_operations` to view object
  CHANGELOG.md
  featurebyte/api/view.py
  featurebyte/common/documentation/documentation_layout.py
  tests/unit/api/base_view_test.py
Labels: enhancement, Documentation Changes Confirmed

#1316 [DEV-1408] Add `is_default` column to feature's & feature list's `list_versions` object methods
  CHANGELOG.md
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_feature_list.py
Labels: enhancement

#1317 [DEV-1712] Ensure html repr for unsaved objects is not empty
  featurebyte/api/api_object.py
  tests/unit/api/test_feature.py
Labels: bug, Skip Changelog

#1306 expose catalog_id for entity and relationship
  CHANGELOG.md
  featurebyte/api/entity.py
  featurebyte/api/relationship.py
  featurebyte/common/documentation/documentation_layout.py
  tests/unit/api/test_entity.py
  tests/unit/api/test_relationship.py
Labels: Documentation Changes Confirmed

#1321 [chore] docs: add more examples for save(), info() and get_feature_jobs_status()
  featurebyte/api/entity.py
  featurebyte/api/feature.py
  featurebyte/api/feature_job.py
  featurebyte/api/feature_list.py
  tests/unit/common/documentation/test_extract_csv.py
Labels: Documentation Changes Confirmed

#1320 [DEV-1725] Exclude tables with names that has a "__" prefix in source table listing
  CHANGELOG.md
  featurebyte/api/data_source.py
  featurebyte/service/feature_store_warehouse.py
  tests/unit/routes/test_feature_store.py
Labels: Documentation Changes Confirmed

#1322 [DEV-1273] Add `primary_entity` to feature list `list()` method
  CHANGELOG.md
  featurebyte/api/catalog.py
  featurebyte/api/feature_list.py
  featurebyte/routes/feature_list_namespace/api.py
  featurebyte/routes/feature_list_namespace/controller.py
  featurebyte/routes/feature_namespace/controller.py
  featurebyte/routes/registry.py
  featurebyte/schema/feature_list_namespace.py
  tests/unit/api/test_feature_list.py
  tests/unit/routes/test_feature_list_namespace.py
Labels: Documentation Changes Confirmed

#1323 [DEV-1703] Add `cleaning_operations` property to `TableColumn` & `ViewColumn` objects
  CHANGELOG.md
  featurebyte/api/base_table.py
  featurebyte/api/view.py
  featurebyte/common/documentation/documentation_layout.py
  tests/unit/api/base_table_test.py
  tests/unit/api/base_view_test.py
Labels: enhancement, Documentation Changes Confirmed

#1325 [DEV-1728] expose warehouse statstics of feature job analysis
  featurebyte/schema/feature_job_setting_analysis.py
  tests/unit/routes/test_feature_job_setting_analysis.py
Labels: enhancement, Skip Changelog

#1327 [chore] changed changelog workflow | fixed starlette dependency
  .changelog/DEV-1271.yaml
  .changelog/DEV-1285.yaml
  .changelog/DEV-1387.yaml
  .changelog/DEV-1408.yaml
  .changelog/DEV-1423.yaml
  .changelog/DEV-1490.yaml
  .changelog/DEV-1683.yaml
  .changelog/DEV-1692.yaml
  .changelog/DEV-1699-1.yaml
  .changelog/DEV-1699.yaml
  .changelog/DEV-1703.yaml
  .changelog/DEV-1707.yaml
  .changelog/DEV-1710.yaml
  .changelog/DEV-1712.yaml
  .changelog/DEV-1723.yaml
  .changelog/DEV-1725.yaml
  .changelog/DEV-1726.yaml
  .changelog/DEV-980-2.yaml
  .changelog/DEV-980.yaml
  .changelog/TEMPLATE.yaml
  .changelog/changelog-gen.py
  .changelog/chester-starlette-vuln.yaml
  .changelog/jevon-catalog_id.yaml
  .github/workflows/changelog.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Taskfile.yaml
  poetry.lock
Labels: enhancement, dependencies, github_actions, Skip Changelog

#1326 [DEV-1431] Add `default_feature_list_id` to `feature_list.info()` output
  .changelog/DEV-1431.yaml
  .github/workflows/changelog.yml
  Taskfile.yaml
  featurebyte/api/feature_list.py
  featurebyte/schema/info.py
  tests/unit/api/test_feature_list.py
  tests/unit/service/test_info.py
Labels: Documentation Changes Confirmed

#1328 [DEV-1702] Remove unnecessary info in `feature_list.list_versions()`
  .changelog/DEV-1702.yaml
  featurebyte/api/feature_list.py
  tests/unit/api/test_feature_list.py
Labels: Documentation Changes Confirmed

#1330 [DEV-1734] Remove `entity_ids` from feature creation payload
  .changelog/DEV-1734.yaml
  featurebyte/api/feature.py
  featurebyte/models/feature.py
  featurebyte/query_graph/graph.py
  featurebyte/query_graph/model/graph.py
  featurebyte/schema/feature.py
  tests/fixtures/request_payloads/feature_iet.json
  tests/fixtures/request_payloads/feature_item_event.json
  tests/fixtures/request_payloads/feature_non_time_based.json
  tests/fixtures/request_payloads/feature_sum_2h.json
  tests/fixtures/request_payloads/feature_sum_30m.json
  tests/unit/routes/test_feature.py
Labels: refactoring, Documentation Changes Confirmed

#1331 [DEV-1736] Refactor `Feature` class to remove redundant inheritance
  .changelog/DEV-1736.yaml
  featurebyte/api/event_view.py
  featurebyte/api/feature.py
  featurebyte/query_graph/graph.py
  tests/unit/api/conftest.py
  tests/unit/api/test_event_view.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_request_column.py
  tests/unit/conftest.py
  tests/unit/query_graph/test_query_graph.py
Labels: enhancement

#1336 [DEV-1737] Refactor `Feature` class to drop `FrozenFeatureModel` inheritance
  .changelog/DEV-1737.yaml
  featurebyte/api/feature.py
  featurebyte/api/feature_group.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/models/feature.py
  featurebyte/schema/credential.py
  tests/unit/api/test_api_object.py
  tests/unit/api/test_feature.py
Labels: Documentation Changes Confirmed

#1333 [DEV-1721] Enforce time limits for periodic tasks scheduled based on intervals
  .changelog/DEV-1721.yaml
  featurebyte/service/task_manager.py
  featurebyte/worker/task_executor.py
  tests/unit/service/test_task_manager.py
  tests/unit/worker/test_task_executor.py
Labels: enhancement

#1334 [chore] Simplify handling of internal names in tile procedures
  featurebyte/sql/tile_common.py
  featurebyte/sql/tile_generate.py
  featurebyte/sql/tile_generate_entity_tracking.py
  featurebyte/sql/tile_generate_schedule.py
  featurebyte/sql/tile_monitor.py
  featurebyte/tile/manager.py
  tests/integration/tile/test_generate_tile.py
  tests/integration/tile/test_monitor_tile.py
  tests/integration/tile/test_schedule_generate_tile.py
Labels: refactoring, Skip Changelog

#1338 [DEV-1745] Refactor `FeatureList` class to drop `FrozenFeatureListModel` inheritance
  .changelog/DEV-1745.yaml
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/models/feature_list.py
  tests/unit/api/test_api_object.py
  tests/unit/api/test_feature_list.py
  tests/unit/migration/conftest.py
  tests/unit/migration/test_run.py
Labels: refactoring, Documentation Changes Confirmed

#1341 [DEV-1744] Remove `dtype` from feature creation payload
  .changelog/DEV-1744.yaml
  featurebyte/models/feature.py
  featurebyte/schema/feature.py
  tests/fixtures/request_payloads/feature_iet.json
  tests/fixtures/request_payloads/feature_item_event.json
  tests/fixtures/request_payloads/feature_non_time_based.json
  tests/fixtures/request_payloads/feature_sum_2h.json
  tests/fixtures/request_payloads/feature_sum_30m.json
  tests/unit/api/test_feature.py
  tests/unit/routes/test_feature.py
Labels: enhancement

#1361 [DEV-1753] Update `get_persistent()` by removing global persistent object
  .changelog/DEV-1753.yaml
  featurebyte/persistent/mongo.py
  featurebyte/utils/persistent.py
  tests/unit/persistent/test_mongo.py
Labels: bug

#1354 [DEV-1749] Disable redirection in HTTP client
  .changelog/DEV-1749.yaml
  featurebyte/config.py
  tests/unit/test_config.py
Labels: bug

#1370 [DEV-1758] Remove `feature_namespace_id` and `feature_list_namespace_id` from POST payload
  .changelog/DEV-1758.yaml
  featurebyte/routes/feature/controller.py
  featurebyte/routes/feature_list/controller.py
  featurebyte/schema/feature.py
  featurebyte/schema/feature_list.py
  featurebyte/service/feature.py
  featurebyte/service/feature_list.py
  featurebyte/service/version.py
  tests/fixtures/request_payloads/feature_list_namespace.json
  tests/fixtures/request_payloads/feature_namespace.json
  tests/unit/conftest.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_list.py
  tests/unit/routes/test_feature_list_namespace.py
  tests/unit/routes/test_feature_namespace.py
  tests/unit/service/conftest.py
  tests/unit/service/test_feature.py
  tests/unit/service/test_feature_list.py
  tests/unit/service/test_feature_list_namespace.py
  tests/unit/service/test_feature_namespace.py
  tests/unit/service/test_version.py
  tests/unit/test_generate_payload_fixtures.py
Labels: enhancement

#1365 [DEV-1538] Add batch feature creation routes
  .changelog/DEV-1538.yaml
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/api/savable_api_object.py
  featurebyte/enum.py
  featurebyte/query_graph/transform/sdk_code.py
  featurebyte/routes/feature/api.py
  featurebyte/routes/feature/controller.py
  featurebyte/routes/registry.py
  featurebyte/schema/feature.py
  featurebyte/schema/worker/task/batch_feature_create.py
  featurebyte/service/feature.py
  featurebyte/worker/task/batch_feature_create.py
  featurebyte/worker/task_executor.py
  tests/fixtures/request_payloads/feature_iet.json
  tests/fixtures/request_payloads/feature_item_event.json
  tests/fixtures/request_payloads/feature_list_multi.json
  tests/fixtures/request_payloads/feature_list_single.json
  tests/fixtures/request_payloads/feature_sum_2h.json
  tests/fixtures/request_payloads/feature_sum_30m.json
  tests/integration/api/test_online_enable.py
  tests/unit/api/test_feature.py
  tests/unit/models/test_batch_feature_create.py
  tests/unit/routes/base.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_job_setting_analysis.py
  tests/unit/service/conftest.py
  tests/unit/service/test_feature.py
  tests/unit/worker/task/test_batch_feature_create.py
Labels: enhancement

#1369 [chore] snowflake-connector-python 3.0.4 not distributing macos .whl file
  poetry.lock
  pyproject.toml
Labels: dependencies

#1366 [chore] fixed publish workflow
  .github/workflows/publish-dev.yaml
  .github/workflows/publish-dev_gen.yaml
Labels: github_actions, Documentation Changes Confirmed

#1368 [DEV-1454] More informative message for dataSource.list_tables() and list_schemas()
  .changelog/DEV-1454.yaml
  featurebyte/exception.py
  featurebyte/middleware.py
  featurebyte/routes/common/base.py
  featurebyte/service/feature_store_warehouse.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_feature_store.py
  tests/unit/api/test_observation_table.py
  tests/unit/conftest.py
  tests/unit/routes/test_feature_store.py
  tests/unit/session/test_snowflake_session.py
Labels: enhancement

#1374 [DEV-1766] Fix multiple deployment sharing the same feature list bug
  .changelog/DEV-1766.yaml
  featurebyte/exception.py
  featurebyte/service/deploy.py
  tests/unit/routes/base.py
  tests/unit/routes/test_batch_feature_table.py
  tests/unit/routes/test_deployment.py
  tests/unit/service/conftest.py
  tests/unit/service/test_deploy.py
  tests/unit/service/test_feature_list_status.py
Labels: bug

#1377 [Release] updated featurebyte version to 0.3.0
  .changelog/DEV-1271.yaml
  .changelog/DEV-1285.yaml
  .changelog/DEV-1387.yaml
  .changelog/DEV-1408.yaml
  .changelog/DEV-1423.yaml
  .changelog/DEV-1431.yaml
  .changelog/DEV-1439.yaml
  .changelog/DEV-1454.yaml
  .changelog/DEV-1490.yaml
  .changelog/DEV-1538.yaml
  .changelog/DEV-1683.yaml
  .changelog/DEV-1692.yaml
  .changelog/DEV-1698.yaml
  .changelog/DEV-1699-1.yaml
  .changelog/DEV-1699.yaml
  .changelog/DEV-1702.yaml
  .changelog/DEV-1703.yaml
  .changelog/DEV-1707.yaml
  .changelog/DEV-1710.yaml
  .changelog/DEV-1712.yaml
  .changelog/DEV-1718.yaml
  .changelog/DEV-1721.yaml
  .changelog/DEV-1723.yaml
  .changelog/DEV-1725.yaml
  .changelog/DEV-1726.yaml
  .changelog/DEV-1729.yaml
  .changelog/DEV-1734.yaml
  .changelog/DEV-1736.yaml
  .changelog/DEV-1737.yaml
  .changelog/DEV-1740.yaml
  .changelog/DEV-1744.yaml
  .changelog/DEV-1745.yaml
  .changelog/DEV-1746.yaml
  .changelog/DEV-1749.yaml
  .changelog/DEV-1750.yaml
  .changelog/DEV-1753.yaml
  .changelog/DEV-1758.yaml
  .changelog/DEV-1766.yaml
  .changelog/DEV-980-2.yaml
  .changelog/DEV-980.yaml
  .changelog/chester-starlette-vuln.yaml
  .changelog/deprecate-middleware.yaml
  .changelog/jevon-catalog_id.yaml
  .changelog/jevon-create-debug-folder-for-docs.yaml
  .changelog/jevon-workflow-updates-part1.yaml
  .changelog/jevon-workflow-updates-part2.yaml
  .changelog/requests-vuln.yaml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: Skip Changelog
