Repository featurebyte/featurebyte, pull requests merged in 2023-06, with the labels that each got.

#1380 [DEV-1677] Update creditcard dataset (Cherry-pick)
  featurebyte/datasets/creditcard.sql
  featurebyte/datasets/grocery.sql
Labels: Skip Changelog

#1379 [DEV-1677] Update creditcard dataset (Cherry-pick)
  featurebyte/datasets/creditcard.sql
  featurebyte/datasets/grocery.sql
Labels: Skip Changelog

#1383 enchancement: update feature list to preserve feature order
  .changelog/DEV-1763.yaml
  featurebyte/api/feature_list.py
  featurebyte/models/feature_list.py
  featurebyte/service/feature_list.py
  tests/unit/api/test_feature_list.py
  tests/unit/models/test_feature_list.py
  tests/unit/routes/test_feature_list.py
Labels: enhancement

#1386 [DEV-1760] Update get_relative_frequency to return 0 when there is no matching label
  .changelog/DEV-1760.yaml
  featurebyte/core/accessor/count_dict.py
  featurebyte/session/snowflake.py
  featurebyte/sql/snowflake/F_GET_RELATIVE_FREQUENCY.sql
  hive-udf/lib/src/main/java/com/featurebyte/hive/udf/CountDictRelativeFrequency.java
  tests/integration/udf/test_get_relative_frequency.py
Labels: bug, Documentation Changes Confirmed

#1389 [DEV-1777] Refactor task manager to take celery object as input
  .changelog/DEV-1777.yaml
  docker/migration.py
  featurebyte/app.py
  featurebyte/migration/run.py
  featurebyte/migration/service/data_warehouse.py
  featurebyte/migration/service/mixin.py
  featurebyte/routes/app_container.py
  featurebyte/routes/registry.py
  featurebyte/routes/task/controller.py
  featurebyte/schema/worker/task/test.py
  featurebyte/service/online_enable.py
  featurebyte/service/task_manager.py
  featurebyte/service/working_schema.py
  featurebyte/worker/__init__.py
  featurebyte/worker/process_store.py
  featurebyte/worker/start.py
  featurebyte/worker/task/base.py
  featurebyte/worker/task_executor.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/integration/api/test_online_enable.py
  tests/integration/conftest.py
  tests/integration/feature_manager/test_feature_manager.py
  tests/integration/service/test_working_schema_service.py
  tests/integration/tile/conftest.py
  tests/integration/tile/test_tile_scheduler.py
  tests/integration/worker/conftest.py
  tests/integration/worker/test_task_manager.py
  tests/unit/api/test_event_table.py
  tests/unit/conftest.py
  tests/unit/migration/test_run.py
  tests/unit/routes/test_app_container.py
  tests/unit/routes/test_task.py
  tests/unit/service/test_task_manager.py
  tests/unit/worker/task/base.py
  tests/unit/worker/test_task_executor.py
Labels: enhancement, dependencies

#1392 [DEV-1780] Ignore vuln for cryptography and redis
  Taskfile.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies, Skip Changelog

#1393 [DEV-1777] Refactor task executor to import tasks explicitly
  .changelog/DEV-1777.yaml
  docker/entrypoint.sh
  featurebyte/worker/start.py
  featurebyte/worker/task_executor.py
Labels: enhancement

#1390 enhancement: update `Feature.save` to use async POST route
  .changelog/DEV-1538.yaml
  featurebyte/api/api_object.py
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/api/savable_api_object.py
  featurebyte/worker/task/batch_feature_create.py
  tests/fixtures/sdk_code/complex_multi_table_feature.py
  tests/fixtures/sdk_code/feature_item_cosine_similarity.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/query_graph/test_online_serving.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_feature_list.py
  tests/unit/worker/task/test_batch_feature_create.py
Labels: Documentation Changes Confirmed

#1399 [DEV-1793] Make websocket client more resilient against connection drop
  .changelog/DEV-1793.yaml
  featurebyte/config.py
  featurebyte/service/deploy.py
  tests/unit/test_config.py
Labels: bug

#1401 enhancement: limit manual default version selection to the versions with the highest readiness level only
  .changelog/DEV-1795.yaml
  featurebyte/api/feature_list.py
  featurebyte/routes/feature_namespace/controller.py
  featurebyte/service/validator/production_ready_validator.py
  featurebyte/worker/task/batch_feature_create.py
  tests/unit/api/test_feature.py
  tests/unit/routes/base.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_namespace.py
  tests/unit/service/validator/test_production_ready_validator.py
Labels: Documentation Changes Confirmed

#1403 [DEV-1796] Fix duplicate entries in metadata schema for Spark and Databricks
  .changelog/DEV-1796.yaml
  featurebyte/session/base.py
  featurebyte/session/base_spark.py
Labels: bug

#1404 enhancement: optimize time to deserialize feature model
  .changelog/DEV-1797.yaml
  featurebyte/models/feature.py
  tests/unit/api/test_feature.py
Labels: enhancement

#1407 [Release] Changelog 0.3.1
  .changelog/DEV-1774.yaml
  .changelog/DEV-1793.yaml
  CHANGELOG.md
Labels: Skip Changelog, port/backport

#1406 bugfix: `feature_list_ids` of feature model not update properly after associated feature list is deleted
  .changelog/DEV-1799.yaml
  featurebyte/routes/feature_list/controller.py
  featurebyte/service/feature_list.py
  featurebyte/service/mixin.py
  tests/unit/api/test_feature_list.py
  tests/unit/service/test_feature_list.py
Labels: bug

#1414 [DEV-1467] Update schema recreation process to be aware of materialized tables
  featurebyte/enum.py
  featurebyte/migration/service/mixin.py
  featurebyte/service/batch_feature_table.py
  featurebyte/service/batch_request_table.py
  featurebyte/service/historical_feature_table.py
  featurebyte/service/observation_table.py
  featurebyte/session/base.py
  featurebyte/session/snowflake.py
  tests/integration/service/test_working_schema_service.py
Labels: bug

#1378 [DEV-1705] Kerberos auth and webhdfs support for spark session
  .changelog/DEV-1705.yaml
  docker/Dockerfile
  docker/entrypoint.sh
  featurebyte/__init__.py
  featurebyte/__main__.py
  featurebyte/docker/featurebyte.yml
  featurebyte/docker/manager.py
  featurebyte/enum.py
  featurebyte/models/credential.py
  featurebyte/routes/feature_store/controller.py
  featurebyte/session/base_spark.py
  featurebyte/session/simple_storage.py
  featurebyte/session/spark.py
  featurebyte/session/webhdfs.py
  poetry.lock
  pyproject.toml
  tests/fixtures/hive.service.keytab
  tests/integration/session/test_simple_storage.py
  tests/unit/models/test_credential.py
Labels: enhancement, dependencies, Documentation Changes Confirmed

#1437 [ISSUES-1436] Update workflows with new packages for kerberos support
  .changelog/ISSUES-1436.yaml
  .github/workflows/daily-cron_gen.yaml
  .github/workflows/documentation_gen.yaml
  .github/workflows/lint_gen.yaml
  .github/workflows/publish-dev_gen.yaml
  .github/workflows/publish-public_gen.yaml
  .github/workflows/test_gen.yaml
Labels: bug, github_actions

#1442 enhancement: update feature's & feature list's `list_versions` method
  .changelog/DEV-1802.yaml
  featurebyte/api/feature.py
  featurebyte/api/feature_list.py
  featurebyte/routes/feature/controller.py
  featurebyte/routes/feature_list/api.py
  featurebyte/routes/feature_list/controller.py
  featurebyte/schema/feature.py
  featurebyte/schema/feature_list.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_feature_list.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_list.py
Labels: Documentation Changes Confirmed

#1439 enhancement: add feature list with batch feature creation async route
  .changelog/DEV-1804.yaml
  featurebyte/api/api_object.py
  featurebyte/api/api_object_util.py
  featurebyte/api/feature.py
  featurebyte/api/feature_group.py
  featurebyte/api/feature_list.py
  featurebyte/api/savable_api_object.py
  featurebyte/enum.py
  featurebyte/routes/feature/controller.py
  featurebyte/routes/feature_list/api.py
  featurebyte/routes/feature_list/controller.py
  featurebyte/routes/registry.py
  featurebyte/schema/feature.py
  featurebyte/schema/feature_list.py
  featurebyte/schema/worker/task/batch_feature_create.py
  featurebyte/schema/worker/task/feature_list_batch_feature_create.py
  featurebyte/worker/task/batch_feature_create.py
  featurebyte/worker/task/feature_list_batch_feature_create.py
  tests/integration/api/test_feature_list_batch_feature_create.py
  tests/unit/api/test_feature_list.py
  tests/unit/common/test_utils.py
  tests/unit/models/test_batch_feature_create.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_list.py
Labels: Documentation Changes Confirmed

#1444 [DEV-1833] - Migrate Tutorial Notebooks
  .changelog/DEV-1833.yaml
  Taskfile.yaml
  featurebyte/__init__.py
  featurebyte/common/env_util.py
  notebooks/deep dive data modeling - final.ipynb
  notebooks/deep dive feature engineering - final.ipynb
  notebooks/deep dive materializing features - final.ipynb
  notebooks/model.pkl
  notebooks/playground credit cards.ipynb
  notebooks/playground healthcare.ipynb
  notebooks/prebuilt_catalogs.py
  notebooks/quick start end-to-end workflow - final.ipynb
  notebooks/quick start feature engineering - final.ipynb
  notebooks/quick start feature management - final.ipynb
  notebooks/quick start model training - final.ipynb
  notebooks/quick start reusing features - final.ipynb
  notebooks/training_data.csv
  notebooks/training_data.parquet
  poetry.lock
  pyproject.toml
  tests/notebooks/conftest.py
  tests/notebooks/test_notebooks.py
Labels: enhancement, dependencies

#1451 [DEV-1764] Add s3 support for service storage
  .changelog/DEV-1764.yaml
  Taskfile.yaml
  featurebyte/storage/__init__.py
  featurebyte/storage/s3.py
  featurebyte/utils/storage.py
  poetry.lock
  pyproject.toml
  tests/integration/storage/__init__.py
  tests/integration/storage/base.py
  tests/integration/storage/test_local_storage.py
  tests/integration/storage/test_local_temp_storage.py
  tests/integration/storage/test_s3_storage.py
Labels: enhancement, dependencies

#1435 [DEV-1810] Remove implicit profile selection
  .changelog/DEV-1810.yaml
  featurebyte/__init__.py
  featurebyte/config.py
  featurebyte/worker/task_executor.py
  tests/fixtures/config/config.yaml
  tests/integration/backward_compatibility/test_get_route.py
  tests/integration/conftest.py
  tests/integration/worker/conftest.py
  tests/unit/conftest_config.py
  tests/unit/test_config.py
Labels: enhancement, breaking

#1459 [DEV-1842] Fix feature definition generation for isin() operation
  .changelog/DEV-1842.yaml
  featurebyte/query_graph/node/binary.py
  tests/fixtures/sdk_code/isin_column.py
  tests/fixtures/sdk_code/isin_feature.py
  tests/unit/api/test_sdk_code.py
Labels: bug
