Repository featurebyte/featurebyte, pull requests merged in 2023-12, with the labels that each got.

#1956 [RELEASE] 0.6.2 featurebyte
  .changelog/DEV-2128.yaml
  .changelog/DEV-2349.yaml
  .changelog/DEV-2430.yaml
  .changelog/DEV-2431.yaml
  .changelog/DEV-2435_1.yaml
  .changelog/DEV-2435_2.yaml
  .changelog/DEV-2449.yaml
  .changelog/DEV-2453.yaml
  .changelog/DEV-2463.yaml
  .changelog/DEV-2467.yaml
  .changelog/DEV-2473.yaml
  .changelog/DEV-2474.yaml
  .changelog/DEV-2482.yaml
  .changelog/DEV-2483.yaml
  .changelog/DEV-2485.yaml
  .changelog/DEV-2487.yaml
  .changelog/DEV-2490.yaml
  .changelog/DEV-2491.yaml
  .changelog/DEV-2496.yaml
  .changelog/DEV-2503.yaml
  .changelog/DEV-2516.yaml
  .changelog/DEV-2518.yaml
  .changelog/DEV-2525.yaml
  .changelog/DEV-2526.yaml
  .changelog/DEV-2527.yaml
  .changelog/DEV-2568.yaml
  .changelog/DEV-2569.yaml
  .changelog/DEV-2571.yaml
  .changelog/DEV-2591.yaml
  .changelog/DEV-2611.yaml
  .changelog/DEV-2623.yaml
  .changelog/DEV-2626.yaml
  .changelog/DEV-2643.yaml
  .changelog/DEV-2656.yaml
  .changelog/DEV-2659.yaml
  .changelog/DEV-2669.yaml
  .changelog/DEV-2679.yaml
  .changelog/DEV-2694.yaml
  .changelog/DEV-2702.yaml
  .changelog/DEV-2714.yaml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: Skip Changelog, Documentation Changes Confirmed

#1962 [DEV-2717] Add OfflineStoreFeatureTableModel and update services
  featurebyte/models/offline_store_feature_table.py
  featurebyte/routes/registry.py
  featurebyte/service/feature_materialize.py
  featurebyte/service/offline_store_feature_table.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/fixtures/offline_store_feature_table/feature_cluster_disabled_one_feature.json
  tests/fixtures/offline_store_feature_table/feature_cluster_one_feature.json
  tests/fixtures/offline_store_feature_table/feature_cluster_two_features.json
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/conftest.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_offline_store_feature_table_manager.py
  tests/util/helper.py
Labels: Skip Changelog

#1963 [DEV-2734] Add fb.UserDefinedFunction.get to docs
  featurebyte/api/user_defined_function.py
  featurebyte/common/documentation/documentation_layout.py
Labels: Documentation Changes Confirmed

#1970 [DEV-2764] Update FeatureMaterializeService to handle initialization and scheduled updates
  featurebyte/models/feature_list.py
  featurebyte/models/offline_store_feature_table.py
  featurebyte/query_graph/model/graph.py
  featurebyte/service/feature_materialize.py
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_new_table.sql
  tests/fixtures/feature_materialize/materialize_features_queries.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_queries.sql
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/service/test_feature_materialize.py
Labels: Skip Changelog

#1972 [DEV-2770] Trigger feature columns initialization in OfflineStoreFeatureTableManagerService
  featurebyte/service/feature_materialize.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#1973 [DEV-2715] Schedule periodic task to materialise features to offline store feature tables
  featurebyte/enum.py
  featurebyte/routes/registry.py
  featurebyte/schema/worker/task/online_store_cleanup.py
  featurebyte/schema/worker/task/scheduled_feature_materialize.py
  featurebyte/service/feature_materialize_scheduler.py
  featurebyte/service/offline_store_feature_table_manager.py
  featurebyte/worker/registry.py
  featurebyte/worker/task/online_store_cleanup.py
  featurebyte/worker/task/scheduled_feature_materialize.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/service/test_feature_materialize_scheduler.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#1975 [DEV-2772] Create or update feast registry in offline store feature table manager
  featurebyte/feast/model/registry.py
  featurebyte/feast/service/registry.py
  featurebyte/service/feature_list.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/integration/api/test_scd_view_operations.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#1982 [DEPS] feast dependency needs to be mandatory as used in enums.py
  poetry.lock
  pyproject.toml
Labels: dependencies, Skip Changelog, Documentation Changes Confirmed

#1983 [chore] Fix feast dependency extras
  poetry.lock
  pyproject.toml
Labels: dependencies

#1989 [chore] Make feast an optional dependency in server extras
  poetry.lock
  pyproject.toml
Labels: dependencies

#1988 [chore] Refactor OfflineStoreFeatureTableManagerService to handle multiple features at once
  featurebyte/service/offline_store_feature_table_manager.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#1992 [DEV-2806] Invoke offline store feature table manager on deployment
  featurebyte/models/deployment.py
  featurebyte/service/deploy.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/conftest.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#1995 Update feature service feast integration
  featurebyte/feast/utils/registry_construction.py
  featurebyte/models/feature.py
  featurebyte/models/offline_store_feature_table.py
  featurebyte/service/entity_serving_names.py
  featurebyte/service/feature.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_offline_ingest_query_graph.py
  tests/unit/api/test_request_column.py
  tests/unit/feast/conftest.py
  tests/util/helper.py
Labels: Skip Changelog

#2001 [DEV-2831] Fix periodic tasks not disabled when reverting failed deployment
  .changelog/DEV-2831.yaml
  featurebyte/service/deploy.py
  tests/unit/service/test_deploy.py
Labels: bug

#2002 [DEV-2832] Drop columns in offline store feature table after online disabling features
  featurebyte/service/feature_materialize.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/fixtures/feature_materialize/drop_columns.sql
  tests/unit/service/conftest.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_offline_store_feature_table_manager.py
  tests/unit/service/test_online_serving_feast.py
Labels: Skip Changelog

#2007 [DEV-2843] Update README
  README.md
Labels: Skip Changelog

#2010 [RELEASE] Branch cut to release 1.0.0
  .changelog/DEV-2731.yaml
  .changelog/DEV-2784.yaml
  .changelog/DEV-2831.yaml
  .changelog/DEV-2845.yaml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: dependencies, Skip Changelog, Documentation Changes Confirmed

#2011 [chore] Fix snowflake connector issue
  docker/Dockerfile
  featurebyte/__init__.py
  poetry.lock
  pyproject.toml
  tests/integration/query_graph/test_online_serving.py
  tests/unit/api/test_feature_job_setting_analysis.py
  tests/unit/api/test_static_source_table.py
  tests/unit/worker/task/test_batch_feature_create.py
Labels: dependencies

#2015 [chore] removed oscrypto by bumping snowflake-connector-python
  poetry.lock
  pyproject.toml
  tests/unit/session/test_snowflake_session.py
Labels: dependencies

#2029 [chore] Add mysql extras for feast
  docker/Dockerfile
  poetry.lock
  pyproject.toml
Labels: dependencies

#2022 Implement CRUD routes for online stores
  .changelog/DEV-2886.yaml
  featurebyte/__init__.py
  featurebyte/api/catalog.py
  featurebyte/api/online_store.py
  featurebyte/app.py
  featurebyte/common/documentation/allowed_classes.py
  featurebyte/common/documentation/constants.py
  featurebyte/common/documentation/custom_nav.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/common/documentation/resource_extractor.py
  featurebyte/enum.py
  featurebyte/models/catalog.py
  featurebyte/models/online_store.py
  featurebyte/models/online_store_spec.py
  featurebyte/routes/catalog/api.py
  featurebyte/routes/catalog/controller.py
  featurebyte/routes/common/base.py
  featurebyte/routes/online_store/__init__.py
  featurebyte/routes/online_store/api.py
  featurebyte/routes/online_store/controller.py
  featurebyte/routes/registry.py
  featurebyte/schema/catalog.py
  featurebyte/schema/info.py
  featurebyte/schema/online_store.py
  featurebyte/service/catalog.py
  featurebyte/service/feature_manager.py
  featurebyte/service/online_enable.py
  featurebyte/service/online_store.py
  scripts/test-docs-setup.py
  tests/fixtures/backward_compatibility/get_routes.txt
  tests/fixtures/request_payloads/online_store.json
  tests/integration/feature_manager/test_feature_manager.py
  tests/integration/query_graph/test_online_serving.py
  tests/unit/api/test_catalog.py
  tests/unit/api/test_online_store.py
  tests/unit/conftest.py
  tests/unit/feature_manager/test_unit_snowflake_feature.py
  tests/unit/routes/test_catalog.py
  tests/unit/routes/test_online_store.py
  tests/unit/service/conftest.py
  tests/unit/test_generate_payload_fixtures.py
Labels: Documentation Changes Confirmed
