Repository featurebyte/featurebyte, pull requests merged in 2024-07, with the labels that each got.

#2418 [chore] Revise historical feature table model
  featurebyte/models/historical_feature_table.py
  featurebyte/worker/task/historical_feature_table.py
  tests/integration/api/test_event_view_operations.py
Labels: documentation, Skip Changelog

#2429 [DEV-3571] Implement sql generation for window aggregate without tiles
  featurebyte/enum.py
  featurebyte/query_graph/enum.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/sql/aggregator/non_tile_window.py
  featurebyte/query_graph/sql/aggregator/range_join.py
  featurebyte/query_graph/sql/ast/aggregate.py
  featurebyte/query_graph/sql/feature_compute.py
  featurebyte/query_graph/sql/feature_job.py
  featurebyte/query_graph/sql/specifications/non_tile_window_aggregate.py
  featurebyte/query_graph/sql/specs.py
  featurebyte/query_graph/sql/tile_util.py
  tests/fixtures/aggregator/expected_non_tile_window_aggregator.sql
  tests/fixtures/aggregator/expected_non_tile_window_aggregator_ctes.sql
  tests/fixtures/expected_preview_non_tile_window_aggregate.sql
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/test_feature_preview.py
  tests/unit/query_graph/test_non_tile_window_aggregator.py
Labels: Skip Changelog

#2427 [DEV-3565] adding webdav support
  Taskfile.yaml
  featurebyte/storage/webdav.py
  tests/integration/storage/base.py
  tests/integration/storage/test_webdav_storage.py
Labels: Skip Changelog

#2431 [RELEASE] featurebyte version 1.1.3
  .changelog/DEV-3548.yaml
  .changelog/DEV-3559.yaml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: Skip Changelog

#2430 [DEV-3572] Support count_distinct aggregation method
  .changelog/DEV-3572.yaml
  featurebyte/api/aggregator/asat_aggregator.py
  featurebyte/api/aggregator/base_aggregator.py
  featurebyte/api/aggregator/simple_aggregator.py
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/enum.py
  featurebyte/query_graph/node/agg_func.py
  featurebyte/query_graph/node/metadata/operation.py
  featurebyte/query_graph/sql/groupby_helper.py
  tests/integration/api/test_feature_correctness.py
  tests/unit/api/test_aggregate_over.py
  tests/unit/query_graph/sql/test_groupby_helper.py
Labels: documentation, enhancement

#2435 [chore] Update `typechecked` for enum type
  featurebyte/api/aggregator/simple_aggregator.py
  featurebyte/api/base_table.py
  featurebyte/api/catalog.py
  featurebyte/api/feature.py
  featurebyte/api/feature_job.py
  featurebyte/api/feature_list.py
  featurebyte/api/groupby.py
  featurebyte/api/observation_table.py
  featurebyte/api/relationship.py
  featurebyte/api/user_defined_function.py
  tests/unit/api/test_groupby.py
  tests/unit/api/test_relationship.py
Labels: documentation

#2434 [DEV-3578] Update deployment workflows to handle non-tile window aggregate nodes
  featurebyte/models/entity_universe.py
  featurebyte/query_graph/graph.py
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/query_graph/transform/decompose_point.py
  featurebyte/service/feature_offline_store_info.py
  tests/fixtures/offline_store_feature_table/count_distinct_window_aggregate_universe.sql
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/conftest.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#2437 task/catalog_online_store_update: Fix task logging message
  featurebyte/worker/task/catalog_online_store_update.py
Labels: Skip Changelog

#2438 [chore] Refactor base document service to support soft-delete
  featurebyte/models/base.py
  featurebyte/models/catalog.py
  featurebyte/routes/catalog/controller.py
  featurebyte/schema/catalog.py
  featurebyte/schema/common/base.py
  featurebyte/service/base_document.py
  featurebyte/service/catalog.py
  tests/unit/api/test_credential.py
  tests/unit/api/test_dimension_table.py
  tests/unit/api/test_entity.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_feature_list.py
  tests/unit/api/test_feature_store.py
  tests/unit/api/test_item_table.py
  tests/unit/api/test_online_store.py
  tests/unit/api/test_scd_table.py
  tests/unit/models/test_dimension_table.py
  tests/unit/models/test_entity.py
  tests/unit/models/test_event_table.py
  tests/unit/models/test_feature.py
  tests/unit/models/test_feature_list.py
  tests/unit/models/test_scd_table.py
  tests/unit/routes/test_deployment.py
  tests/unit/routes/test_target.py
  tests/unit/routes/test_target_table.py
  tests/unit/service/test_base_document.py
  tests/unit/service/test_catalog.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: documentation

#2439 [chore] adding explicit numpy version
  poetry.lock
  pyproject.toml
Labels: dependencies

#2441 [RELEASE] Featurebyte 1.1.4
  .changelog/DEV-3572.yaml
  .changelog/DEV-3583.yaml
  CHANGELOG.md
  pyproject.toml
Labels: Skip Changelog

#2443 [DEV-3585] Track aggregation_ids in offline store feature table documents
  featurebyte/models/offline_store_feature_table.py
  featurebyte/service/offline_store_feature_table.py
  featurebyte/service/offline_store_feature_table_construction.py
  tests/unit/service/test_offline_store_feature_table.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#2448 [DEV-3586] Implement services for feature materialize task coordination
  featurebyte/common/date_util.py
  featurebyte/models/feature_materialize_prerequisite.py
  featurebyte/routes/registry.py
  featurebyte/service/feature_materialize_prerequisite.py
  featurebyte/service/feature_materialize_sync.py
  tests/unit/service/test_feature_materialize_prerequisite.py
  tests/unit/service/test_feature_materialize_sync.py
Labels: Skip Changelog

#2451 [chore] Disable feast usage before feast imports
  tests/conftest.py
Labels: Skip Changelog

#2450 [DEV-3586] Minor improvements for FeatureMaterializePrerequisiteService
  featurebyte/service/feature_materialize_prerequisite.py
  featurebyte/service/feature_materialize_sync.py
  tests/unit/service/test_feature_materialize_prerequisite.py
Labels: Skip Changelog

#2452 [chore] Fix extraction of aggregation ids for offline store feature table
  featurebyte/models/offline_store_feature_table.py
  featurebyte/service/offline_store_feature_table_construction.py
  tests/integration/feature_store_integration/test_feature_materialize.py
Labels: Skip Changelog

#2455 [DEV-3589] Update tile task to report completion status
  featurebyte/service/tile/tile_task_executor.py
  tests/unit/service/tile/test_tile_task_executor.py
Labels: Skip Changelog

#2454 [DEV-3587] Add FeatureMaterializeSyncTask
  featurebyte/enum.py
  featurebyte/routes/registry.py
  featurebyte/schema/worker/task/feature_materialize_sync.py
  featurebyte/worker/registry.py
  featurebyte/worker/task/feature_materialize_sync.py
  tests/integration/feature_store_integration/test_feature_materialize.py
Labels: Skip Changelog

#2457 [DEV-3588] Schedule FeatureMaterializeSyncTask on deployment
  featurebyte/service/feature_materialize_scheduler.py
  featurebyte/service/feature_materialize_sync.py
  featurebyte/service/task_manager.py
  featurebyte/service/tile/tile_task_executor.py
  tests/integration/conftest.py
  tests/unit/conftest.py
  tests/unit/service/test_feature_materialize_scheduler.py
  tests/unit/service/test_feature_materialize_sync.py
  tests/unit/service/test_offline_store_feature_table_manager.py
  tests/unit/service/test_task_manager.py
Labels: Skip Changelog

#2456 [chore] Update gcs credential format
  featurebyte/models/credential.py
  featurebyte/utils/messaging.py
  tests/unit/api/test_view.py
  tests/unit/models/test_credential.py
  tests/unit/routes/test_feature_store.py
Labels: documentation

#2461 [DEV-3590] Add FeatureMaterializeRun model to track feature materialize runs
  featurebyte/models/feature_materialize_prerequisite.py
  featurebyte/models/feature_materialize_run.py
  featurebyte/routes/registry.py
  featurebyte/schema/worker/task/scheduled_feature_materialize.py
  featurebyte/service/feature_materialize.py
  featurebyte/service/feature_materialize_run.py
  featurebyte/service/feature_materialize_sync.py
  featurebyte/worker/task/scheduled_feature_materialize.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_feature_materialize_run.py
  tests/unit/service/test_feature_materialize_scheduler.py
  tests/unit/service/test_feature_materialize_sync.py
Labels: Skip Changelog

#2466 [DEV-3607] Add route to retrieve deployment feature job history
  featurebyte/models/feature_materialize_run.py
  featurebyte/routes/deployment/api.py
  featurebyte/routes/deployment/controller.py
  featurebyte/routes/registry.py
  featurebyte/schema/deployment.py
  featurebyte/service/base_document.py
  featurebyte/service/feature_job_history_service.py
  featurebyte/service/feature_list.py
  featurebyte/service/feature_materialize_run.py
  featurebyte/service/feature_materialize_sync.py
  tests/unit/routes/test_deployment.py
  tests/unit/service/fixtures_feature_materialize_runs.py
  tests/unit/service/test_feature_job_history.py
  tests/unit/service/test_feature_materialize_run.py
  tests/unit/service/test_feature_materialize_sync.py
Labels: Skip Changelog

#2467 [DEV-3607] Filter incomplete tile tasks by aggregation id
  featurebyte/models/feature_list.py
  featurebyte/service/feature_job_history_service.py
  tests/unit/api/test_feature_list.py
  tests/unit/models/test_feature_list.py
  tests/unit/service/fixtures_feature_materialize_runs.py
  tests/unit/service/test_feature_job_history.py
Labels: Skip Changelog

#2468 [DEV-3608] Remove default values for mandatory arguments in aggregation methods
  .changelog/DEV-3608.yaml
  featurebyte/api/aggregator/asat_aggregator.py
  featurebyte/api/aggregator/base_aggregator.py
  featurebyte/api/aggregator/base_asat_aggregator.py
  featurebyte/api/aggregator/forward_aggregator.py
  featurebyte/api/aggregator/forward_asat_aggregator.py
  featurebyte/api/aggregator/simple_aggregator.py
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/api/groupby.py
  scripts/test-docs-setup.py
  tests/integration/api/test_change_view_operations.py
  tests/integration/api/test_dimension_view_operations.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_feature_list_batch_feature_create.py
  tests/integration/api/test_features.py
  tests/integration/api/test_forward_aggregate_asat.py
  tests/integration/api/test_item_view_operations.py
  tests/integration/api/test_online_enable.py
  tests/integration/api/test_scd_view_operations.py
  tests/integration/api/test_serving_parent_features.py
  tests/integration/api/test_table_column_critical_data_info.py
  tests/integration/conftest.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/integration/migration/test_data_warehouse_migration.py
  tests/integration/query_graph/test_online_serving.py
  tests/integration/service/test_feature_table_cache.py
  tests/integration/tile/test_tile_cache.py
  tests/unit/api/aggregator/test_forward_aggregator.py
  tests/unit/api/test_aggregate_asat_common.py
  tests/unit/api/test_aggregate_over.py
  tests/unit/api/test_change_view.py
  tests/unit/api/test_databricks.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_groupby.py
  tests/unit/api/test_item_view.py
  tests/unit/api/test_offline_ingest_query_graph.py
  tests/unit/api/test_sdk_code.py
  tests/unit/conftest.py
  tests/unit/core/accessor/test_count_dict.py
  tests/unit/query_graph/sql/test_complex_feature.py
  tests/unit/service/test_feature_manager.py
Labels: documentation

#2469 [chore] Group job runs by feature table in /deployment/job_history
  featurebyte/schema/deployment.py
  featurebyte/service/feature_job_history_service.py
  tests/unit/routes/test_deployment.py
  tests/unit/service/test_feature_job_history.py
Labels: Skip Changelog

#2470 [chore] Update migration framework to be more customisable
  featurebyte/migration/model.py
  featurebyte/migration/run.py
  featurebyte/migration/service/mixin.py
  featurebyte/persistent/base.py
  tests/unit/persistent/test_mongo.py
Labels: Skip Changelog

#2475 [DEV-3627] Reuse sampled data when executing describe queries
  docker/docker-compose.yml
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/fixtures/expected_describe_request.sql
  tests/fixtures/query_graph/expected_describe_batches_0.sql
  tests/fixtures/query_graph/expected_describe_batches_1.sql
  tests/fixtures/query_graph/expected_describe_count_based_stats_only.sql
  tests/fixtures/query_graph/expected_describe_databricks.sql
  tests/fixtures/query_graph/expected_describe_date_range_and_size.sql
  tests/fixtures/query_graph/expected_describe_snowflake.sql
  tests/fixtures/query_graph/expected_describe_spark.sql
  tests/fixtures/query_graph/expected_describe_stats_names.sql
  tests/fixtures/query_graph/expected_value_counts.sql
  tests/fixtures/query_graph/expected_value_counts_no_casting.sql
  tests/unit/query_graph/interpreter/test_preview.py
  tests/unit/routes/test_feature_store.py
  tests/unit/service/test_observation_table.py
Labels: Skip Changelog

#2490 [DEV-3632][cherry-pick] Fix request table name conflict between tile & non-tile window aggregators (#2482)
  featurebyte/query_graph/sql/aggregator/non_tile_window.py
  tests/fixtures/aggregator/expected_non_tile_window_aggregator.sql
  tests/fixtures/aggregator/expected_non_tile_window_aggregator_ctes.sql
  tests/fixtures/expected_preview_non_tile_window_aggregate.sql
  tests/integration/api/test_event_view_operations.py
  tests/integration/conftest.py
Labels: Skip Changelog

#2491 [DEV-3626][cherry-pick] Handle multiple columns in value_counts() (#2483)
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/fixtures/query_graph/expected_value_counts.sql
  tests/fixtures/query_graph/expected_value_counts_a.sql
  tests/fixtures/query_graph/expected_value_counts_b.sql
  tests/fixtures/query_graph/expected_value_counts_sampled_data.sql
  tests/unit/query_graph/interpreter/test_preview.py
  tests/unit/service/test_preview.py
Labels: Skip Changelog

#2492 [DEV-3628] Clip timestamp columns in sample and preview
  featurebyte/query_graph/sql/common.py
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/integration/api/conftest.py
  tests/integration/api/test_view_describe.py
  tests/integration/api/test_view_sample.py
  tests/unit/query_graph/interpreter/test_interpreter.py
  tests/unit/routes/test_feature_store.py
Labels: Skip Changelog

#2493 [DEV-3632] Fix potential duplicated parent names in non-tile aggregate (#2484)
  featurebyte/query_graph/sql/aggregator/non_tile_window.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/conftest.py
Labels: Skip Changelog

#2494 [DEV-3628] Clip timestamp columns in sample and preview
  featurebyte/query_graph/sql/common.py
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/integration/api/conftest.py
  tests/integration/api/test_view_describe.py
  tests/integration/api/test_view_sample.py
  tests/unit/query_graph/interpreter/test_interpreter.py
  tests/unit/routes/test_feature_store.py
Labels: Skip Changelog

#2495 [chore] deprecating sasl to support 3.11
  .changelog/SASL.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies

#2496 [DEV-3641] Update PreviewService to allow long running queries by default
  featurebyte/routes/feature_store/controller.py
  featurebyte/service/preview.py
  tests/unit/routes/test_feature_store.py
  tests/unit/service/test_preview.py
  tests/unit/service/test_specialized_dtype.py
Labels: Skip Changelog

#2498 [DEV-3641] Update PreviewService to allow long running queries by default
  featurebyte/routes/feature_store/controller.py
  featurebyte/service/preview.py
  tests/unit/routes/test_feature_store.py
  tests/unit/service/test_preview.py
  tests/unit/service/test_specialized_dtype.py
Labels: Skip Changelog

#2497 [DEV-3642] Update PreviewService to do value counts without sorting full table
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/fixtures/query_graph/expected_value_counts_sampled_data.sql
  tests/unit/query_graph/interpreter/test_preview.py
Labels: Skip Changelog

#2501 [DEV-3642][cherry-pick] Update PreviewService to do value counts without sorting full table (#2497)
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/fixtures/query_graph/expected_value_counts_sampled_data.sql
  tests/unit/query_graph/interpreter/test_preview.py
Labels: Skip Changelog

#2505 [RELEASE] Releasing 2.0.0
  .changelog/CHORE-ruff.yaml
  .changelog/DEV-3483.yaml
  .changelog/DEV-3594.yaml
  .changelog/DEV-3597.yaml
  .changelog/DEV-3608.yaml
  .changelog/SASL.yaml
  CHANGELOG.md
  pyproject.toml
Labels: Skip Changelog
