Repository featurebyte/featurebyte, pull requests merged in 2024-08, with the labels that each got.

#2508 [DEV-3648] Fix bugs due to pydantic upgrade
  featurebyte/query_graph/node/cleaning_operation.py
  featurebyte/session/manager.py
  tests/unit/models/test_scd_table.py
  tests/unit/session/test_manager.py
Labels: documentation, Skip Changelog

#2511 [DEV-3621] Update table columns info update endpoint to conditionally skip semantic check
  featurebyte/routes/common/base_table.py
  featurebyte/service/table_columns_info.py
  featurebyte/service/table_facade.py
  featurebyte/service/table_info.py
  tests/unit/routes/test_event_table.py
Labels: Skip Changelog

#2481 [chore] Bumping pandas to support 2.0
  .github/workflows/test-notebooks.yaml
  .github/workflows/test.yaml
  poetry.lock
  pyproject.toml
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_feature_correctness.py
  tests/unit/common/test_validator.py
Labels: documentation, dependencies, breaking

#2515 [DEV-3659] Revise week datetime extraction for pandas 2.0
  .github/workflows/test-notebooks.yaml
  .github/workflows/test.yaml
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/sql/parent_serving.py
  poetry.lock
  pyproject.toml
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_feature_correctness.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/common/test_validator.py
  tests/unit/query_graph/on_demand_function/test_date.py
  tests/unit/query_graph/util.py
Labels: dependencies, Skip Changelog

#2516 [DEV-3662] Tighten asset name limit
  .changelog/DEV-3662.yaml
  featurebyte/models/base.py
  featurebyte/models/entity.py
  tests/unit/models/test_base.py
Labels: documentation

#2522 [DEV-3673] Resolve conflict column name in `ItemTable.get_view()` by default
  .changelog/DEV-3673.yaml
  featurebyte/api/item_table.py
  featurebyte/query_graph/model/table.py
  tests/unit/api/test_item_view.py
Labels: documentation

#2503 [DEV-3644][cherry-pick] Implement data warehouse query caching for PreviewService (#2502)
  featurebyte/enum.py
  featurebyte/logging.py
  featurebyte/models/query_cache.py
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/routes/registry.py
  featurebyte/schema/worker/task/query_cache_cleanup.py
  featurebyte/service/feature_preview.py
  featurebyte/service/preview.py
  featurebyte/service/query_cache.py
  featurebyte/service/query_cache_cleanup.py
  featurebyte/service/query_cache_cleanup_scheduler.py
  featurebyte/service/query_cache_manager.py
  featurebyte/worker/registry.py
  featurebyte/worker/task/query_cache_cleanup.py
  tests/fixtures/expected_describe_request.sql
  tests/fixtures/query_graph/expected_describe_batches_0.sql
  tests/fixtures/query_graph/expected_describe_batches_1.sql
  tests/fixtures/query_graph/expected_describe_count_based_stats_only.sql
  tests/fixtures/query_graph/expected_describe_databricks.sql
  tests/fixtures/query_graph/expected_describe_date_range_and_size.sql
  tests/fixtures/query_graph/expected_describe_snowflake.sql
  tests/fixtures/query_graph/expected_describe_spark.sql
  tests/fixtures/query_graph/expected_describe_stats_names.sql
  tests/fixtures/query_graph/expected_value_counts_a.sql
  tests/fixtures/query_graph/expected_value_counts_b.sql
  tests/unit/query_graph/interpreter/test_preview.py
  tests/unit/routes/test_feature_store.py
  tests/unit/service/test_observation_table.py
  tests/unit/service/test_query_cache_manager.py
Labels: Skip Changelog

#2524 [DEV-3657] Deduplicate right table in simple join
  featurebyte/query_graph/sql/ast/join.py
  tests/fixtures/expected_feature_sql_combined_simple_aggregate_and_window_aggregate.sql
  tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
  tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
  tests/integration/api/test_dimension_view_operations.py
  tests/integration/api/test_item_view_operations.py
  tests/integration/api/test_view_sample.py
  tests/unit/api/test_item_view.py
  tests/unit/api/test_timezone_offset.py
  tests/unit/models/test_entity_universe.py
  tests/unit/query_graph/test_join.py
Labels: Skip Changelog

#2528 [DEV-3671] Filter input table based on selected entities when building tiles on demand
  featurebyte/models/user_defined_function.py
  featurebyte/query_graph/sql/ast/base.py
  featurebyte/query_graph/sql/ast/input.py
  featurebyte/query_graph/sql/ast/tile.py
  featurebyte/query_graph/sql/builder.py
  featurebyte/query_graph/sql/common.py
  featurebyte/query_graph/sql/entity_filter.py
  featurebyte/query_graph/sql/interpreter/tile.py
  tests/fixtures/expected_historical_requests_multiple_batches_feature_set_0.sql
  tests/fixtures/expected_historical_requests_multiple_batches_feature_set_2.sql
  tests/fixtures/expected_preview_sql_all_types.sql
  tests/fixtures/expected_tile_sql_on_demand.sql
  tests/fixtures/expected_tile_sql_on_demand_complex_composite.sql
  tests/fixtures/expected_tile_sql_on_demand_simple.sql
  tests/integration/api/test_features.py
  tests/integration/api/test_scd_view_operations.py
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/interpreter/test_interpreter.py
  tests/unit/query_graph/sql/test_tile.py
  tests/unit/query_graph/test_definition.py
  tests/unit/query_graph/test_extract_operation_structure.py
  tests/unit/query_graph/test_join.py
  tests/unit/query_graph/test_sql.py
Labels: Skip Changelog

#2529 [DEV-3675] Handle concurrent tile tasks on the same tile table (main)
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/session/base.py
  featurebyte/session/databricks_unity.py
  featurebyte/sql/tile_generate.py
  featurebyte/sql/tile_registry.py
  tests/fixtures/feature_manager/enable_new_feature.sql
  tests/fixtures/feature_manager/enable_new_feature_offset.sql
  tests/fixtures/feature_manager/enable_second_feature_later_date.sql
  tests/fixtures/feature_manager/enable_second_feature_much_later_date.sql
  tests/fixtures/feature_manager/enable_with_backfill_metadata.sql
  tests/fixtures/feature_manager/enable_without_last_run_metadata.sql
  tests/integration/tile/test_generate_tile.py
  tests/unit/conftest.py
Labels: Skip Changelog

#2521 [DEV-3674] Add support for BigQuery
  .changelog/DEV-3674.yaml
  .github/workflows/test.yaml
  Taskfile.yaml
  featurebyte/__init__.py
  featurebyte/enum.py
  featurebyte/models/credential.py
  featurebyte/query_graph/model/table.py
  featurebyte/query_graph/node/schema.py
  featurebyte/query_graph/sql/common.py
  featurebyte/session/base.py
  featurebyte/session/base_spark.py
  featurebyte/session/bigquery.py
  featurebyte/session/manager.py
  featurebyte/session/snowflake.py
  featurebyte/sql/bigquery/F_INDEX_TO_TIMESTAMP.sql
  featurebyte/sql/bigquery/F_TIMESTAMP_TO_INDEX.sql
  poetry.lock
  pyproject.toml
  tests/integration/conftest.py
  tests/integration/session/test_base.py
  tests/integration/session/test_bigquery.py
  tests/integration/session/test_databricks_unity.py
  tests/integration/session/test_snowflake.py
  tests/integration/session/test_spark.py
  tests/source_types.py
  tests/unit/models/test_credential.py
  tests/unit/session/test_bigquery_session.py
  tests/unit/session/test_snowflake_session.py
  tests/unit/session/test_spark.py
Labels: documentation, dependencies

#2532 [DEV-3680] Support OBJECT_AGG aggregation function for BigQuery
  featurebyte/query_graph/sql/adapter/__init__.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  tests/integration/conftest.py
  tests/integration/udf/test_object_agg.py
  tests/unit/query_graph/test_adapter.py
Labels: Skip Changelog

#2535 [DEV-3676] Fix feature table cache handling for concurrent requests (main)
  featurebyte/service/feature_table_cache.py
  featurebyte/service/feature_table_cache_metadata.py
  featurebyte/sql/tile_generate_entity_tracking.py
  tests/integration/api/test_historical_features.py
  tests/integration/conftest.py
  tests/unit/service/test_feature_table_cache.py
Labels: Skip Changelog

#2537 [DEV-3686] BigQuery: Fix detection of array dtype when listing table schema
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/session/bigquery.py
  tests/integration/conftest.py
Labels: Skip Changelog

#2539 [DEV-3689] reduce describe sql batch size
  featurebyte/service/preview.py
Labels: Skip Changelog

#2536 [DEV-3682] Add retry to sql execution on timeout
  featurebyte/migration/service/data_warehouse.py
  featurebyte/migration/service/mixin.py
  featurebyte/session/base.py
  tests/unit/session/test_base.py
Labels: Skip Changelog

#2540 [DEV-3684] BigQuery: Implement more UDFs
  featurebyte/sql/bigquery/F_COUNT_DICT_COSINE_SIMILARITY.sql
  featurebyte/sql/bigquery/F_COUNT_DICT_ENTROPY.sql
  featurebyte/sql/bigquery/F_COUNT_DICT_LEAST_FREQUENT.sql
  featurebyte/sql/bigquery/F_COUNT_DICT_MOST_FREQUENT.sql
  featurebyte/sql/bigquery/F_COUNT_DICT_MOST_FREQUENT_KEY_VALUE.sql
  featurebyte/sql/bigquery/F_COUNT_DICT_MOST_FREQUENT_VALUE.sql
  featurebyte/sql/bigquery/F_GET_RANK.sql
  featurebyte/sql/bigquery/F_GET_RELATIVE_FREQUENCY.sql
  featurebyte/sql/bigquery/F_TIMEZONE_OFFSET_TO_SECOND.sql
  tests/integration/conftest.py
  tests/integration/udf/bigquery/util.py
  tests/integration/udf/test_cosine_similarity.py
  tests/integration/udf/test_count_dict_entropy.py
  tests/integration/udf/test_get_rank.py
  tests/integration/udf/test_get_relative_frequency.py
  tests/integration/udf/test_least_frequent.py
  tests/integration/udf/test_most_frequent.py
  tests/integration/udf/test_timezone_offset_to_second.py
  tests/unit/session/test_bigquery_session.py
Labels: Skip Changelog

#2541 Revert "[DEV-3682] Add retry to sql execution on timeout"
  featurebyte/migration/service/data_warehouse.py
  featurebyte/migration/service/mixin.py
  featurebyte/session/base.py
  tests/unit/session/test_base.py
Labels: Skip Changelog

#2544 [DEV-3697] BigQuery: Support SCD view operations
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/query_graph/sql/ast/tile.py
  featurebyte/query_graph/sql/scd_helper.py
  featurebyte/query_graph/sql/tile_compute.py
  featurebyte/sql/base.py
  featurebyte/tile/tile_cache.py
  tests/fixtures/expected_preview_sql.sql
  tests/fixtures/expected_preview_sql_all_types.sql
  tests/fixtures/expected_preview_sql_category.sql
  tests/fixtures/expected_preview_sql_complex_feature.sql
  tests/fixtures/expected_preview_sql_databricks.sql
  tests/fixtures/expected_preview_sql_double_aggregation.sql
  tests/fixtures/expected_preview_sql_item_groupby.sql
  tests/fixtures/expected_preview_sql_latest_aggregation.sql
  tests/fixtures/expected_preview_sql_latest_aggregation_no_window.sql
  tests/fixtures/expected_preview_sql_multiple_nodes.sql
  tests/fixtures/expected_preview_sql_on_demand_features.sql
  tests/fixtures/expected_preview_sql_with_missing_value_imputation.sql
  tests/fixtures/expected_preview_sql_with_parent_serving_preparation.sql
  tests/fixtures/expected_preview_window_offset.sql
  tests/integration/api/test_scd_view_operations.py
  tests/integration/conftest.py
Labels: Skip Changelog
