Repository featurebyte/featurebyte, pull requests merged in 2024-03, with the labels that each got.

#2174 [chore] Improve entity validation and feature clusters handling
  featurebyte/api/feature_list.py
  featurebyte/models/historical_feature_table.py
  featurebyte/routes/batch_feature_table/controller.py
  featurebyte/routes/common/feature_or_target_table.py
  featurebyte/routes/historical_feature_table/controller.py
  featurebyte/routes/registry.py
  featurebyte/schema/info.py
  featurebyte/service/entity_validation.py
  featurebyte/service/feature_list.py
  featurebyte/service/feature_materialize.py
  featurebyte/service/feature_preview.py
  featurebyte/service/feature_table_cache.py
  featurebyte/service/historical_features.py
  featurebyte/service/online_serving.py
  featurebyte/service/target_helper/base_feature_or_target_computer.py
  tests/unit/service/test_entity_validation.py
Labels: Documentation Changes Confirmed

#2186 [chore] reduce / simplify queries for source table operations
  featurebyte/api/source_table.py
  featurebyte/enum.py
  featurebyte/query_graph/sql/materialisation.py
  featurebyte/routes/batch_feature_table/controller.py
  featurebyte/routes/batch_request_table/controller.py
  featurebyte/routes/common/base_materialized_table.py
  featurebyte/routes/common/feature_or_target_table.py
  featurebyte/routes/feature_store/api.py
  featurebyte/routes/feature_store/controller.py
  featurebyte/routes/historical_feature_table/controller.py
  featurebyte/routes/observation_table/controller.py
  featurebyte/routes/static_source_table/controller.py
  featurebyte/routes/target_table/controller.py
  featurebyte/schema/worker/task/historical_feature_table.py
  featurebyte/service/feature_store_warehouse.py
  featurebyte/service/preview.py
  featurebyte/session/base_spark.py
  featurebyte/session/manager.py
  tests/integration/conftest.py
  tests/unit/api/test_feature_store.py
  tests/unit/api/test_source_table.py
  tests/unit/conftest.py
  tests/unit/routes/base.py
  tests/unit/routes/test_feature_store.py
  tests/unit/service/conftest.py
  tests/unit/service/test_feature_store_warehouse.py
  tests/unit/service/test_preview.py
Labels: Documentation Changes Confirmed

#2218 [chore] Handle schema inconsistency between query fetch batches
  docker/docker-compose.yml
  featurebyte/api/materialized_table.py
  featurebyte/api/utils.py
  featurebyte/common/utils.py
  featurebyte/core/accessor/count_dict.py
  featurebyte/core/accessor/datetime.py
  featurebyte/enum.py
  featurebyte/exception.py
  featurebyte/routes/feature_store/api.py
  featurebyte/session/base.py
  featurebyte/session/base_spark.py
  featurebyte/session/databricks.py
  featurebyte/session/snowflake.py
  featurebyte/session/spark.py
  scripts/enforce_import_rules.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_feature_correctness.py
  tests/integration/api/test_item_view_operations.py
  tests/integration/api/test_scd_view_operations.py
  tests/integration/api/test_table_column_critical_data_info.py
  tests/integration/api/test_target_correctness.py
  tests/integration/conftest.py
  tests/integration/feature_manager/test_feature_manager.py
  tests/integration/session/test_base.py
  tests/integration/udf/test_object_agg.py
  tests/unit/routes/base.py
  tests/unit/session/test_databricks_session.py
  tests/unit/session/test_snowflake_session.py
Labels: Documentation Changes Confirmed

#2234 [DEV-3139] Update as_target docstring
  featurebyte/api/view.py
Labels: Documentation Changes Confirmed

#2243 [docs] removed torchserve repository
  docs/misc/torchserve/Dockerfile
  docs/misc/torchserve/README.md
  docs/misc/torchserve/Taskfile.yaml
  docs/misc/torchserve/config.properties
  docs/misc/torchserve/dockerd-entrypoint.sh
  docs/misc/torchserve/log4j2.xml
  docs/misc/torchserve/poetry.lock
  docs/misc/torchserve/pyproject.toml
  docs/misc/torchserve/serving/__init__.py
  docs/misc/torchserve/serving/handler.py
  docs/misc/torchserve/tests/__init__.py
Labels: refactoring, Skip Changelog

#2246 [CICD] bumping cicd actions
  .github/workflows/changelog_gen.yaml
  .github/workflows/daily-cron_gen.yaml
  .github/workflows/dependencies_gen.yaml
  .github/workflows/documentation_gen.yaml
  .github/workflows/lint_gen.yaml
  .github/workflows/publish-dev_gen.yaml
  .github/workflows/publish-public_gen.yaml
  .github/workflows/test-notebooks_gen.yaml
  .github/workflows/test_gen.yaml
Labels: github_actions, Skip Changelog

#2242 [DEV-3141] Support specifying target column during creation of observation tables
  .changelog/DEV-3141.yaml
  featurebyte/api/observation_table.py
  featurebyte/api/source_table.py
  featurebyte/api/target.py
  featurebyte/api/view.py
  featurebyte/exception.py
  featurebyte/models/observation_table.py
  featurebyte/routes/observation_table/controller.py
  featurebyte/routes/target_table/controller.py
  featurebyte/schema/info.py
  featurebyte/schema/observation_table.py
  featurebyte/schema/target_table.py
  featurebyte/schema/worker/task/observation_table.py
  featurebyte/schema/worker/task/observation_table_upload.py
  featurebyte/service/observation_table.py
  featurebyte/worker/task/observation_table.py
  featurebyte/worker/task/observation_table_upload.py
  featurebyte/worker/task/target_table.py
  tests/fixtures/request_payloads/observation_table.json
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_observation_table.py
  tests/unit/api/base_materialize_table_test.py
  tests/unit/api/observation_table/test_utils.py
  tests/unit/api/test_batch_request_table.py
  tests/unit/api/test_observation_table.py
  tests/unit/api/test_source_table.py
  tests/unit/conftest.py
  tests/unit/routes/test_context.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_list.py
  tests/unit/routes/test_observation_table.py
  tests/unit/routes/test_target.py
  tests/unit/routes/test_use_case.py
  tests/unit/schema/test_target_table.py
  tests/unit/service/test_observation_table.py
Labels: Documentation Changes Confirmed
