Repository featurebyte/featurebyte, pull requests merged in 2024-04, with the labels that each got.

#2259 [bug] fixing bad installation of databricks
  Taskfile.yaml
  docker/Dockerfile
Labels: bug, Skip Changelog

#2261 [cicd] Changelog task update to prevent failures on deletion
  .changelog/changelog-gen.py
  .github/workflows/changelog_gen.yaml
  .pre-commit-config.yaml
  Taskfile.yaml
Labels: Skip Changelog

#2262 [cicd] Implementing pytest-split for databricks test
  .changelog/pytest-split.yaml
  .github/workflows/changelog_gen.yaml
  .github/workflows/dependencies_gen.yaml
  .github/workflows/test_gen.yaml
  Taskfile.yaml
  poetry.lock
  pyproject.toml
Labels: enhancement, github_actions

#2269 [DEV-3201] Add historical feature table associated attributes
  .changelog/DEV-3201.yaml
  featurebyte/api/catalog.py
  featurebyte/api/credential.py
  featurebyte/api/deployment.py
  featurebyte/api/feature_list.py
  featurebyte/api/historical_feature_table.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/models/observation_table.py
  tests/unit/api/base_materialize_table_test.py
  tests/unit/api/test_batch_feature_table.py
  tests/unit/api/test_batch_request_table.py
  tests/unit/api/test_deployment.py
  tests/unit/api/test_historical_feature_table.py
  tests/unit/api/test_observation_table.py
Labels: Documentation Changes Confirmed

#2270 [DEV-3199] Fix backward compatibility broken by changes in target table
  featurebyte/api/target.py
  featurebyte/models/target_table.py
  featurebyte/routes/common/feature_or_target_table.py
  featurebyte/routes/historical_feature_table/controller.py
  featurebyte/routes/target_table/controller.py
  featurebyte/schema/target_table.py
  featurebyte/schema/worker/task/materialized_table_delete.py
  featurebyte/schema/worker/task/target_table.py
  featurebyte/service/target_table.py
  featurebyte/worker/task/materialized_table_delete.py
  featurebyte/worker/task/target_table.py
  tests/fixtures/request_payloads/target_table.json
  tests/unit/routes/base.py
  tests/unit/routes/test_target.py
  tests/unit/routes/test_target_table.py
  tests/unit/schema/test_target_table.py
  tests/unit/test_generate_payload_fixtures.py
  tests/unit/worker/task/test_materialized_table_delete.py
  tests/unit/worker/task/test_target_table.py
Labels: Skip Changelog

#2275 [DEV-3209] Revise progress update for make features production ready task
  featurebyte/service/feature_list_facade.py
  featurebyte/service/offline_store_feature_table_manager.py
  featurebyte/worker/task/feature_list_make_production_ready.py
Labels: Skip Changelog

#2276 [DEV-3211] Update get historical feature table to track dataset using mlflow
  featurebyte/api/historical_feature_table.py
  scripts/enforce_import_rules.py
  tests/unit/api/test_historical_feature_table.py
Labels: Skip Changelog

#2283 [DEV-3222|DEV-3221] bump databricks + snowflake + docker python
  .changelog/DEV-3221.yaml
  .changelog/DEV-3222.yaml
  .github/workflows/dependencies.yaml
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/publish-dev.yaml
  .github/workflows/publish-public.yaml
  .github/workflows/test.yaml
  Taskfile.yaml
  docker/Dockerfile
  docker/docker-compose.yml
  featurebyte/session/databricks.py
  featurebyte/session/databricks_unity.py
  poetry.lock
  pyproject.toml
Labels: documentation, dependencies

#2284 [chore] bump pillow and pymongo
  .changelog/vuln-fix.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies, Documentation Changes Confirmed

#2286 [DEV-3225] Limit asset names to 255 characters
  .changelog/DEV-3225.yaml
  featurebyte/models/base.py
  featurebyte/models/feature_store.py
  featurebyte/models/user_defined_function.py
  featurebyte/query_graph/node/schema.py
  featurebyte/routes/common/base_table.py
  featurebyte/schema/batch_feature_table.py
  featurebyte/schema/catalog.py
  featurebyte/schema/common/feature_or_target.py
  featurebyte/schema/context.py
  featurebyte/schema/credential.py
  featurebyte/schema/deployment.py
  featurebyte/schema/entity.py
  featurebyte/schema/feature.py
  featurebyte/schema/feature_job_setting_analysis.py
  featurebyte/schema/feature_list.py
  featurebyte/schema/feature_namespace.py
  featurebyte/schema/feature_store.py
  featurebyte/schema/historical_feature_table.py
  featurebyte/schema/info.py
  featurebyte/schema/observation_table.py
  featurebyte/schema/online_store.py
  featurebyte/schema/relationship_info.py
  featurebyte/schema/request_table.py
  featurebyte/schema/semantic.py
  featurebyte/schema/static_source_table.py
  featurebyte/schema/table.py
  featurebyte/schema/target.py
  featurebyte/schema/target_namespace.py
  featurebyte/schema/use_case.py
  featurebyte/schema/user_defined_function.py
  featurebyte/schema/worker/task/deployment_create_update.py
  featurebyte/schema/worker/task/feature_list_create.py
  tests/unit/models/test_base.py
  tests/unit/routes/test_item_table.py
  tests/unit/service/conftest.py
Labels: documentation, Documentation Changes Confirmed

#2288 [DEV-3215] Cast type for features with float dtype
  .changelog/DEV-3215.yaml
  featurebyte/core/accessor/count_dict.py
  featurebyte/query_graph/sql/ast/unary.py
  featurebyte/query_graph/sql/feature_compute.py
  featurebyte/query_graph/sql/specs.py
  tests/fixtures/expected_combined_sql_with_relationships.sql
  tests/fixtures/expected_get_online_features_multiple_queries_batch_request_table.sql
  tests/fixtures/expected_get_online_features_multiple_queries_dataframe.sql
  tests/fixtures/expected_historical_requests.sql
  tests/fixtures/expected_historical_requests_multiple_batches_feature_set_1.sql
  tests/fixtures/expected_historical_requests_multiple_batches_feature_set_2.sql
  tests/fixtures/expected_historical_requests_multiple_batches_feature_set_3.sql
  tests/fixtures/expected_historical_requests_output_row_index.sql
  tests/fixtures/expected_historical_requests_single_batch_output_query.sql
  tests/fixtures/expected_historical_requests_with_mapping.sql
  tests/fixtures/expected_historical_requests_with_missing_value_imputation.sql
  tests/fixtures/expected_online_feature_retrieval_complex.sql
  tests/fixtures/expected_online_feature_retrieval_filled_versions.sql
  tests/fixtures/expected_online_feature_retrieval_filled_versions_multiple_groups.sql
  tests/fixtures/expected_online_feature_retrieval_mixed.sql
  tests/fixtures/expected_online_feature_retrieval_request_subquery.sql
  tests/fixtures/expected_online_feature_retrieval_simple.sql
  tests/fixtures/expected_preview_sql.sql
  tests/fixtures/expected_preview_sql_all_types.sql
  tests/fixtures/expected_preview_sql_complex_feature.sql
  tests/fixtures/expected_preview_sql_databricks.sql
  tests/fixtures/expected_preview_sql_double_aggregation.sql
  tests/fixtures/expected_preview_sql_item_groupby.sql
  tests/fixtures/expected_preview_sql_latest_aggregation.sql
  tests/fixtures/expected_preview_sql_latest_aggregation_no_window.sql
  tests/fixtures/expected_preview_sql_lookup.sql
  tests/fixtures/expected_preview_sql_multiple_nodes.sql
  tests/fixtures/expected_preview_sql_with_missing_value_imputation.sql
  tests/fixtures/expected_preview_sql_with_parent_serving_preparation.sql
  tests/fixtures/feature_job_setting_analysis/backtest.parquet
  tests/fixtures/feature_job_status/expected_session_logs.parquet
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table_empty.sql
  tests/fixtures/feature_materialize/initialize_new_columns_new_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_new_table_databricks.sql
  tests/fixtures/feature_materialize/materialize_features_queries.sql
  tests/fixtures/feature_materialize/materialize_features_queries_composite_entity.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_queries.sql
  tests/unit/api/test_dimension_view.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_feature_list.py
  tests/unit/api/test_table_column.py
  tests/unit/query_graph/model/test_table_data.py
  tests/unit/query_graph/test_feature_compute.py
  tests/unit/query_graph/test_sql.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_list.py
  tests/unit/service/test_online_serving.py
Labels: documentation, Documentation Changes Confirmed

#2287 [DEV-3230] Create precomputed lookup feature table records
  featurebyte/models/entity_lookup_feature_table.py
  featurebyte/models/offline_store_feature_table.py
  featurebyte/models/precomputed_lookup_feature_table.py
  featurebyte/service/entity_lookup_feature_table.py
  featurebyte/service/feature_materialize.py
  featurebyte/service/offline_store_feature_table.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/fixtures/offline_store_feature_table/cust_id_to_gender_universe.sql
  tests/fixtures/offline_store_feature_table/transaction_id_to_cust_id_universe.sql
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/service/test_offline_store_feature_table_manager.py
  tests/util/helper.py
Labels: Skip Changelog

#2292 [DEV-3229] Add use case filtering by feature ID support & implement deployment use case validation
  featurebyte/models/context.py
  featurebyte/models/feature_list_namespace.py
  featurebyte/routes/deployment/controller.py
  featurebyte/routes/use_case/api.py
  featurebyte/routes/use_case/controller.py
  featurebyte/schema/context.py
  tests/integration/api/test_serving_parent_features.py
  tests/unit/api/test_databricks.py
  tests/unit/api/test_deployment.py
Labels: Skip Changelog

#2295 [DEV-3230] Populate offline tables for precomputed lookup feature tables
  featurebyte/service/feature_materialize.py
  tests/fixtures/feature_materialize/initialize_features_no_entity_databricks_unity.sql
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table_empty.sql
  tests/fixtures/feature_materialize/initialize_new_columns_new_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_new_table_databricks.sql
  tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/service/conftest.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_online_serving_feast.py
Labels: Skip Changelog

#2297 [chore] Reduce nodes processing batch size for historical features
  featurebyte/query_graph/sql/batch_helper.py
  featurebyte/tile/tile_cache.py
Labels: Skip Changelog

#2296 [DEV-3230] Add initialization for new precomputed lookup feature tables
  featurebyte/service/feature_materialize.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table.sql
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/conftest.py
  tests/unit/service/test_feature_materialize.py
Labels: Skip Changelog

#2298 [DEV-3241] Make Feast registry deployment specific
  featurebyte/feast/model/registry.py
  featurebyte/feast/schema/registry.py
  featurebyte/feast/service/feature_store.py
  featurebyte/feast/service/registry.py
  featurebyte/models/deployment.py
  featurebyte/models/offline_store_feature_table.py
  featurebyte/routes/deployment/controller.py
  featurebyte/schema/deployment.py
  featurebyte/service/deploy.py
  featurebyte/service/deployment.py
  featurebyte/service/feature_materialize.py
  featurebyte/service/offline_store_feature_table.py
  featurebyte/service/offline_store_feature_table_manager.py
  featurebyte/worker/task/catalog_online_store_update.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/feast/service/test_registry.py
  tests/unit/routes/test_deployment.py
  tests/unit/service/conftest.py
  tests/unit/service/test_feast_registry.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_offline_store_feature_table_manager.py
  tests/unit/service/test_online_serving_feast.py
  tests/unit/service/test_registry.py
  tests/util/helper.py
Labels: Skip Changelog

#2303 [DEV-3241] Fix feast feature store used for materialization
  featurebyte/feast/service/feature_store.py
  featurebyte/feast/utils/registry_construction.py
  featurebyte/service/feature_materialize.py
  featurebyte/worker/task/catalog_online_store_update.py
  tests/integration/feature_store_integration/test_feature_materialize.py
Labels: Skip Changelog

#2311 [DEV-3284] Make dtype mandatory during target namespace creation
  .changelog/DEV-3284.yaml
  featurebyte/api/target_namespace.py
  featurebyte/enum.py
  featurebyte/schema/target_namespace.py
  tests/fixtures/request_payloads/target_namespace.json
  tests/integration/api/test_serving_parent_features.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/api/test_observation_table.py
  tests/unit/api/test_target.py
  tests/unit/api/test_target_namespace.py
  tests/unit/api/test_use_case.py
  tests/unit/test_generate_payload_fixtures.py
Labels: documentation, Documentation Changes Confirmed

#2313 [DEV-3295] Fix Feast ODFV construction bugs
  featurebyte/feast/utils/on_demand_view.py
  tests/unit/feast/service/test_registry.py
Labels: Skip Changelog

#2320 [DEV-3230] Fix precomputed lookup feature table universe for ttl features
  featurebyte/service/feature_materialize.py
  tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup_ttl.sql
  tests/unit/service/conftest.py
  tests/unit/service/test_feature_materialize.py
Labels: Skip Changelog

#2321 [DEV-3230] Remove code related to dynamic entity lookup feature tables
  featurebyte/feast/utils/registry_construction.py
  featurebyte/models/entity_lookup_feature_table.py
  featurebyte/models/offline_store_feature_table.py
  featurebyte/service/entity_lookup_feature_table.py
  featurebyte/service/offline_store_feature_table.py
  featurebyte/service/offline_store_feature_table_comment.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/feast/conftest.py
  tests/unit/feast/utils/test_registry_construction.py
  tests/unit/service/test_offline_feature_store_comment.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#2316 [chore] Dropping aioredis in favour of redis.asyncio
  .changelog/deps-aioredis.yaml
  featurebyte/api/feature_job.py
  featurebyte/app.py
  featurebyte/common/env_util.py
  featurebyte/feast/utils/materialize_helper.py
  featurebyte/session/databricks.py
  poetry.lock
  pyproject.toml
  tests/integration/conftest.py
  tests/integration/storage/test_azure_storage.py
  tests/integration/storage/test_s3_storage.py
  tests/unit/conftest.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_feature_table_cache.py
  tests/unit/session/test_databricks_session.py
  tests/unit/worker/task/test_feature_job_setting_analysis.py
Labels: documentation, dependencies

#2323 [chore] Remove unused enabled_serving_entity_ids in FeatureListModel
  featurebyte/models/feature_list.py
  featurebyte/schema/feature_list.py
  featurebyte/service/deploy.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/api/test_feature_list.py
  tests/unit/models/test_feature_list.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: documentation, Skip Changelog

#2325 [fix] mkdocs error on upgrade
  poetry.lock
  pyproject.toml
Labels: Skip Changelog

#2326 [DEV-3313] Update feature online enabled status after materialization
  featurebyte/service/deploy.py
  featurebyte/service/online_enable.py
  featurebyte/service/working_schema.py
  tests/unit/conftest.py
  tests/unit/service/test_deploy.py
Labels: Skip Changelog

#2329 [DEV-3314] Batch by columns when materializing online features
  featurebyte/service/feature_materialize.py
  tests/unit/service/conftest.py
  tests/unit/service/test_feature_materialize.py
Labels: Skip Changelog
