Repository featurebyte/featurebyte, pull requests merged in 2024-06, with the labels that each got.

#2382 [DEV-3463] Make `skip_fill_na` default to True
  .changelog/DEV-3463.yaml
  featurebyte/api/aggregator/asat_aggregator.py
  featurebyte/api/aggregator/forward_aggregator.py
  featurebyte/api/aggregator/forward_asat_aggregator.py
  featurebyte/api/aggregator/simple_aggregator.py
  featurebyte/api/aggregator/util.py
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/api/groupby.py
  tests/fixtures/expected_feature_sql_combined_simple_aggregate_and_window_aggregate.sql
  tests/fixtures/expected_get_online_features_multiple_queries_batch_request_table.sql
  tests/fixtures/expected_get_online_features_multiple_queries_dataframe.sql
  tests/fixtures/feature_materialize/initialize_features_no_entity_databricks_unity.sql
  tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
  tests/fixtures/feature_materialize/materialize_features_queries_internal_relationships.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
  tests/fixtures/offline_store_feature_table/feature_cluster_with_internal_relationships.json
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_feature_correctness.py
  tests/integration/api/test_forward_aggregate_asat.py
  tests/integration/api/test_item_view_operations.py
  tests/integration/api/test_scd_view_operations.py
  tests/integration/api/test_serving_parent_features.py
  tests/integration/api/test_table_column_critical_data_info.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/api/test_aggregate_asat_common.py
  tests/unit/api/test_databricks.py
  tests/unit/api/test_groupby.py
  tests/unit/api/test_item_view.py
Labels: documentation

#2384 [DEV-3465] Implement sampling with seed without sorting full table
  .changelog/DEV-3465.yaml
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/fixtures/query_graph/expected_describe_date_range_and_size.sql
  tests/integration/api/test_view_describe.py
  tests/integration/api/test_view_sample.py
  tests/unit/query_graph/interpreter/test_preview.py
  tests/unit/routes/test_feature_store.py
  tests/unit/service/test_specialized_dtype.py
Labels: documentation

#2385 [chore] Upgrade snowflake connector
  featurebyte/session/snowflake.py
  poetry.lock
  pyproject.toml
  tests/unit/session/test_snowflake_session.py
Labels: dependencies

#2388 [RELEASE] Adding changelogs for 1.1 release
  .changelog/DEV-3463.yaml
  .changelog/DEV-3465.yaml
  CHANGELOG.md
Labels: Skip Changelog

#2391 [DEV-3483] Update class variable annotation to make it explicit
  featurebyte/api/api_object.py
  featurebyte/api/base_table.py
  featurebyte/api/batch_feature_table.py
  featurebyte/api/batch_request_table.py
  featurebyte/api/catalog.py
  featurebyte/api/change_view.py
  featurebyte/api/context.py
  featurebyte/api/credential.py
  featurebyte/api/data_source.py
  featurebyte/api/deployment.py
  featurebyte/api/dimension_table.py
  featurebyte/api/dimension_view.py
  featurebyte/api/entity.py
  featurebyte/api/event_table.py
  featurebyte/api/event_view.py
  featurebyte/api/feature.py
  featurebyte/api/feature_group.py
  featurebyte/api/feature_job_setting_analysis.py
  featurebyte/api/feature_list.py
  featurebyte/api/feature_namespace.py
  featurebyte/api/feature_or_target_namespace_mixin.py
  featurebyte/api/feature_store.py
  featurebyte/api/groupby.py
  featurebyte/api/historical_feature_table.py
  featurebyte/api/item_table.py
  featurebyte/api/item_view.py
  featurebyte/api/materialized_table.py
  featurebyte/api/observation_table.py
  featurebyte/api/online_store.py
  featurebyte/api/periodic_task.py
  featurebyte/api/relationship.py
  featurebyte/api/request_column.py
  featurebyte/api/scd_table.py
  featurebyte/api/scd_view.py
  featurebyte/api/source_table.py
  featurebyte/api/static_source_table.py
  featurebyte/api/table.py
  featurebyte/api/target.py
  featurebyte/api/target_namespace.py
  featurebyte/api/use_case.py
  featurebyte/api/user_defined_function.py
  featurebyte/api/view.py
  featurebyte/core/accessor/count_dict.py
  featurebyte/core/accessor/datetime.py
  featurebyte/core/accessor/feature_datetime.py
  featurebyte/core/accessor/feature_string.py
  featurebyte/core/accessor/string.py
  featurebyte/core/accessor/target_datetime.py
  featurebyte/core/accessor/target_string.py
  featurebyte/core/accessor/vector.py
  featurebyte/core/frame.py
  featurebyte/core/generic.py
  featurebyte/core/series.py
Labels: Skip Changelog

#2379 [DEV-3446] Update has_ttl for feature with unbounded window
  featurebyte/models/offline_store_ingest_query.py
  featurebyte/query_graph/transform/decompose_point.py
  featurebyte/service/feature_offline_store_info.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/api/test_deployment.py
  tests/unit/query_graph/transform/test_decompose_point.py
Labels: Skip Changelog

#2396 [DEV-3483] Update `BaseModel` used in `models`, `query_graph` & `schema` directories
  featurebyte/models/feature_job_setting_analysis.py
  featurebyte/models/offline_store_feature_table.py
  featurebyte/models/periodic_task.py
  featurebyte/models/tile_registry.py
  featurebyte/query_graph/graph_node/base.py
  featurebyte/query_graph/node/agg_func.py
  featurebyte/query_graph/node/base.py
  featurebyte/query_graph/node/count_dict.py
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/node/distance.py
  featurebyte/query_graph/node/function.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/node/input.py
  featurebyte/query_graph/node/metadata/operation.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  featurebyte/query_graph/node/mixin.py
  featurebyte/query_graph/node/nested.py
  featurebyte/query_graph/node/request.py
  featurebyte/query_graph/node/scalar.py
  featurebyte/query_graph/node/string.py
  featurebyte/query_graph/node/unary.py
  featurebyte/query_graph/transform/decompose_point.py
  featurebyte/query_graph/transform/flattening.py
  featurebyte/query_graph/transform/null_filling_value.py
  featurebyte/query_graph/transform/on_demand_function.py
  featurebyte/query_graph/transform/on_demand_view.py
  featurebyte/query_graph/transform/operation_structure.py
  featurebyte/query_graph/transform/pruning.py
  featurebyte/query_graph/transform/quick_pruning.py
  featurebyte/query_graph/transform/reconstruction.py
  featurebyte/query_graph/transform/sdk_code.py
  featurebyte/schema/common/operation.py
  featurebyte/schema/worker/task/deployment_create_update.py
  featurebyte/schema/worker/task/feature_list_create.py
  featurebyte/sql/base.py
Labels: Skip Changelog

#2398 [DEV-3506] Set default feature job setting during SCDTable registration
  featurebyte/schema/scd_table.py
  tests/unit/api/test_change_view.py
  tests/unit/api/test_scd_table.py
  tests/unit/test_generate_payload_fixtures.py
Labels: Skip Changelog

#2399 [chore] Use a different test table name to avoid collision
  tests/integration/udf/test_object_agg.py
Labels: Skip Changelog

#2405 [DEV-3523] Support batch document creation and deletion
  featurebyte/service/base_document.py
  tests/unit/service/test_base_document.py
Labels: Skip Changelog

#2406 [chore] Split snowflake integration tests and run tests sequentially
  .github/workflows/test.yaml
  Taskfile.yaml
Labels: Skip Changelog

#2408 [chore] Clean up unused method in FeatureExecutionPlan
  featurebyte/query_graph/sql/feature_compute.py
  tests/unit/query_graph/test_feature_compute.py
Labels: Skip Changelog

#2409 [DEV-3507] Fix update feature store details validation
  featurebyte/routes/feature_store/controller.py
  featurebyte/service/session_manager.py
  tests/conftest.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/integration/feature_store_integration/test_update_online_store.py
  tests/unit/api/test_databricks.py
  tests/unit/api/test_dimension_view.py
  tests/unit/api/test_event_view.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_item_view.py
  tests/unit/api/test_null_filling_value.py
  tests/unit/api/test_offline_ingest_query_graph.py
  tests/unit/api/test_request_column.py
  tests/unit/api/test_scd_view.py
  tests/unit/conftest.py
  tests/unit/feast/conftest.py
  tests/unit/routes/conftest.py
  tests/unit/routes/test_batch_feature_table.py
  tests/unit/routes/test_feature_store.py
  tests/unit/service/test_feast_registry.py
  tests/unit/service/test_feature_materialize.py
  tests/unit/service/test_offline_feature_store_comment.py
  tests/unit/service/test_offline_store_feature_table_manager.py
  tests/unit/service/test_online_serving_feast.py
Labels: Skip Changelog

#2411 [DEV-3539] Fix error when using request column as key in dictionary feature operations
  .changelog/DEV-3539.yaml
  featurebyte/core/accessor/count_dict.py
  featurebyte/query_graph/sql/ast/util.py
  featurebyte/typing.py
  tests/integration/api/test_dimension_view_operations.py
  tests/unit/conftest.py
  tests/unit/core/accessor/test_count_dict.py
Labels: documentation

#2412 [DEV-3538] Do not convert keys to string in value counts
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/fixtures/query_graph/expected_value_counts_no_casting.sql
  tests/unit/query_graph/interpreter/test_preview.py
  tests/unit/service/test_preview.py
Labels: Skip Changelog

#2413 [RELEASE] Featurebyte version 1.1.2
  .changelog/DEV-3446.yaml
  .changelog/DEV-3507.yaml
  .changelog/DEV-3539.yaml
  CHANGELOG.md
  pyproject.toml
Labels: Skip Changelog

#2417 [DEV-3555] Add attributes to track feature ID & name used in historical feature table computation
  featurebyte/api/feature_group.py
  featurebyte/models/feature_list.py
  featurebyte/models/historical_feature_table.py
  featurebyte/schema/constant.py
  featurebyte/schema/feature.py
  featurebyte/schema/feature_list.py
  featurebyte/service/historical_feature_table.py
  featurebyte/worker/task/historical_feature_table.py
  tests/fixtures/request_payloads/historical_feature_table.json
  tests/unit/api/test_historical_feature_table.py
  tests/unit/routes/test_feature_list.py
Labels: documentation, Skip Changelog
