Repository featurebyte/featurebyte, pull requests merged in 2024-12, with the labels that each got.

#2690 [DEV-3912] Disable bigquery storage client when running in io workers
  docker/entrypoint.sh
  featurebyte/common/env_util.py
  featurebyte/service/session_manager.py
  featurebyte/session/bigquery.py
  tests/integration/conftest.py
  tests/integration/session/test_bigquery.py
Labels: Skip Changelog

#2693 [DEV-3914] Add `FLAT_DICT` to `DBVarType.dictionary_types()`
  featurebyte/enum.py
Labels: Skip Changelog

#2694 [chore] Add TimestampSchema class for generic timestamp columns
  featurebyte/query_graph/model/timestamp_schema.py
  poetry.lock
  pyproject.toml
  tests/unit/query_graph/model/test_timestamp_schema.py
Labels: dependencies

#2691 [DEV-3910] Add catalog cleanup task
  featurebyte/enum.py
  featurebyte/models/base.py
  featurebyte/models/feature_job_setting_analysis.py
  featurebyte/models/feature_materialize_run.py
  featurebyte/models/feature_table_cache_metadata.py
  featurebyte/models/materialized_table.py
  featurebyte/models/offline_store_feature_table.py
  featurebyte/models/online_store_compute_query.py
  featurebyte/models/online_store_table_version.py
  featurebyte/models/task.py
  featurebyte/models/tile_registry.py
  featurebyte/query_graph/node/schema.py
  featurebyte/routes/registry.py
  featurebyte/schema/worker/task/catalog_cleanup.py
  featurebyte/worker/registry.py
  featurebyte/worker/task/catalog_cleanup.py
  featurebyte/worker/task/feature_list_create.py
  tests/unit/routes/test_feature_job_setting_analysis.py
  tests/unit/worker/task/test_catalog_cleanup.py
Labels: Skip Changelog

#2698 [chore] Bumping snowflake-connection-python
  poetry.lock
  pyproject.toml
Labels: dependencies

#2701 [chore] bumping vuln deps
  poetry.lock
  pyproject.toml
Labels: dependencies

#2705 [chore] Revise catalog cleanup task
  featurebyte/worker/task/catalog_cleanup.py
Labels: Skip Changelog

#2706 [DEV-3920] Add WarehouseTableService for temporary tile tables cleanup
  featurebyte/models/warehouse_table.py
  featurebyte/routes/registry.py
  featurebyte/service/feature_table_cache.py
  featurebyte/service/historical_features.py
  featurebyte/service/historical_features_and_target.py
  featurebyte/service/tile/tile_task_executor.py
  featurebyte/service/tile_cache.py
  featurebyte/service/tile_manager.py
  featurebyte/service/warehouse_table_service.py
  featurebyte/sql/tile_generate.py
  tests/integration/conftest.py
  tests/integration/tile/test_generate_tile.py
  tests/integration/tile/test_tile_manager.py
  tests/unit/service/conftest.py
  tests/unit/service/test_historical_features.py
  tests/unit/service/test_tile_cache_query_by_observation_table.py
  tests/unit/service/test_warehouse_table_service.py
  tests/unit/tile/test_unit_snowflake_tile.py
  tests/unit/worker/task/test_catalog_cleanup.py
Labels: Skip Changelog

#2708 [DEV-3919] Fix materialization of FLAT_DICT type features in BigQuery (main)
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  tests/integration/api/test_dict_operations.py
Labels: Skip Changelog

#2709 [DEV-3910] Update catalog cleanup to delete audit logs
  featurebyte/persistent/base.py
  featurebyte/worker/task/catalog_cleanup.py
  tests/unit/persistent/test_mongo.py
  tests/unit/worker/task/test_catalog_cleanup.py
Labels: Skip Changelog

#2710 [chore] downgrading python-muiltiparttdue to fastapi-users
  poetry.lock
  pyproject.toml
Labels: dependencies

#2707 [chore] bumping starlette
  featurebyte/app.py
  featurebyte/schema/feature_list.py
  featurebyte/schema/worker/task/feature_list_create.py
  poetry.lock
  pyproject.toml
  tests/unit/routes/test_feature_list.py
Labels: dependencies

#2713 [DEV-3923] Update dtype to physical type mapping for array dtype (post-release)
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/tiling.py
  featurebyte/service/feature_table_cache_metadata.py
  tests/fixtures/feature_table_cache/feature_query.sql
  tests/integration/api/test_features.py
  tests/integration/api/test_view_describe.py
  tests/integration/api/test_view_sample.py
  tests/integration/conftest.py
  tests/unit/conftest.py
  tests/unit/service/test_feature_table_cache_metadata.py
Labels: Skip Changelog

#2715 [chore] Add try-catch to model deserialization (catalog cleanup task)
  featurebyte/worker/task/catalog_cleanup.py
Labels: Skip Changelog

#2716 [chore] Expose BigQuery schemas in package namespace
  featurebyte/__init__.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/models/credential.py
  featurebyte/query_graph/node/schema.py
Labels: documentation

#2720 [chore] Add missing docs
  featurebyte/common/documentation/documentation_layout.py
Labels: documentation

#2719 [DEV-3918] Support cron expression string for cron-based feature job settings
  featurebyte/api/time_series_table.py
  featurebyte/models/periodic_task.py
  featurebyte/query_graph/model/feature_job_setting.py
  poetry.lock
  pyproject.toml
  scripts/enforce_import_rules.py
  tests/unit/api/test_time_series_table.py
  tests/unit/models/test_time_series_table.py
  tests/unit/query_graph/model/test_feature_job_setting.py
Labels: documentation, dependencies, Skip Changelog

#2724 [chore] Releasing version 2.1.0
  .changelog/DEV-3727.yaml
  .changelog/DEV-3735.yaml
  .changelog/DEV-3740.yaml
  .changelog/DEV-3744.yaml
  .changelog/DEV-3745.yaml
  .changelog/DEV-3748.yaml
  .changelog/DEV-3751.yaml
  .changelog/DEV-3765.yaml
  .changelog/DEV-3790-1.yaml
  .changelog/DEV-3790.yaml
  .changelog/DEV-3802.yaml
  .changelog/DEV-3808.yaml
  .changelog/DEV-3810.yaml
  .changelog/DEV-3827.yaml
  .changelog/DEV-3832.yaml
  .changelog/DEV-3856-1.yaml
  .changelog/DEV-3856-2.yaml
  .changelog/DEV-3856-3.yaml
  .changelog/DEV-3856-4.yaml
  .changelog/DEV-3863.yaml
  .changelog/DEV-3884.yaml
  .changelog/DEV-3890.yaml
  .changelog/DEV-3896.yaml
  .changelog/DEV-3902.yaml
  .changelog/DEV-3903.yaml
  .changelog/DEV-3913.yaml
  .changelog/DEV-3918.yaml
  .changelog/DEV-3922.yaml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: documentation, Skip Changelog

#2723 [DEV-3924] Add feature job setting union type
  featurebyte/api/time_series_table.py
  featurebyte/core/series.py
  featurebyte/models/offline_store_ingest_query.py
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/service/feature.py
  featurebyte/service/version.py
  tests/unit/query_graph/model/test_feature_job_setting.py
Labels: documentation, Skip Changelog

#2721 [DEV-3925] Update operation structure to include dtype metadata
  featurebyte/api/aggregator/base_aggregator.py
  featurebyte/core/accessor/count_dict.py
  featurebyte/core/frame.py
  featurebyte/query_graph/model/dtype.py
  featurebyte/query_graph/node/agg_func.py
  featurebyte/query_graph/node/base.py
  featurebyte/query_graph/node/binary.py
  featurebyte/query_graph/node/count_dict.py
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/node/distance.py
  featurebyte/query_graph/node/function.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/node/input.py
  featurebyte/query_graph/node/metadata/operation.py
  featurebyte/query_graph/node/mixin.py
  featurebyte/query_graph/node/request.py
  featurebyte/query_graph/node/schema.py
  featurebyte/query_graph/node/string.py
  featurebyte/query_graph/node/unary.py
  featurebyte/query_graph/node/vector.py
  tests/unit/models/test_feature.py
  tests/unit/query_graph/test_function.py
  tests/unit/query_graph/test_metadata_operation.py
  tests/unit/query_graph/util.py
Labels: Skip Changelog

#2726 [DEV-3928] Add TIME_SERIES_WINDOW_AGGREGATE node type
  featurebyte/query_graph/enum.py
  featurebyte/query_graph/model/window.py
  featurebyte/query_graph/node/generic.py
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/test_extract_operation_structure.py
Labels: Skip Changelog

#2730 [DEV-3930] Add helper to simulate cron schedules for historical features
  featurebyte/enum.py
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/sql/scd_helper.py
  featurebyte/routes/registry.py
  featurebyte/service/cron_helper.py
  tests/fixtures/cron_helper/test_register_request_table_with_job_schedule.sql
  tests/integration/service/test_cron_helper.py
  tests/unit/conftest.py
  tests/unit/service/test_cron_helper.py
Labels: Skip Changelog

#2729 [DEV-3926] Add timestamp schema validation
  featurebyte/query_graph/model/timestamp_schema.py
  featurebyte/query_graph/node/schema.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/service/base_table_document.py
  featurebyte/service/base_table_validation.py
  featurebyte/service/scd_table_validation.py
  tests/fixtures/query_graph/test_input/scd_varchar_bigquery.sql
  tests/fixtures/query_graph/test_input/scd_varchar_tz_column_offset_bigquery.sql
  tests/fixtures/query_graph/test_input/scd_varchar_tz_column_timezone_bigquery.sql
  tests/fixtures/query_graph/test_input/scd_varchar_utc_bigquery.sql
  tests/integration/api/test_scd_view_operations.py
  tests/integration/conftest.py
  tests/integration/service/test_scd_table_validation.py
  tests/unit/api/test_scd_table.py
  tests/unit/query_graph/model/test_timestamp_schema.py
  tests/unit/service/test_scd_table_validation.py
Labels: Skip Changelog

#2732 [DEV-3926] Revise time series schema validation
  featurebyte/query_graph/model/timestamp_schema.py
  featurebyte/query_graph/sql/ast/input.py
  featurebyte/service/base_table_validation.py
  tests/integration/api/test_scd_view_operations.py
  tests/integration/conftest.py
Labels: Skip Changelog

#2735 [chore] Fix broken test
  featurebyte/service/base_table_validation.py
  tests/integration/api/test_scd_view_operations.py
Labels: Skip Changelog

#2736 [chore] Tag timezone column with timezone semantic
  featurebyte/models/time_series_table.py
  featurebyte/routes/common/base_table.py
  featurebyte/schema/worker/task/table_validation.py
  tests/fixtures/request_payloads/time_series_table.json
  tests/fixtures/sdk_code/time_series_table.py
  tests/unit/api/test_time_series_table.py
  tests/unit/conftest.py
  tests/unit/models/test_time_series_table.py
  tests/unit/routes/test_time_series_table.py
Labels: Skip Changelog

#2737 [DEV-3938] Fix initialize_new_columns on empty feature columns
  featurebyte/service/feature_materialize.py
  tests/fixtures/feature_materialize/initialize_new_columns_no_feature_columns.sql
  tests/unit/service/test_feature_materialize.py
Labels: Skip Changelog

#2739 [DEV-3931] Handle feature job timezone in cron_helper
  featurebyte/enum.py
  featurebyte/service/cron_helper.py
  tests/fixtures/cron_helper/test_register_request_table_with_job_schedule.sql
  tests/integration/service/test_cron_helper.py
  tests/unit/service/test_cron_helper.py
Labels: Skip Changelog

#2740 [DEV-3937] Update cronjob scheduling to support specifying timezone
  featurebyte/models/periodic_task.py
  featurebyte/service/task_manager.py
  featurebyte/worker/schedulers.py
  tests/integration/worker/conftest.py
  tests/integration/worker/test_task_manager.py
  tests/unit/worker/test_schedulers.py
Labels: Skip Changelog

#2741 [DEV-3930] Rework CronHelper to match usage pattern in get_historical_features
  featurebyte/models/periodic_task.py
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/sql/cron.py
  featurebyte/service/cron_helper.py
  tests/integration/service/test_cron_helper.py
  tests/unit/query_graph/sql/test_cron.py
  tests/unit/service/test_cron_helper.py
Labels: Skip Changelog
