Repository featurebyte/featurebyte, pull requests merged in 2024-09, with the labels that each got.

#2545 [DEV-3698] BigQuery: Support event view operations
  featurebyte/feature_manager/model.py
  featurebyte/models/feature.py
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/query_graph/sql/ast/binary.py
  featurebyte/query_graph/sql/ast/count_dict.py
  featurebyte/query_graph/sql/ast/datetime.py
  featurebyte/query_graph/sql/ast/literal.py
  featurebyte/query_graph/sql/ast/string.py
  featurebyte/query_graph/sql/ast/vector.py
  featurebyte/query_graph/sql/groupby_helper.py
  featurebyte/session/bigquery.py
  featurebyte/sql/bigquery/F_OBJECT_DELETE.sql
  featurebyte/worker/task/observation_table_upload.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/conftest.py
  tests/unit/core/accessor/test_string.py
  tests/unit/core/test_series.py
  tests/unit/models/test_user_defined_function.py
  tests/unit/query_graph/sql/adapter/base_adapter_test.py
  tests/unit/query_graph/sql/test_groupby_helper.py
  tests/unit/session/test_bigquery_session.py
  tests/util/helper.py
Labels: Skip Changelog

#2548 [chore] bumping vulnerable packages
  .changelog/VULN-0.yaml
  .github/workflows/lint.yaml
  Taskfile.lint.yaml
  featurebyte/session/bigquery.py
  poetry.lock
  pyproject.toml
Labels: dependencies, github_actions

#2551 [bug] fixing artifact publish action defaulting to not adding hidden file
  .github/workflows/documentation.yaml
  .github/workflows/test.yaml
  Taskfile.lint.yaml
Labels: bug, github_actions, Skip Changelog

#2538 [DEV-3676] Use retry when executing queries to add columns
  featurebyte/service/feature_table_cache.py
Labels: Skip Changelog

#2553 [DEV-3707] BigQuery: Support more dictionary operations
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/sql/bigquery/F_GET_VALUE.sql
  featurebyte/tile/tile_cache.py
  tests/integration/api/test_dimension_view_operations.py
  tests/integration/conftest.py
  tests/unit/session/test_bigquery_session.py
Labels: Skip Changelog

#2555 [DEV-3711] BigQuery: Fix observation table creation by sampling from view
  featurebyte/models/request_input.py
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  tests/fixtures/request_input/materialize_bigquery.sql
  tests/integration/api/test_view_sample.py
  tests/integration/conftest.py
  tests/unit/conftest.py
  tests/unit/models/test_request_input.py
Labels: Skip Changelog

#2556 [DEV-3712] BigQuery: Support distance operations and enable more tests
  .github/workflows/test.yaml
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  tests/integration/api/test_distance_operations.py
  tests/integration/api/test_scd_view_operations.py
  tests/integration/conftest.py
  tests/integration/service/test_feature_table_cache.py
Labels: Skip Changelog

#2560 [chore] Bump freeware version for BigQuery support
  poetry.lock
  pyproject.toml
Labels: dependencies

#2559 [chore] bump vuln package cryptography
  poetry.lock
  pyproject.toml
Labels: dependencies, Skip Changelog

#2561 [DEV-3720] BigQuery: Set online store table names to upper case
  featurebyte/query_graph/sql/online_serving_util.py
  tests/fixtures/expected_get_online_features_multiple_queries_batch_request_table.sql
  tests/fixtures/expected_get_online_features_multiple_queries_dataframe.sql
  tests/fixtures/expected_online_feature_retrieval_complex.sql
  tests/fixtures/expected_online_feature_retrieval_filled_versions.sql
  tests/fixtures/expected_online_feature_retrieval_filled_versions_multiple_groups.sql
  tests/fixtures/expected_online_feature_retrieval_mixed.sql
  tests/fixtures/expected_online_feature_retrieval_request_subquery.sql
  tests/fixtures/expected_online_feature_retrieval_simple.sql
  tests/fixtures/feature_manager/enable_second_feature_later_date.sql
  tests/fixtures/feature_manager/enable_second_feature_much_later_date.sql
  tests/fixtures/feature_manager/enable_with_backfill_metadata.sql
  tests/fixtures/feature_manager/enable_without_last_run_metadata.sql
  tests/fixtures/feature_materialize/initialize_features_no_entity_databricks_unity.sql
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table_empty.sql
  tests/fixtures/feature_materialize/initialize_new_columns_new_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_new_table_databricks.sql
  tests/fixtures/feature_materialize/materialize_features_queries.sql
  tests/fixtures/feature_materialize/materialize_features_queries_composite_entity.sql
  tests/fixtures/feature_materialize/materialize_features_queries_composite_entity_batch.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup_ttl.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_queries.sql
  tests/fixtures/offline_store_feature_table/latest_aggregation_with_window_universe.sql
  tests/integration/feature_manager/test_feature_manager.py
  tests/unit/api/test_deployment.py
  tests/unit/feature_manager/test_unit_snowflake_feature.py
  tests/unit/models/test_entity_universe.py
  tests/unit/models/test_feature.py
  tests/unit/query_graph/test_online_serving.py
  tests/unit/service/test_offline_store_feature_table_manager.py
  tests/unit/service/test_online_serving.py
Labels: Skip Changelog

#2562 [DEV-3721] BigQuery: Cast key to string in get_rank and get_relative_frequency
  featurebyte/query_graph/sql/ast/count_dict.py
  tests/integration/conftest.py
  tests/unit/query_graph/test_sql.py
Labels: Skip Changelog

#2564 [DEV-3722] BigQuery: Disable unnecessary sort in random_sample
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  tests/fixtures/adapter/bigquery_random_sample.sql
  tests/fixtures/request_input/materialize_bigquery.sql
  tests/unit/query_graph/sql/adapter/test_bigquery.py
Labels: Skip Changelog

#2565 [DEV-3723] Validate table existence when create_table_as fails with exists flag
  featurebyte/session/base.py
  featurebyte/sql/base.py
  tests/integration/conftest.py
  tests/unit/feature_manager/test_unit_snowflake_feature.py
Labels: Skip Changelog

#2567 [DEV-3718] Make event_id, item_id, scd natural_key_column optional for table registration
  .changelog/DEV-3718.yaml
  featurebyte/api/change_view.py
  featurebyte/api/dimension_view.py
  featurebyte/api/event_view.py
  featurebyte/api/item_table.py
  featurebyte/api/item_view.py
  featurebyte/api/scd_table.py
  featurebyte/api/scd_view.py
  featurebyte/api/source_table.py
  featurebyte/api/view.py
  featurebyte/models/entity_universe.py
  featurebyte/models/event_table.py
  featurebyte/models/item_table.py
  featurebyte/models/scd_table.py
  featurebyte/query_graph/model/table.py
  featurebyte/routes/item_table/controller.py
  featurebyte/schema/event_table.py
  featurebyte/schema/info.py
  featurebyte/schema/item_table.py
  featurebyte/schema/scd_table.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_item_table.py
  tests/unit/api/test_scd_table.py
  tests/unit/api/test_view.py
Labels: documentation

#2568 [DEV-3713] BigQuery: Fix timestamps handling in tile sql and entity universe
  featurebyte/common/date_util.py
  featurebyte/models/entity_universe.py
  featurebyte/models/precomputed_lookup_feature_table.py
  featurebyte/query_graph/sql/ast/tile.py
  featurebyte/service/feature_manager.py
  tests/fixtures/feature_manager/enable_new_feature.sql
  tests/fixtures/feature_manager/enable_new_feature_offset.sql
  tests/fixtures/feature_manager/enable_second_feature_later_date.sql
  tests/fixtures/feature_manager/enable_second_feature_much_later_date.sql
  tests/fixtures/feature_manager/enable_with_backfill_metadata.sql
  tests/fixtures/feature_manager/enable_without_last_run_metadata.sql
  tests/integration/feature_manager/test_feature_manager.py
Labels: Skip Changelog

#2572 [DEV-3714] BigQuery: Fix to_timestamp usage in FeatureMaterializeService for deployment
  featurebyte/service/feature_materialize.py
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table_empty.sql
Labels: Skip Changelog

#2573 [DEV-3728] BigQuery: Fix dtype detection for numeric types without scale
  featurebyte/session/bigquery.py
  tests/integration/session/test_bigquery.py
  tests/unit/session/test_bigquery_session.py
Labels: Skip Changelog

#2574 [RELEASE] featurebyte 2.0.1
  .changelog/DEV-3647.yaml
  .changelog/DEV-3662.yaml
  .changelog/DEV-3673.yaml
  .changelog/DEV-3674.yaml
  .changelog/DEV-3709.yaml
  .changelog/DEV-3718.yaml
  .changelog/VULN-0.yaml
  .github/workflows/publish-dev.yaml
  CHANGELOG.md
  pyproject.toml
Labels: Skip Changelog

#2576 [DEV-3732] BigQuery: Cast key to string in get_value
  featurebyte/query_graph/sql/ast/count_dict.py
  tests/unit/query_graph/test_sql.py
Labels: Skip Changelog

#2575 [DEV-3731] BigQuery: Handle date type preview and add datetime diff tests
  featurebyte/session/bigquery.py
  tests/integration/api/test_datetime.py
Labels: Skip Changelog

#2579 [DEV-3734] BigQuery: Fix errors in F_GET_VALUE and PARSE_JSON
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/session/bigquery.py
  featurebyte/sql/bigquery/F_GET_VALUE.sql
  tests/integration/udf/test_get_value.py
Labels: Skip Changelog

#2577 [DEV-3727] Add support for sampling by time range during observation table registration
  .changelog/DEV-3727.yaml
  featurebyte/api/obs_table/utils.py
  featurebyte/api/source_table.py
  featurebyte/api/view.py
  featurebyte/models/observation_table.py
  featurebyte/models/request_input.py
  featurebyte/query_graph/sql/common.py
  featurebyte/schema/observation_table.py
  featurebyte/worker/task/observation_table.py
  tests/fixtures/request_payloads/observation_table.json
  tests/integration/api/test_observation_table.py
  tests/unit/api/observation_table/test_utils.py
  tests/unit/models/test_request_input.py
  tests/unit/routes/test_target_table.py
Labels: documentation

#2585 [DEV-3737] BigQuery: Implement vector aggregation UDFs
  .github/workflows/test.yaml
  featurebyte/session/bigquery.py
  featurebyte/sql/bigquery/F_VECTOR_AGGREGATE_MAX.sql
  featurebyte/sql/bigquery/F_VECTOR_AGGREGATE_SIMPLE_AVERAGE.sql
  featurebyte/sql/bigquery/F_VECTOR_AGGREGATE_SIMPLE_AVG.sql
  featurebyte/sql/bigquery/F_VECTOR_AGGREGATE_SUM.sql
  tests/integration/udf/bigquery/util.py
  tests/integration/udf/conftest.py
  tests/integration/udf/snowflake/util.py
  tests/integration/udf/spark/util.py
  tests/integration/udf/test_vector_aggregate.py
  tests/source_types.py
  tests/unit/session/test_bigquery_session.py
Labels: Skip Changelog

#2588 [chore] Bump Feast to 0.40.1
  featurebyte/feast/patch.py
  featurebyte/feast/utils/registry_construction.py
  featurebyte/service/online_serving.py
  poetry.lock
  pyproject.toml
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/feast/test_patch.py
Labels: dependencies, Skip Changelog

#2589 [chore] supporting python3.12
  .github/workflows/publish-dev.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies

#2597 [DEV-3747] Skip validation error during SDK api object listing
  featurebyte/api/api_handler/base.py
  tests/unit/api/test_feature_store.py
Labels: Skip Changelog

#2599 [DEV-3737] BigQuery: Fix UDF calls in tiling.py to use fully qualified names
  featurebyte/query_graph/sql/aggregator/window.py
  featurebyte/query_graph/sql/specs.py
  featurebyte/query_graph/sql/tiling.py
  tests/unit/query_graph/test_feature_common.py
  tests/unit/query_graph/test_feature_compute.py
  tests/unit/query_graph/test_tiling.py
Labels: Skip Changelog

#2598 [chore] Store test durations in test workflow
  .github/workflows/test.yaml
  .test_durations
  Taskfile.yaml
Labels: Skip Changelog

#2593 [DEV-3713] BigQuery: Support online serving with feast integration
  featurebyte/common/env_util.py
  featurebyte/feast/infra/offline_stores/bigquery.py
  featurebyte/feast/model/feature_store.py
  featurebyte/models/feature_list.py
  featurebyte/models/feature_list_store_info.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/service/feature_materialize.py
  featurebyte/session/bigquery.py
  featurebyte/sql/tile_schedule_online_store.py
  featurebyte/worker/util/batch_feature_creator.py
  poetry.lock
  pyproject.toml
  tests/fixtures/feature_manager/enable_new_feature.sql
  tests/fixtures/feature_manager/enable_new_feature_offset.sql
  tests/fixtures/feature_manager/enable_second_feature_later_date.sql
  tests/fixtures/feature_manager/enable_second_feature_much_later_date.sql
  tests/fixtures/feature_manager/enable_with_backfill_metadata.sql
  tests/fixtures/feature_manager/enable_with_required_tiles_available.sql
  tests/fixtures/feature_manager/enable_without_last_run_metadata.sql
  tests/integration/api/test_scd_view_operations.py
  tests/integration/conftest.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/session/test_bigquery_session.py
  tests/unit/worker/task/test_batch_feature_create.py
Labels: dependencies, Skip Changelog

#2602 [chore] Remove more warnings
  featurebyte/api/api_handler/feature_namespace.py
  featurebyte/models/base.py
  featurebyte/service/feature_materialize.py
  featurebyte/worker/task/feature_job_setting_analysis.py
  poetry.lock
  pyproject.toml
  tests/integration/conftest.py
  tests/unit/api/test_deployment.py
  tests/unit/api/test_feature.py
  tests/unit/api/test_feature_list.py
  tests/unit/models/test_dimension_table.py
  tests/unit/models/test_entity.py
  tests/unit/models/test_event_table.py
  tests/unit/models/test_feature.py
  tests/unit/models/test_feature_list.py
  tests/unit/routes/test_deployment.py
Labels: dependencies

#2608 [DEV-3714] BigQuery: Fix binary operations with a scalar timestamp
  featurebyte/query_graph/sql/ast/util.py
  tests/integration/conftest.py
  tests/unit/query_graph/test_sql.py
Labels: Skip Changelog

#2609 [DEV-3766] BigQuery: Fix handling native datetime objects in session register_table
  featurebyte/session/bigquery.py
  tests/integration/session/test_bigquery.py
Labels: Skip Changelog

#2610 [chore] Override max durations for pytest-split
  .test_durations
  Taskfile.yaml
  tests/integration/conftest.py
Labels: Skip Changelog

#2611 [DEV-3768] Add SCDTableValidationService for table registration guardrails
  featurebyte/exception.py
  featurebyte/query_graph/sql/aggregator/base_asat.py
  featurebyte/query_graph/sql/asat_helper.py
  featurebyte/routes/registry.py
  featurebyte/service/scd_table_validation.py
  tests/fixtures/scd_table_validation/no_end_timestamp.sql
  tests/fixtures/scd_table_validation/with_end_timestamp.sql
  tests/integration/service/test_scd_table_validation.py
  tests/unit/api/test_source_table.py
  tests/unit/service/test_scd_table_validation.py
Labels: Skip Changelog

#2612 [DEV-3767] Add endpoints to preview materialized tables
  featurebyte/api/materialized_table.py
  featurebyte/common/env_util.py
  featurebyte/routes/batch_feature_table/api.py
  featurebyte/routes/batch_feature_table/controller.py
  featurebyte/routes/batch_request_table/api.py
  featurebyte/routes/common/base_materialized_table.py
  featurebyte/routes/common/schema.py
  featurebyte/routes/feature_store/api.py
  featurebyte/routes/historical_feature_table/api.py
  featurebyte/routes/observation_table/api.py
  featurebyte/routes/static_source_table/api.py
  featurebyte/routes/static_source_table/controller.py
  featurebyte/routes/target_table/api.py
  featurebyte/service/feature_store_warehouse.py
  tests/conftest.py
  tests/integration/api/test_event_view_operations.py
  tests/unit/api/test_observation_table.py
  tests/unit/api/test_static_source_table.py
  tests/unit/common/test_env_util.py
  tests/unit/routes/base.py
Labels: Skip Changelog
