Repository featurebyte/featurebyte, pull requests merged in 2024-01, with the labels that each got.

#2035 [chore] Move `FeatureListNamespaceModel` to `feature_list_namespace.py`
  featurebyte/__init__.py
  featurebyte/api/feature_list.py
  featurebyte/models/feature_list.py
  featurebyte/models/feature_list_namespace.py
  featurebyte/routes/feature_list_namespace/controller.py
  featurebyte/schema/feature_list_namespace.py
  featurebyte/schema/info.py
  featurebyte/service/deploy.py
  featurebyte/service/feature_list.py
  featurebyte/service/feature_list_facade.py
  featurebyte/service/feature_list_namespace.py
  featurebyte/service/feature_list_status.py
  featurebyte/service/feature_readiness.py
  tests/unit/api/test_feature_list.py
  tests/unit/models/test_feature_list.py
  tests/unit/service/test_feature_list_namespace.py
  tests/unit/service/test_feature_list_status.py
Labels: Documentation Changes Confirmed

#2034 [DEV-2901] Fix output variable type of count aggregation
  .changelog/DEV-2901.yaml
  featurebyte/api/feature.py
  featurebyte/query_graph/node/agg_func.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/api/test_groupby.py
  tests/unit/core/accessor/test_count_dict.py
  tests/unit/query_graph/test_extract_operation_structure.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Documentation Changes Confirmed

#2040 [DEV-2929] Set user role during Snowflake session initialization
  .changelog/DEV-2929.yaml
  featurebyte/session/snowflake.py
  tests/unit/session/test_snowflake_session.py
Labels: bug

#2045 [DEV-2931 Simplify user defined function route creation schema
  .changelog/DEV-2931.yaml
  featurebyte/api/user_defined_function.py
  featurebyte/routes/user_defined_function/api.py
  featurebyte/routes/user_defined_function/controller.py
  featurebyte/schema/user_defined_function.py
  featurebyte/service/user_defined_function.py
  tests/fixtures/request_payloads/user_defined_function.json
  tests/unit/api/test_user_defined_function.py
  tests/unit/routes/test_user_defined_function.py
  tests/unit/service/test_user_defined_function.py
Labels: Documentation Changes Confirmed

#2056 [DEV-2938] Fix count dictionary entropy UDF behavior for edge cases
  .changelog/DEV-2938.yaml
  featurebyte/session/base_spark.py
  featurebyte/session/databricks_unity.py
  featurebyte/session/snowflake.py
  featurebyte/sql/databricks_unity/F_COUNT_DICT_ENTROPY.sql
  featurebyte/sql/snowflake/F_COUNT_DICT_ENTROPY.sql
  hive-udf/lib/build.gradle
  hive-udf/lib/src/main/java/com/featurebyte/hive/udf/CountDictEntropyV2.java
  hive-udf/lib/src/test/java/com/featurebyte/hive/udf/CountDictTransformsTest.java
  tests/integration/udf/test_count_dict_entropy.py
Labels: bug

#1999 [chore] Try using python-setup poetry cache
  .github/workflows/daily-cron_gen.yaml
  .github/workflows/documentation_gen.yaml
  .github/workflows/lint_gen.yaml
  .github/workflows/publish-dev_gen.yaml
  .github/workflows/publish-public_gen.yaml
  .github/workflows/test-notebooks_gen.yaml
  .github/workflows/test_gen.yaml
Labels: dependencies

#2072 [DEV-2125] Support description specification during table creation
  .changelog/DEV-2125.yaml
  featurebyte/api/source_table.py
  featurebyte/routes/common/base_table.py
  featurebyte/schema/table.py
  poetry.lock
  tests/fixtures/request_payloads/dimension_table.json
  tests/fixtures/request_payloads/event_table.json
  tests/fixtures/request_payloads/item_table.json
  tests/fixtures/request_payloads/scd_table.json
  tests/integration/conftest.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_source_table.py
  tests/unit/conftest.py
  tests/unit/routes/base.py
  tests/unit/service/test_info.py
Labels: Documentation Changes Confirmed

#2070 [DEV-2912] feature table cache service usage
  featurebyte/models/materialized_table.py
  featurebyte/query_graph/sql/feature_historical.py
  featurebyte/service/feature_table_cache.py
  featurebyte/service/historical_features.py
  featurebyte/service/historical_features_and_target.py
  featurebyte/service/target_helper/compute_target.py
  featurebyte/session/base.py
  featurebyte/worker/task/historical_feature_table.py
  featurebyte/worker/task/materialized_table_delete.py
  featurebyte/worker/task/mixin.py
  featurebyte/worker/task/target_table.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/service/test_feature_table_cache.py
  tests/unit/conftest.py
  tests/unit/routes/test_historical_feature_table.py
  tests/unit/service/conftest.py
  tests/unit/service/test_feature_table_cache.py
  tests/unit/service/test_historical_features.py
Labels: Documentation Changes Confirmed

#2080 [DEV-2972] Fix getting sample entity serving values fail when entity has null values
  .changelog/DEV-2972.yaml
  featurebyte/query_graph/sql/interpreter/preview.py
  tests/unit/routes/test_deployment.py
Labels: bug

#2078 [vuln] Bump pyarrow to 14.0.2
  featurebyte/session/databricks.py
  featurebyte/session/spark.py
  poetry.lock
  pyproject.toml
  tests/integration/feature_store_integration/test_feature_materialize.py
Labels: dependencies

#2090 [chore] fix pillow vulnerability
  poetry.lock
  pyproject.toml
Labels: dependencies
