Repository featurebyte/featurebyte, pull requests merged in 2024-05, with the labels that each got.

#2331 [DEV-3294] Fix handling of composite entity in precomputed lookup feature tables
  featurebyte/models/offline_store_feature_table.py
  featurebyte/models/precomputed_lookup_feature_table.py
  featurebyte/query_graph/sql/entity.py
  featurebyte/service/entity_lookup_feature_table.py
  featurebyte/service/feature_materialize.py
  featurebyte/service/online_serving.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#2335 [DEV-3331] Fix feast get online features error for composite entities
  featurebyte/service/online_serving.py
  tests/unit/conftest.py
  tests/unit/service/conftest.py
  tests/unit/service/test_online_serving_feast.py
Labels: Skip Changelog

#2337 [DEV-3232] Make online disable handling more robust to unexpected failures
  featurebyte/service/feature.py
  featurebyte/service/feature_materialize.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/unit/service/conftest.py
  tests/unit/service/test_feature_materialize.py
Labels: Skip Changelog

#2336 [DEV-3334] Update DataBricks feature specs generation for precomputed lookup feature table
  featurebyte/api/accessor/databricks.py
  featurebyte/models/feature_list.py
  featurebyte/models/feature_list_store_info.py
  featurebyte/service/deploy.py
  featurebyte/service/feature_list.py
  featurebyte/service/offline_store_feature_table.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/unit/api/test_databricks.py
  tests/unit/service/test_deploy.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#2330 [Deps] Adding pyopenssl as a main dependency
  .changelog/pyopenssl-required.yaml
  .github/workflows/dependencies.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies

#2340 [chore] Save debug info for troubleshooting on entity universe creation failure
  featurebyte/models/entity_universe.py
  featurebyte/service/deploy.py
  featurebyte/service/offline_store_feature_table.py
  featurebyte/service/offline_store_feature_table_construction.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#2341 [DEV-3343][DEV-3363] Implement null filling for DataBricks UDF
  featurebyte/models/offline_store_ingest_query.py
  featurebyte/query_graph/node/metadata/config.py
  featurebyte/query_graph/node/nested.py
  featurebyte/service/deploy.py
  featurebyte/service/feature_manager.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/api/test_databricks.py
  tests/unit/api/test_offline_ingest_query_graph.py
  tests/util/helper.py
Labels: Skip Changelog

#2351 [DEV-3312] Handle offline store feature table bad state when disabling a deployment
  featurebyte/service/exception.py
  featurebyte/service/offline_store_feature_table_construction.py
  featurebyte/service/offline_store_feature_table_manager.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#2352 [DEV-3302] Exclude missing entity values from entity universe
  featurebyte/models/entity_universe.py
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_existing_table_empty.sql
  tests/fixtures/feature_materialize/initialize_new_columns_new_table.sql
  tests/fixtures/feature_materialize/initialize_new_columns_new_table_databricks.sql
  tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
  tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table.sql
  tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table_missing_column.sql
  tests/fixtures/feature_materialize/materialize_features_queries.sql
  tests/fixtures/feature_materialize/materialize_features_queries_composite_entity.sql
  tests/fixtures/feature_materialize/materialize_features_queries_composite_entity_batch.sql
  tests/fixtures/feature_materialize/materialize_features_queries_internal_relationships.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup_ttl.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_queries.sql
  tests/fixtures/offline_store_feature_table/aggregate_asat_feature_universe.sql
  tests/fixtures/offline_store_feature_table/cust_id_to_gender_universe.sql
  tests/fixtures/offline_store_feature_table/lookup_feature_universe.sql
  tests/fixtures/offline_store_feature_table/transaction_id_to_cust_id_universe.sql
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/models/test_entity_universe.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#2353 [DEV-3381] Fix count dictionary key retrieval in on demand function
  featurebyte/query_graph/node/count_dict.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/api/test_offline_ingest_query_graph.py
  tests/unit/query_graph/on_demand_function/test_count_dict.py
Labels: Skip Changelog

#2362 [DEV-3321] Patch `BaseFeatureView.with_projection` to improve runtime performance
  featurebyte/feast/patch.py
  featurebyte/service/online_serving.py
Labels: Skip Changelog

#2363 [chore] Patch `typechecked` in Feast
  featurebyte/_overrides/__init__.py
  featurebyte/_overrides/typechecked_override.py
  featurebyte/app.py
  featurebyte/feast/patch.py
Labels: Skip Changelog

#2364 [DEV-3028] Update item table lookup universe to filter by event timestamps
  featurebyte/models/entity_lookup_feature_table.py
  featurebyte/models/entity_universe.py
  featurebyte/models/item_table.py
  featurebyte/models/parent_serving.py
  featurebyte/models/precomputed_lookup_feature_table.py
  featurebyte/routes/registry.py
  featurebyte/service/item_table.py
  featurebyte/service/parent_serving.py
  tests/fixtures/offline_store_feature_table/item_id_to_item_type_universe.sql
  tests/integration/conftest.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/unit/conftest.py
  tests/unit/service/test_offline_store_feature_table_manager.py
  tests/unit/service/test_parent_serving.py
Labels: Skip Changelog

#2367 [1.0.3] Release + update changelog and version
  .changelog/DEV-2983.yaml
  .changelog/DEV-3095.yaml
  .changelog/DEV-3096.yaml
  .changelog/DEV-3101.yaml
  .changelog/DEV-3102.yaml
  .changelog/DEV-3103.yaml
  .changelog/DEV-3104.yaml
  .changelog/DEV-3105.yaml
  .changelog/DEV-3111.yaml
  .changelog/DEV-3112.yaml
  .changelog/DEV-3114.yaml
  .changelog/DEV-3136.yaml
  .changelog/DEV-3141.yaml
  .changelog/DEV-3160.yaml
  .changelog/DEV-3169.yaml
  .changelog/DEV-3175.yaml
  .changelog/DEV-3197.yaml
  .changelog/DEV-3201.yaml
  .changelog/DEV-3202.yaml
  .changelog/DEV-3203.yaml
  .changelog/DEV-3215.yaml
  .changelog/DEV-3221.yaml
  .changelog/DEV-3222.yaml
  .changelog/DEV-3225.yaml
  .changelog/DEV-3234.yaml
  .changelog/DEV-3255.yaml
  .changelog/DEV-3283.yaml
  .changelog/DEV-3284.yaml
  .changelog/DEV-3297.yaml
  .changelog/DEV-3306.yaml
  .changelog/DEV-3344.yaml
  .changelog/DEV-3365.yaml
  .changelog/DEV-3380.yaml
  .changelog/DEV-3382.yaml
  .changelog/DEV-3383.yaml
  .changelog/DEV-3393.yaml
  .changelog/deps-aioredis.yaml
  .changelog/pyopenssl-required.yaml
  .changelog/pytest-split.yaml
  .changelog/vuln-fix.yaml
  CHANGELOG.md
  pyproject.toml
Labels: Skip Changelog

#2368 [DEV-3406] Support offset parameter in query graph for window aggregates
  featurebyte/query_graph/model/graph.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/sql/aggregator/window.py
  featurebyte/query_graph/sql/online_store_compute_query.py
  featurebyte/query_graph/sql/specs.py
  featurebyte/query_graph/sql/tile_util.py
  tests/fixtures/expected_preview_window_offset.sql
  tests/fixtures/offline_store_feature_table/feature_cluster_disabled_one_feature.json
  tests/fixtures/offline_store_feature_table/feature_cluster_one_feature.json
  tests/fixtures/offline_store_feature_table/feature_cluster_two_features.json
  tests/fixtures/request_payloads/feature_iet.json
  tests/fixtures/request_payloads/feature_sum_2h.json
  tests/fixtures/request_payloads/feature_sum_30m.json
  tests/fixtures/request_payloads/historical_feature_table.json
  tests/unit/api/test_groupby.py
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/test_feature_common.py
  tests/unit/query_graph/test_feature_compute.py
  tests/unit/query_graph/test_feature_preview.py
  tests/unit/query_graph/test_nested_graph_pruning.py
  tests/unit/query_graph/test_online_serving.py
  tests/unit/service/test_feature.py
  tests/unit/service/test_version.py
Labels: Skip Changelog

#2369 [DEV-3408] Add offset parameter in forward aggregate node
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/sql/aggregator/forward.py
  tests/fixtures/aggregator/expected_forward_aggregator.sql
  tests/fixtures/aggregator/expected_forward_aggregator_offset.sql
  tests/fixtures/request_payloads/target.json
  tests/unit/api/aggregator/test_forward_aggregator.py
  tests/unit/query_graph/sql/aggregator/test_forward.py
  tests/unit/query_graph/test_definition.py
  tests/unit/service/test_feature_table_cache.py
Labels: Skip Changelog

#2370 [DEV-3408] Support offset parameter in aggregate_over method
  .changelog/DEV-3408.yaml
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/api/groupby.py
  featurebyte/feature_manager/model.py
  featurebyte/models/tile.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/sql/interpreter/tile.py
  featurebyte/query_graph/sql/specs.py
  featurebyte/query_graph/sql/tile_compute.py
  featurebyte/service/feature_manager.py
  tests/fixtures/expected_preview_window_offset.sql
  tests/fixtures/feature_manager/enable_new_feature_offset.sql
  tests/fixtures/sdk_code/complex_event_item_feature.py
  tests/fixtures/sdk_code/complex_multi_table_feature.py
  tests/fixtures/sdk_code/feature_fraction.py
  tests/fixtures/sdk_code/feature_item_cosine_similarity.py
  tests/fixtures/sdk_code/feature_time_based_with_data_cleaning_operations.py
  tests/fixtures/sdk_code/feature_with_cleaned_tz_offset_column.py
  tests/fixtures/sdk_code/feature_with_request_column.py
  tests/fixtures/sdk_code/feature_with_timestamp_filtering.py
  tests/fixtures/sdk_code/feature_with_udf_used_in_view.py
  tests/fixtures/sdk_code/isin_feature.py
  tests/integration/api/test_feature_correctness.py
  tests/integration/query_graph/test_online_serving.py
  tests/unit/api/test_aggregate_over.py
  tests/unit/api/test_feature.py
  tests/unit/query_graph/interpreter/test_interpreter.py
  tests/unit/service/test_feature_manager.py
  tests/unit/service/tile/test_tile_cache.py
Labels: documentation

#2371 [DEV-3408] Add offset parameter to forward_aggregate method
  .changelog/DEV-3408.yaml
  featurebyte/api/aggregator/forward_aggregator.py
  featurebyte/api/groupby.py
  featurebyte/query_graph/node/generic.py
  tests/fixtures/sdk_code/forward_aggregate_target_code_generation.py
  tests/integration/api/test_target_correctness.py
  tests/unit/api/aggregator/test_forward_aggregator.py
  tests/unit/api/test_target.py
Labels: documentation
