Repository featurebyte/featurebyte, pull requests merged in 2025-08, with the labels that each got.

#3081 [chore] Update docs
  featurebyte/common/documentation/documentation_layout.py
Labels: documentation

#3070 [DEV-4105] Handle deleted tables in dev datasets
  featurebyte/models/development_dataset.py
  featurebyte/persistent/base.py
  featurebyte/persistent/mongo.py
  featurebyte/routes/development_dataset/controller.py
  featurebyte/schema/development_dataset.py
  featurebyte/service/base_document.py
  featurebyte/service/development_dataset.py
  tests/unit/routes/base.py
  tests/unit/routes/test_development_dataset.py
  tests/unit/test_generate_payload_fixtures.py
Labels: Skip Changelog

#3088 [DEV-4138] Add models, services and routes for SnapshotsTable
  .changelog/DEV-4138.yaml
  featurebyte/__init__.py
  featurebyte/api/base_table.py
  featurebyte/api/snapshots_table.py
  featurebyte/api/snapshots_view.py
  featurebyte/api/source_table.py
  featurebyte/app.py
  featurebyte/enum.py
  featurebyte/models/proxy_table.py
  featurebyte/models/snapshots_table.py
  featurebyte/query_graph/enum.py
  featurebyte/query_graph/model/common_table.py
  featurebyte/query_graph/model/table.py
  featurebyte/query_graph/node/input.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  featurebyte/query_graph/node/nested.py
  featurebyte/routes/common/base.py
  featurebyte/routes/common/base_table.py
  featurebyte/routes/registry.py
  featurebyte/routes/snapshots_table/__init__.py
  featurebyte/routes/snapshots_table/api.py
  featurebyte/routes/snapshots_table/controller.py
  featurebyte/schema/info.py
  featurebyte/schema/snapshots_table.py
  featurebyte/schema/worker/task/table_validation.py
  featurebyte/service/base_table_document.py
  featurebyte/service/snapshots_table.py
  featurebyte/service/snapshots_table_validation.py
  featurebyte/service/table_columns_info.py
  featurebyte/service/table_facade.py
  tests/fixtures/backward_compatibility/get_routes.txt
  tests/fixtures/request_payloads/snapshots_table.json
  tests/fixtures/sdk_code/saved_snapshots_table.py
  tests/fixtures/sdk_code/snapshots_table.py
  tests/fixtures/sdk_code/snapshots_view.py
  tests/fixtures/sdk_code/snapshots_view_with_column_clean_ops.py
  tests/unit/api/base_table_test.py
  tests/unit/api/base_view_test.py
  tests/unit/api/conftest.py
  tests/unit/api/test_catalog.py
  tests/unit/api/test_snapshots_table.py
  tests/unit/api/test_snapshots_view.py
  tests/unit/conftest.py
  tests/unit/routes/test_snapshots_table.py
  tests/unit/test_generate_payload_fixtures.py
Labels: documentation

#3094 add status, plan ids to dev dataset models
  featurebyte/models/development_dataset.py
  featurebyte/routes/development_dataset/controller.py
  featurebyte/schema/development_dataset.py
  tests/fixtures/request_payloads/development_dataset.json
  tests/unit/routes/test_development_dataset.py
Labels: Skip Changelog

#3096 [chore] Refine progress tracking in historical feature table creation
  featurebyte/service/feature_table_cache.py
  featurebyte/service/target_helper/base_feature_or_target_computer.py
  featurebyte/worker/task/historical_feature_table.py
Labels: Skip Changelog

#3095 [DEV-4143] Add support for lookup features in SnapshotsView
  featurebyte/api/snapshots_view.py
  featurebyte/query_graph/model/graph.py
  featurebyte/query_graph/model/node_hash_util.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/node/input.py
  featurebyte/query_graph/sql/aggregator/base.py
  featurebyte/query_graph/sql/aggregator/base_lookup.py
  featurebyte/query_graph/sql/parent_serving.py
  featurebyte/query_graph/sql/specifications/base_lookup.py
  featurebyte/query_graph/sql/specifications/lookup.py
  featurebyte/query_graph/sql/specifications/lookup_target.py
  tests/fixtures/aggregator/expected_lookup_aggregator_snapshots_daily.sql
  tests/fixtures/aggregator/expected_lookup_aggregator_snapshots_daily_with_blind_spot.sql
  tests/fixtures/aggregator/expected_lookup_aggregator_snapshots_monthly.sql
  tests/fixtures/aggregator/expected_lookup_aggregator_snapshots_monthly_with_blind_spot.sql
  tests/fixtures/aggregator/expected_lookup_aggregator_snapshots_with_blind_spot.sql
  tests/fixtures/expected_preview_sql_snapshots_lookup.sql
  tests/fixtures/offline_store_feature_table/feature_cluster_with_internal_relationships.json
  tests/integration/api/test_snapshots_view_operations.py
  tests/integration/api/test_time_series_view_operations.py
  tests/integration/conftest.py
  tests/unit/api/test_dimension_view.py
  tests/unit/api/test_item_view.py
  tests/unit/api/test_scd_view.py
  tests/unit/api/test_snapshots_view.py
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/test_definition.py
  tests/unit/query_graph/test_feature_compute.py
  tests/unit/query_graph/test_feature_preview.py
  tests/unit/query_graph/test_lookup_aggregator.py
  tests/unit/query_graph/util.py
  tests/util/helper.py
Labels: Skip Changelog

#3099 [chore] Bump featurebyte-freeware to 0.2.23
  poetry.lock
  pyproject.toml
Labels: dependencies

#3101 [DEV-4145] Add support for serving parent features via SnapshotsTable
  featurebyte/query_graph/sql/parent_serving.py
  tests/fixtures/query_graph/test_parent_serving/snapshots_table_lookup.sql
  tests/integration/api/test_serving_parent_features.py
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/test_parent_serving.py
Labels: Skip Changelog

#3104 [DEV-4149] Add support for joining SnapshotsView with other view types
  featurebyte/api/snapshots_view.py
  featurebyte/api/view.py
  featurebyte/enum.py
  featurebyte/query_graph/model/node_hash_util.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/sql/aggregator/base_lookup.py
  featurebyte/query_graph/sql/ast/join.py
  featurebyte/query_graph/sql/timestamp_helper.py
  tests/fixtures/query_graph/test_join/test_event_table_join_snapshots_table.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/basic_transform_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/basic_transform_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/basic_transform_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/basic_transform_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/no_transform_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/no_transform_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/no_transform_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/no_transform_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/timezone_column_name_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/timezone_column_name_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/timezone_column_name_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/timezone_column_name_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/timezone_column_offset_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/timezone_column_offset_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/timezone_column_offset_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/timezone_column_offset_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_feature_job_setting_day_blind_spot_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_feature_job_setting_day_blind_spot_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_feature_job_setting_day_blind_spot_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_feature_job_setting_day_blind_spot_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_format_string_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_format_string_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_format_string_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_format_string_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_original_timestamp_schema_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_original_timestamp_schema_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_original_timestamp_schema_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/apply_snapshots_datetime_transform/with_original_timestamp_schema_spark.sql
  tests/fixtures/request_payloads/feature_item_event.json
  tests/integration/api/test_snapshots_view_operations.py
  tests/integration/backward_compatibility/test_get_route.py
  tests/integration/conftest.py
  tests/unit/api/test_item_view.py
  tests/unit/api/test_scd_view.py
  tests/unit/api/test_snapshots_view.py
  tests/unit/api/test_view.py
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/sql/test_timestamp_handler.py
  tests/unit/query_graph/test_definition.py
  tests/unit/query_graph/test_graph_pruning.py
  tests/unit/query_graph/test_join.py
Labels: Skip Changelog

#3100 Support specifying context / use case during observation table creation
  .changelog/DEV-4146.yaml
  featurebyte/api/observation_table.py
  featurebyte/api/source_table.py
  featurebyte/api/view.py
  featurebyte/schema/observation_table.py
  featurebyte/schema/worker/task/observation_table.py
  featurebyte/schema/worker/task/observation_table_upload.py
  featurebyte/service/observation_table.py
  featurebyte/worker/task/observation_table.py
  featurebyte/worker/task/observation_table_upload.py
  tests/fixtures/request_payloads/observation_table.json
  tests/unit/api/test_observation_table.py
  tests/unit/routes/test_observation_table.py
  tests/unit/test_generate_payload_fixtures.py
Labels: documentation
