Repository featurebyte/featurebyte, pull requests merged in 2025-07, with the labels that each got.

#3030 [DEV-4092] Limit partition column to only one per table
  featurebyte/schema/table.py
  tests/unit/api/test_event_table.py
Labels: Skip Changelog

#3035 [DEV-4101] Handle timestamp schema in PreviewService when sampling with range
  featurebyte/query_graph/model/dtype.py
  featurebyte/query_graph/sql/interpreter/preview.py
  tests/integration/api/test_view_sample.py
  tests/unit/query_graph/interpreter/conftest.py
  tests/unit/query_graph/interpreter/test_interpreter.py
Labels: Skip Changelog

#3033 [DEV-4100] Update PreviewService to use partition column filters
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/fixtures/preview_service/expected_describe_with_partition_column_filters.sql
  tests/fixtures/preview_service/expected_sample_with_partition_column_filters.sql
  tests/fixtures/preview_service/expected_value_counts_with_partition_column_filters.sql
  tests/unit/api/test_event_table.py
  tests/unit/conftest.py
  tests/unit/service/test_preview.py
Labels: Skip Changelog

#3041 [chore] fixing vuln packages
  poetry.lock
  pyproject.toml
Labels: dependencies

#3040 [DEV-4100] Update partition column filters to include only primary table
  featurebyte/service/preview.py
  tests/fixtures/preview_service/expected_scd_join_with_partition_column_filters.sql
  tests/unit/service/test_preview.py
Labels: Skip Changelog

#3051 [DEV-4102] Apply partition column filtering for batch features
  featurebyte/query_graph/sql/online_serving.py
  tests/fixtures/expected_get_online_features_partition_column_filters.sql
  tests/unit/conftest.py
  tests/unit/service/test_online_serving.py
Labels: Skip Changelog

#3054 [DEV-4103] Apply partition column filtering in scheduled tile sql
  .github/workflows/test.yaml
  featurebyte/query_graph/sql/ast/input.py
  featurebyte/query_graph/sql/common.py
  featurebyte/query_graph/sql/partition_filter.py
  tests/fixtures/expected_tile_sql_scheduled_partition_column_filters.sql
  tests/integration/api/test_view_sample.py
  tests/integration/service/test_tile_task_executor.py
  tests/unit/query_graph/sql/test_tile.py
Labels: Skip Changelog

#3055 [DEV-4106] Use string timestamp filtering for event tables tile computation
  featurebyte/query_graph/sql/ast/input.py
  featurebyte/query_graph/sql/common.py
  featurebyte/query_graph/sql/entity_filter.py
  featurebyte/query_graph/sql/partition_filter.py
  featurebyte/query_graph/sql/partition_filter_helper.py
  tests/fixtures/expected_tile_sql_on_demand_event_timestamp_schema.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2d_bigquery.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2d_databricks_unity.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2d_snowflake.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2m_bigquery.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2m_databricks_unity.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2m_snowflake.sql
  tests/unit/query_graph/sql/test_partition_filter.py
  tests/unit/query_graph/sql/test_partition_filter_helper.py
Labels: Skip Changelog

#3056 [DEV-4102] Reduce partition column filter buffer size for historical and batch features
  featurebyte/query_graph/sql/partition_filter_helper.py
  tests/fixtures/expected_get_online_features_partition_column_filters.sql
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/sql/test_partition_filter_helper.py
Labels: Skip Changelog

#3057 [FIX] adding missing aiofiles dependency (#3031)
  poetry.lock
  pyproject.toml
Labels: dependencies, Skip Changelog

#3058 [RELEASE] Releasing featurebyte 3.1.1
  .changelog/DEV-4092.yaml
  .changelog/DEV-4105.yaml
  .changelog/DEV-4107.yaml
  CHANGELOG.md
  pyproject.toml
Labels: Skip Changelog

#3060 [chore][release] yanking 3.1.1 releasing 3.1.2
  CHANGELOG.md
  pyproject.toml
Labels: documentation, dependencies, Skip Changelog

#3063 [DEV-4115] Support partition column filtering in entity universe
  featurebyte/models/entity_universe.py
  featurebyte/query_graph/sql/common.py
  featurebyte/query_graph/sql/online_serving.py
  featurebyte/query_graph/sql/partition_filter.py
  featurebyte/query_graph/sql/partition_filter_helper.py
  featurebyte/service/historical_features_and_target.py
  featurebyte/service/preview.py
  scripts/enforce_import_rules.py
  tests/fixtures/entity_universe/ts_window_aggregate_bigquery.sql
  tests/fixtures/entity_universe/ts_window_aggregate_databricks_unity.sql
  tests/fixtures/entity_universe/ts_window_aggregate_snowflake.sql
  tests/fixtures/entity_universe/ts_window_aggregate_spark.sql
  tests/fixtures/expected_get_online_features_partition_column_filters.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2d_bigquery.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2d_databricks_unity.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2d_snowflake.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2m_bigquery.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2m_databricks_unity.sql
  tests/fixtures/query_graph/test_partition_filter/varchar_2m_snowflake.sql
  tests/unit/query_graph/sql/ast/test_input.py
  tests/unit/query_graph/sql/test_partition_filter.py
  tests/unit/query_graph/sql/test_partition_filter_helper.py
  tests/unit/query_graph/sql/test_tile.py
  tests/unit/query_graph/test_feature_historical.py
Labels: Skip Changelog

#3067 [DEV-4091] Implement flow to update target namespace `positive_label`
  featurebyte/enum.py
  featurebyte/models/target_namespace.py
  featurebyte/routes/registry.py
  featurebyte/routes/target_namespace/api.py
  featurebyte/routes/target_namespace/controller.py
  featurebyte/schema/target_namespace.py
  featurebyte/schema/worker/task/target_namespace_classification_metadata_update.py
  featurebyte/service/target_namespace.py
  featurebyte/worker/registry.py
  featurebyte/worker/task/observation_table.py
  featurebyte/worker/task/target_namespace_classification_metadata_update.py
  featurebyte/worker/task/target_table.py
  tests/integration/api/fixtures/observation_table_time_interval.csv
  tests/integration/api/test_observation_table.py
  tests/unit/routes/test_observation_table.py
  tests/unit/routes/test_target.py
Labels: Skip Changelog

#3074 [DEV-4129] Use temp tile tables by default when computing batch features
  .changelog/DEV-4129.yaml
  featurebyte/api/deployment.py
  featurebyte/schema/batch_feature_table.py
  tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_existing_databricks_table_queries.sql
  tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_existing_table_queries.sql
  tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_new_databricks_table_queries.sql
  tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_new_table_queries.sql
  tests/fixtures/request_payloads/batch_feature_table.json
  tests/fixtures/request_payloads/batch_feature_table_with_request_input.json
  tests/integration/query_graph/test_online_serving.py
  tests/unit/api/test_batch_feature_table.py
Labels: documentation
