Repository featurebyte/featurebyte, pull requests merged in 2025-05, with the labels that each got.

#2961 [chore] Bump databricks sql connector to latest version
  poetry.lock
  pyproject.toml
Labels: dependencies

#2969 [DEV-4055] Reduce number of CTEs in time series feature queries
  featurebyte/common/string.py
  featurebyte/models/feature_query_set.py
  featurebyte/query_graph/sql/aggregator/base.py
  featurebyte/query_graph/sql/aggregator/base_asat.py
  featurebyte/query_graph/sql/aggregator/base_lookup.py
  featurebyte/query_graph/sql/aggregator/forward.py
  featurebyte/query_graph/sql/aggregator/item.py
  featurebyte/query_graph/sql/aggregator/latest.py
  featurebyte/query_graph/sql/aggregator/non_tile_window.py
  featurebyte/query_graph/sql/aggregator/request_table.py
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  featurebyte/query_graph/sql/aggregator/window.py
  featurebyte/query_graph/sql/batch_helper.py
  featurebyte/query_graph/sql/feature_compute.py
  featurebyte/query_graph/sql/feature_historical.py
  featurebyte/query_graph/sql/feature_preview.py
  featurebyte/query_graph/sql/online_serving.py
  featurebyte/query_graph/sql/online_store_compute_query.py
  featurebyte/query_graph/sql/tile_compute.py
  featurebyte/service/feature_preview.py
  featurebyte/session/session_helper.py
  tests/fixtures/expected_feature_query_plan.sql
  tests/integration/api/test_historical_features.py
  tests/unit/conftest.py
  tests/unit/query_graph/test_asat_aggregator.py
  tests/unit/query_graph/test_feature_compute.py
  tests/unit/query_graph/test_feature_historical.py
  tests/unit/query_graph/test_item_aggregator.py
  tests/unit/query_graph/test_non_tile_window_aggregator.py
  tests/unit/query_graph/test_online_serving.py
  tests/unit/query_graph/util.py
  tests/unit/routes/test_historical_feature_table.py
  tests/unit/service/test_historical_features.py
  tests/util/helper.py
Labels: Skip Changelog

#2970 [DEV-4055] Update online serving to use queries with reduced CTEs
  featurebyte/query_graph/sql/feature_compute.py
  featurebyte/query_graph/sql/online_serving.py
Labels: Skip Changelog

#2973 [DEV-4056] Determine appropriate join methods using column statistics in time series
  featurebyte/models/column_statistics.py
  featurebyte/query_graph/sql/feature_compute.py
  featurebyte/query_graph/sql/feature_historical.py
  featurebyte/query_graph/sql/feature_preview.py
  featurebyte/query_graph/sql/specifications/base_aggregate_asat.py
  featurebyte/query_graph/sql/specifications/lookup.py
  featurebyte/query_graph/sql/specifications/lookup_target.py
  featurebyte/query_graph/sql/specifications/non_tile_window_aggregate.py
  featurebyte/query_graph/sql/specifications/time_series_window_aggregate.py
  featurebyte/query_graph/sql/specs.py
  featurebyte/routes/registry.py
  featurebyte/service/base_table_validation.py
  featurebyte/service/column_statistics.py
  featurebyte/service/feature_preview.py
  featurebyte/service/feature_table_cache.py
  featurebyte/service/historical_features.py
  featurebyte/service/historical_features_and_target.py
  featurebyte/service/time_series_table_validation.py
  tests/fixtures/time_series_table_validation_service/validate_and_update.sql
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/test_feature_preview.py
  tests/unit/query_graph/test_time_series_window_aggregator.py
  tests/unit/service/conftest.py
  tests/unit/service/test_base_table_validation.py
  tests/unit/service/test_column_statistics.py
  tests/unit/service/test_historical_features.py
  tests/unit/service/test_time_series_table_validation.py
  tests/unit/worker/task/test_catalog_cleanup.py
Labels: Skip Changelog

#2980 [DEV-4060] Add DeployedTileTable model and services
  featurebyte/models/deployed_tile_table.py
  featurebyte/routes/registry.py
  featurebyte/service/deploy.py
  featurebyte/service/deployed_tile_table.py
  featurebyte/service/deployed_tile_table_manager.py
  featurebyte/service/feature.py
  tests/fixtures/deployed_tile_table/expected_tile_sql_1.sql
  tests/fixtures/deployed_tile_table/expected_tile_sql_2.sql
  tests/unit/conftest.py
  tests/unit/service/test_deployed_tile_table.py
  tests/unit/service/test_deployed_tile_table_manager.py
  tests/unit/worker/task/test_catalog_cleanup.py
Labels: Skip Changelog

#2985 [DEV-4067] Serialize timestamp tz tuple as json string in all source types
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  tests/fixtures/query_graph/test_datetime_diff/timestamp_tuple_schema_bigquery.sql
  tests/fixtures/query_graph/test_datetime_diff/timestamp_tuple_schema_databricks_unity.sql
  tests/fixtures/query_graph/test_datetime_diff/timestamp_tuple_schema_snowflake.sql
  tests/fixtures/query_graph/test_datetime_diff/timestamp_tuple_schema_spark.sql
  tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_bigquery.sql
  tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_databricks_unity.sql
  tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_snowflake.sql
  tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_spark.sql
  tests/fixtures/query_graph/test_zip_timestamp/zip_timestamp_bigquery.sql
  tests/fixtures/query_graph/test_zip_timestamp/zip_timestamp_databricks_unity.sql
  tests/fixtures/query_graph/test_zip_timestamp/zip_timestamp_snowflake.sql
  tests/fixtures/query_graph/test_zip_timestamp/zip_timestamp_spark.sql
  tests/unit/query_graph/sql/adapter/test_snowflake.py
Labels: Skip Changelog

#2984 [chore] Revise ODFV when handling `TIMESTAMP_TZ_TUPLE`
  featurebyte/feast/enum.py
  featurebyte/models/feature.py
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/node/metadata/config.py
  featurebyte/query_graph/node/nested.py
  featurebyte/query_graph/node/request.py
  featurebyte/query_graph/node/utils.py
  featurebyte/query_graph/transform/null_filling_value.py
  featurebyte/query_graph/transform/offline_store_ingest.py
  featurebyte/service/feature_offline_store_info.py
  featurebyte/service/feature_table_cache.py
  tests/fixtures/on_demand_function/req_col_ttl_and_non_ttl.sql
  tests/fixtures/sdk_code/feature_with_request_column.py
  tests/integration/api/test_datetime.py
  tests/integration/api/test_event_view_operations.py
  tests/unit/api/test_databricks.py
  tests/unit/api/test_datetime_operations.py
  tests/unit/api/test_offline_ingest_query_graph.py
  tests/unit/api/test_request_column.py
  tests/unit/feast/utils/test_registry_construction.py
  tests/unit/query_graph/on_demand_function/test_date.py
  tests/unit/query_graph/test_nested_node.py
  tests/unit/query_graph/test_request_column_node.py
  tests/unit/service/test_offline_feature_store_comment.py
Labels: Skip Changelog

#2983 [DEV-4061] Update deployment enabling and disabling to use DeployedTileTable
  featurebyte/models/deployed_tile_table.py
  featurebyte/models/online_store_compute_query.py
  featurebyte/models/tile.py
  featurebyte/query_graph/sql/online_serving.py
  featurebyte/query_graph/sql/online_store_compute_query.py
  featurebyte/service/deploy.py
  featurebyte/service/deployed_tile_table.py
  featurebyte/service/deployed_tile_table_manager.py
  featurebyte/service/feature_manager.py
  featurebyte/service/feature_materialize.py
  featurebyte/service/feature_materialize_prerequisite.py
  featurebyte/service/feature_materialize_sync.py
  featurebyte/service/offline_store_feature_table.py
  featurebyte/service/online_serving.py
  featurebyte/service/online_store_compute_query_service.py
  featurebyte/service/tile/tile_task_executor.py
  featurebyte/service/tile_manager.py
  featurebyte/service/working_schema.py
  featurebyte/sql/tile_generate.py
  featurebyte/sql/tile_schedule_online_store.py
  tests/fixtures/feature_manager/enable_new_feature.sql
  tests/fixtures/feature_manager/enable_new_feature_offset.sql
  tests/fixtures/feature_manager/enable_second_feature_later_date.sql
  tests/fixtures/feature_manager/enable_second_feature_much_later_date.sql
  tests/fixtures/feature_manager/enable_with_backfill_metadata.sql
  tests/fixtures/feature_manager/enable_with_required_tiles_available.sql
  tests/fixtures/feature_manager/enable_without_last_run_metadata.sql
  tests/integration/conftest.py
  tests/integration/feature_manager/test_feature_manager.py
  tests/integration/tile/test_generate_tile.py
  tests/integration/tile/test_schedule_feature_store.py
  tests/integration/tile/test_tile_manager.py
  tests/integration/tile/test_tile_scheduler.py
  tests/unit/conftest.py
  tests/unit/feature_manager/test_unit_snowflake_feature.py
  tests/unit/service/test_deployed_tile_table.py
  tests/unit/service/test_deployed_tile_table_manager.py
  tests/unit/service/test_feature_manager.py
  tests/unit/service/test_feature_materialize_prerequisite.py
  tests/unit/service/test_feature_materialize_sync.py
  tests/unit/service/test_offline_store_feature_table.py
  tests/unit/service/test_online_store_compute_query.py
  tests/unit/service/test_tile_manager.py
  tests/unit/tile/test_unit_snowflake_tile.py
Labels: Skip Changelog

#2860 [DEV-4002] Disable online feature serving if online store is not configured for the catalog
  .changelog/DEV-4002.yaml
  docs/notebooks/deep dive materializing features - final.ipynb
  docs/notebooks/quick start end-to-end workflow - final.ipynb
  docs/notebooks/quick start feature engineering - final.ipynb
  featurebyte/api/deployment.py
  featurebyte/config.py
  featurebyte/exception.py
  featurebyte/routes/deployment/controller.py
  featurebyte/service/online_serving.py
  tests/unit/api/test_deployment.py
  tests/unit/routes/test_deployment.py
  tests/unit/service/test_online_serving.py
Labels: documentation
