Repository featurebyte/featurebyte, pull requests merged in 2025-04, with the labels that each got.

#2902 [RELEASE] releasing 3.0 altering changelogs
  .changelog/DEV-3998.yaml
  .changelog/DEV-3999.yaml
  .changelog/DEV-4000-1.yaml
  .changelog/DEV-4000.yaml
  .changelog/DEV-4011.yaml
  .changelog/DEV-4016.yaml
  .changelog/DEV-4017.yaml
  .changelog/DEV-4020.yaml
  .changelog/DEV-4022.yaml
  .changelog/DEV-4024.yaml
  .changelog/DEV-4025.yaml
  CHANGELOG.md
Labels: Skip Changelog

#2901 [chore] Revise table sampling logic to cache sampled primary table
  featurebyte/query_graph/node/input.py
  featurebyte/query_graph/sql/ast/input.py
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  featurebyte/session/base.py
  tests/fixtures/query_graph/expected_filtered_table_primary_table_sampled_data.sql
  tests/fixtures/query_graph/expected_item_table_join_event_table_primary_table_sampled_data.sql
  tests/fixtures/query_graph/expected_primary_table_sampled_data.sql
  tests/unit/query_graph/interpreter/test_preview.py
  tests/unit/session/test_base.py
Labels: documentation, Skip Changelog

#2905 [DEV-4033] Remove group_name from DataBricks Unity feature store
  .changelog/DEV-4033.yaml
  featurebyte/feast/infra/offline_stores/databricks.py
  featurebyte/query_graph/node/schema.py
  featurebyte/service/feature_manager.py
  featurebyte/session/databricks_unity.py
  tests/integration/conftest.py
Labels: documentation

#2903 [DEV-4029] Support blind spot for calendar aggregation
  .changelog/DEV-4029.yaml
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  featurebyte/query_graph/sql/cron.py
  featurebyte/query_graph/sql/specifications/time_series_window_aggregate.py
  tests/fixtures/aggregator/expected_time_series_window_aggregator_blind_spot.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day_with_offset.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_grouped.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_is_utc_time.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_latest.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_mixed_order_dependency.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month_with_offset.sql
  tests/fixtures/expected_preview_time_series_window_aggregate.sql
  tests/fixtures/sdk_code/ts_window_aggregate_feature.py
  tests/integration/api/test_time_series_view_operations.py
  tests/unit/api/test_event_view.py
  tests/unit/api/test_time_series_table.py
  tests/unit/api/test_timestamp_timezone_tuple.py
  tests/unit/conftest.py
  tests/unit/query_graph/model/test_feature_job_setting.py
  tests/unit/query_graph/test_time_series_window_aggregator.py
  tests/unit/service/test_version.py
Labels: documentation

#2908 [DEV-4034] Add to_timestamp_from_epoch function to convert epoch time to timestamp
  .changelog/DEV-4034.yaml
  featurebyte/__init__.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/common/documentation/gen_ref_pages_docs_builder.py
  featurebyte/core/datetime.py
  featurebyte/query_graph/enum.py
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  featurebyte/query_graph/sql/ast/datetime.py
  tests/fixtures/api/test_datetime_operations/to_timestamp_from_epoch.sql
  tests/integration/api/test_datetime.py
  tests/unit/api/test_datetime_operations.py
Labels: documentation

#2919 [chore] Fix pyarrow conversion for decimal in databricks
  featurebyte/core/accessor/datetime.py
  featurebyte/session/base_spark.py
  featurebyte/session/databricks.py
  featurebyte/session/spark.py
  tests/integration/session/test_databricks_unity.py
Labels: documentation

#2927 [chore] Fix feature type detection for non-embedding arrays
  featurebyte/enum.py
  tests/unit/service/test_feature_type.py
Labels: documentation

#2925 [DEV-4301] Exact match via distinct snapshot dates for time series aggregation
  featurebyte/enum.py
  featurebyte/query_graph/model/timestamp_schema.py
  featurebyte/query_graph/sql/aggregator/range_join.py
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  featurebyte/query_graph/sql/specifications/time_series_window_aggregate.py
  tests/fixtures/aggregator/expected_time_series_window_aggregator_blind_spot.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day_with_offset.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_grouped.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_is_utc_time.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_latest.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_mixed_order_dependency.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month_with_offset.sql
  tests/fixtures/expected_preview_time_series_window_aggregate.sql
Labels: Skip Changelog

#2929 [DEV-4045] Fix potential columns limit exceeded error when updating feature table cache
  featurebyte/service/feature_table_cache.py
Labels: Skip Changelog

#2935 [DEV-4035]Fix on-demand feature view code generation (cherry-pick)
  featurebyte/enum.py
  featurebyte/models/offline_store_ingest_query.py
  featurebyte/query_graph/node/base.py
  featurebyte/query_graph/node/binary.py
  featurebyte/query_graph/node/count_dict.py
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/node/distance.py
  featurebyte/query_graph/node/function.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/node/input.py
  featurebyte/query_graph/node/metadata/config.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  featurebyte/query_graph/node/nested.py
  featurebyte/query_graph/node/request.py
  featurebyte/query_graph/node/string.py
  featurebyte/query_graph/node/vector.py
  featurebyte/query_graph/transform/null_filling_value.py
  featurebyte/query_graph/transform/on_demand_function.py
  featurebyte/query_graph/transform/on_demand_view.py
  featurebyte/query_graph/transform/sdk_code.py
  featurebyte/service/feature_offline_store_info.py
  featurebyte/session/time_formatter.py
  scripts/enforce_import_rules.py
  tests/fixtures/on_demand_function/req_col_ttl_and_non_ttl.sql
  tests/integration/api/test_datetime.py
  tests/integration/conftest.py
  tests/integration/session/test_time_formatter.py
  tests/unit/api/test_datetime_operations.py
  tests/unit/api/test_offline_ingest_query_graph.py
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/on_demand_function/conftest.py
  tests/unit/query_graph/on_demand_function/test_binary.py
  tests/unit/query_graph/on_demand_function/test_count_dict.py
  tests/unit/query_graph/on_demand_function/test_date.py
  tests/unit/query_graph/on_demand_function/test_distance.py
  tests/unit/query_graph/on_demand_function/test_generic.py
  tests/unit/query_graph/on_demand_function/test_string.py
  tests/unit/query_graph/on_demand_function/test_unary.py
  tests/unit/query_graph/on_demand_function/test_vector.py
  tests/unit/query_graph/test_sdk_code_generation.py
  tests/unit/query_graph/util.py
  tests/unit/service/test_offline_store_feature_table_manager.py
  tests/util/deployment.py
Labels: port/backport

#2937 [DEV-4301] Fallback to range join for time series aggregation on event tables
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  featurebyte/query_graph/sql/specifications/time_series_window_aggregate.py
  tests/fixtures/aggregator/expected_time_series_window_aggregator_blind_spot.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day_with_offset.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_event_table.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_grouped.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_is_utc_time.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_latest.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_mixed_order_dependency.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month_with_offset.sql
  tests/fixtures/expected_preview_time_series_window_aggregate.sql
  tests/unit/query_graph/test_time_series_window_aggregator.py
Labels: Skip Changelog

#2938 [chore] Clean up dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#2946 [chore] Remove oversampling logic for join & filter (cherry-pick)
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
Labels: port/backport

#2948 [chore] Fix row count for sample & describe operation (cherry-pick)
  featurebyte/service/preview.py
  tests/unit/service/test_preview.py
Labels: port/backport

#2941 [DEV-4045] Check actual number of cached columns in cache table
  featurebyte/service/feature_table_cache.py
  featurebyte/service/feature_table_cache_metadata.py
  tests/unit/service/test_feature_table_cache.py
  tests/unit/service/test_feature_table_cache_metadata.py
Labels: Skip Changelog

#2951 [chore] Fix Crontab comparison to avoid duplicate table name (cherry-pick)
  featurebyte/models/periodic_task.py
  featurebyte/query_graph/sql/cron.py
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/model/test_feature_job_setting.py
  tests/unit/query_graph/sql/test_cron.py
Labels: port/backport

#2953 [DEV-4049] Cast columns to double before std computation
  featurebyte/query_graph/sql/tiling.py
  tests/unit/query_graph/test_tiling.py
Labels: Skip Changelog

#2955 [DEV-4050] Apply timestamp schema in non-tile-based count distinct aggregation
  featurebyte/models/entity_universe.py
  featurebyte/query_graph/sql/aggregator/non_tile_window.py
  tests/integration/api/test_event_view_operations.py
Labels: Skip Changelog

#2956 [DEV-4050] Apply timestamp schema in non-tile-based count distinct aggregation (cherry-pick)
  featurebyte/models/entity_universe.py
  featurebyte/query_graph/sql/aggregator/non_tile_window.py
  tests/integration/api/test_event_view_operations.py
Labels: port/backport

#2957 [chore] Cherry-pick fixes
  featurebyte/query_graph/sql/tiling.py
  featurebyte/service/feature_table_cache.py
  tests/unit/query_graph/test_tiling.py
Labels: port/backport
