Repository featurebyte/featurebyte, pull requests merged in 2025-03, with the labels that each got.

#2854 [DEV-3993] Add SCD end timestamp handling only when the column is available
  featurebyte/query_graph/sql/scd_helper.py
  tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
  tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
  tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
  tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table.sql
  tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table_missing_column.sql
  tests/fixtures/feature_materialize/materialize_features_queries_internal_relationships.sql
  tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
  tests/fixtures/offline_store_feature_table/cust_id_to_gender_universe.sql
  tests/integration/api/test_scd_view_operations.py
Labels: Skip Changelog

#2852 [DEV-3995] Support calendar aggregation for event tables
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/api/groupby.py
  featurebyte/models/entity_universe.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  tests/integration/api/test_event_view_operations.py
  tests/unit/api/test_aggregate_over.py
Labels: documentation, Skip Changelog

#2857 [DEV-4000] bumping snowflake-connector-python to fix cryptography vuln
  .changelog/DEV-4000-1.yaml
  .changelog/DEV-4000.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies

#2859 [DEV-3998] Support timestamp schema for event timestamp column
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/api/event_table.py
  featurebyte/api/event_view.py
  featurebyte/api/source_table.py
  featurebyte/models/entity_universe.py
  featurebyte/models/event_table.py
  featurebyte/query_graph/model/table.py
  featurebyte/query_graph/sql/ast/input.py
  featurebyte/query_graph/sql/ast/tile.py
  featurebyte/query_graph/sql/common.py
  featurebyte/query_graph/sql/entity_filter.py
  featurebyte/query_graph/sql/interpreter/tile.py
  featurebyte/query_graph/sql/tile_compute_spec.py
  featurebyte/schema/event_table.py
  tests/fixtures/request_payloads/event_table.json
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_scd_view_operations.py
  tests/integration/conftest.py
  tests/integration/feature_store_integration/test_feature_materialize.py
  tests/integration/query_graph/test_timestamp_handler.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_event_view.py
  tests/unit/conftest.py
  tests/unit/models/test_event_table.py
Labels: documentation, Skip Changelog

#2858 [DEV-4001] Make `fill_value` mandatory for `forward_aggregate` & `forward_aggregate_asat`
  .changelog/DEV-4001.yaml
  featurebyte/api/groupby.py
  featurebyte/enum.py
  featurebyte/query_graph/model/column_info.py
  featurebyte/query_graph/node/generic.py
  featurebyte/typing.py
  scripts/test-docs-setup.py
  tests/fixtures/request_payloads/target.json
  tests/fixtures/sdk_code/add_timestamp_schema.py
  tests/fixtures/sdk_code/forward_aggregate_asat_target_code_generation.py
  tests/fixtures/sdk_code/forward_aggregate_target_code_generation.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_feature_correctness.py
  tests/integration/api/test_forward_aggregate_asat.py
  tests/integration/api/test_target_correctness.py
  tests/unit/api/aggregator/test_forward_aggregator.py
  tests/unit/api/test_aggregate_asat_common.py
  tests/unit/api/test_databricks.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_forward_aggregate_asat.py
  tests/unit/api/test_sdk_code.py
  tests/unit/api/test_target.py
  tests/unit/conftest.py
  tests/unit/routes/test_target.py
  tests/unit/service/test_feature_table_cache.py
  tests/unit/service/test_info.py
Labels: documentation

#2849 [chore] Fix batch feature table recreate fails when parent table is deleted
  featurebyte/models/batch_feature_table.py
  featurebyte/routes/batch_feature_table/controller.py
  featurebyte/schema/worker/task/batch_feature_table.py
  featurebyte/service/batch_feature_table.py
  featurebyte/worker/task/batch_feature_table.py
  tests/unit/routes/test_batch_feature_table.py
Labels: documentation

#2863 [DEV-4001] Introduce `fill_value` to `as_target` and `as_feature` methods
  .changelog/DEV-4001.yaml
  featurebyte/api/groupby.py
  featurebyte/api/view.py
  featurebyte/enum.py
  featurebyte/exception.py
  featurebyte/query_graph/node/generic.py
  tests/fixtures/sdk_code/lookup_target_code_generation.py
  tests/fixtures/sdk_code/target_scd_lookup.py
  tests/integration/api/test_lookup_target_operations.py
  tests/integration/session/test_databricks_unity.py
  tests/unit/api/aggregator/test_forward_aggregator.py
  tests/unit/api/test_databricks.py
  tests/unit/api/test_dimension_view.py
  tests/unit/api/test_sdk_code.py
  tests/unit/api/test_target.py
  tests/unit/models/test_target.py
  tests/unit/query_graph/test_sdk_code_generation.py
Labels: documentation

#2866 [chore] Fix documentation changes due to UNSET
  featurebyte/typing.py
Labels: documentation

#2865 [DEV-4008] Implement vector aggregation functions in databricks_unity
  featurebyte/query_graph/sql/adapter/__init__.py
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/databricks_unity.py
  featurebyte/query_graph/sql/groupby_helper.py
  featurebyte/query_graph/sql/tiling.py
  tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_avg.sql
  tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_max.sql
  tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_simple_average.sql
  tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_sum.sql
  tests/integration/api/test_vector_aggregation_operations.py
  tests/unit/query_graph/sql/adapter/test_databricks_unity.py
Labels: documentation, Skip Changelog

#2867 [DEV-4009] Implement vector cosine similarity UDF for DataBricks and BigQuery
  featurebyte/session/bigquery.py
  featurebyte/session/databricks_unity.py
  featurebyte/sql/bigquery/F_VECTOR_COSINE_SIMILARITY.sql
  featurebyte/sql/databricks_unity/F_VECTOR_COSINE_SIMILARITY.sql
  tests/integration/api/test_vector_aggregation_operations.py
  tests/integration/udf/conftest.py
  tests/integration/udf/test_vector_aggregate.py
  tests/integration/udf/test_vector_cosine_similarity.py
  tests/unit/session/test_bigquery_session.py
Labels: Skip Changelog

#2868 [DEV-4013] Enable bigquery source type in test_vector_aggregation_operations.py
  featurebyte/session/bigquery.py
  tests/integration/api/test_vector_aggregation_operations.py
Labels: Skip Changelog

#2871 [DEV-4015] Implement conversion from CronFeatureJobSetting to FeatureJobSetting
  featurebyte/exception.py
  featurebyte/query_graph/model/feature_job_setting.py
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day_with_offset.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_is_utc_time.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_latest.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_mixed_order_dependency.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month_with_offset.sql
  tests/fixtures/expected_preview_time_series_window_aggregate.sql
  tests/unit/api/test_aggregate_over.py
  tests/unit/api/test_time_series_table.py
  tests/unit/models/test_time_series_table.py
  tests/unit/query_graph/model/test_feature_job_setting.py
  tests/unit/routes/test_time_series_table.py
Labels: documentation, Skip Changelog

#2875 [DEV-3999] Support cron based default feature job setting for EventTable
  .changelog/DEV-3999.yaml
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/api/event_table.py
  featurebyte/api/event_view.py
  featurebyte/api/item_table.py
  featurebyte/api/item_view.py
  featurebyte/exception.py
  featurebyte/models/event_table.py
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/model/graph.py
  featurebyte/query_graph/model/node_hash_util.py
  featurebyte/query_graph/node/generic.py
  featurebyte/schema/event_table.py
  featurebyte/service/event_table.py
  tests/unit/api/conftest.py
  tests/unit/api/test_aggregate_over.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_event_view.py
  tests/unit/api/test_item_view.py
  tests/unit/query_graph/model/test_feature_job_setting.py
Labels: documentation

#2881 [DEV-4019] Fix EventTable.info() for cron based default feature job setting
  featurebyte/schema/info.py
  tests/unit/api/test_event_table.py
Labels: Skip Changelog

#2882 [DEV-4018] Handle cron job setting in create_new_feature_version_using_source_settings
  featurebyte/service/version.py
  tests/unit/conftest.py
  tests/unit/service/test_version.py
Labels: Skip Changelog

#2885 [chore] Replace aiobotocore3 with aioboto3
  featurebyte/storage/s3.py
  featurebyte/utils/storage.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#2884 [DEV-4016] Add `feature_type` to feature namespace
  .changelog/DEV-4016.yaml
  featurebyte/api/feature.py
  featurebyte/api/feature_namespace.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/enum.py
  featurebyte/migration/service/feature_namespace.py
  featurebyte/models/feature_namespace.py
  featurebyte/routes/feature_namespace/controller.py
  featurebyte/routes/registry.py
  featurebyte/schema/feature_namespace.py
  featurebyte/schema/info.py
  featurebyte/service/feature_facade.py
  featurebyte/service/feature_type.py
  tests/fixtures/migration/feature_namespace
  tests/unit/api/test_feature.py
  tests/unit/models/test_feature.py
  tests/unit/routes/test_feature.py
  tests/unit/routes/test_feature_namespace.py
  tests/unit/service/test_feature_type.py
  tests/unit/service/test_info.py
Labels: documentation

#2888 [DEV-4016] Add `features_metadata` to feature list model to track `feature_type`
  featurebyte/migration/service/feature_list.py
  featurebyte/models/feature_list.py
  featurebyte/routes/registry.py
  featurebyte/service/feature_list.py
  featurebyte/service/version.py
  tests/fixtures/migration/feature_namespace
  tests/unit/api/test_feature_list.py
  tests/unit/models/test_feature_list.py
Labels: Skip Changelog

#2892 [DEV-4023] Validate table after critical data info update
  featurebyte/core/timedelta.py
  featurebyte/routes/common/base_table.py
  featurebyte/service/base_table_validation.py
  tests/integration/api/test_item_view_operations.py
  tests/unit/service/test_base_table_validation.py
Labels: documentation, Skip Changelog
