Repository featurebyte/featurebyte, pull requests merged in 2025-02, with the labels that each got.

#2803 [DEV-3962] Fix cron feature job setting scheduled job bug
  featurebyte/exception.py
  featurebyte/models/periodic_task.py
  featurebyte/service/cron_helper.py
  featurebyte/service/feature_materialize_sync.py
  featurebyte/service/task_manager.py
  tests/unit/service/test_cron_helper.py
  tests/unit/service/test_task_manager.py
Labels: Skip Changelog

#2806 [chore] Revise credential deletion logic
  featurebyte/routes/credential/api.py
  featurebyte/routes/credential/controller.py
  tests/unit/api/test_credential.py
  tests/unit/routes/base.py
  tests/unit/routes/test_credential.py
Labels: Skip Changelog

#2808 [DEV-3974] Introduce `target_type` to target object
  .changelog/DEV-3974.yaml
  featurebyte/__init__.py
  featurebyte/api/target.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/enum.py
  featurebyte/models/target.py
  featurebyte/routes/target/api.py
  featurebyte/routes/target/controller.py
  featurebyte/schema/target.py
  tests/unit/api/test_target.py
  tests/unit/routes/test_target.py
Labels: documentation

#2810 [chore] Minor revision on catalog cleanup task
  featurebyte/query_graph/node/input.py
  featurebyte/worker/task/catalog_cleanup.py
  tests/unit/query_graph/test_node.py
Labels: Skip Changelog

#2813 [chore] Fix activate catalog
  featurebyte/api/catalog.py
  featurebyte/config.py
  tests/unit/api/test_catalog.py
Labels: documentation

#2817 [DEV-3981] Fix entity relationship issue for time series table
  featurebyte/models/time_series_table.py
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/model/timestamp_schema.py
  tests/unit/api/base_table_test.py
  tests/unit/api/test_relationship.py
  tests/unit/api/test_time_series_table.py
Labels: documentation, Skip Changelog

#2819 [DEV-3983] Add return_exceptions option in run_coroutines
  featurebyte/session/session_helper.py
  featurebyte/utils/async_helper.py
  tests/unit/session/test_session_helper.py
Labels: Skip Changelog

#2820 [DEV-3974] Move `target_type` from `TargetModel` to `TargetNamespaceModel`
  featurebyte/api/aggregator/forward_aggregator.py
  featurebyte/api/aggregator/forward_asat_aggregator.py
  featurebyte/api/groupby.py
  featurebyte/api/target.py
  featurebyte/api/target_namespace.py
  featurebyte/api/view.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/common/validator.py
  featurebyte/enum.py
  featurebyte/models/target.py
  featurebyte/models/target_namespace.py
  featurebyte/routes/target/api.py
  featurebyte/routes/target/controller.py
  featurebyte/routes/target_namespace/api.py
  featurebyte/routes/target_namespace/controller.py
  featurebyte/schema/target.py
  featurebyte/schema/target_namespace.py
  featurebyte/service/target.py
  tests/fixtures/request_payloads/target.json
  tests/fixtures/request_payloads/target_namespace.json
  tests/unit/api/test_target.py
  tests/unit/api/test_target_namespace.py
  tests/unit/routes/test_target.py
  tests/unit/routes/test_target_namespace.py
  tests/unit/test_generate_payload_fixtures.py
Labels: documentation, Skip Changelog

#2825 [DEV-3970] Add route to recreate existing batch feature table
  featurebyte/exception.py
  featurebyte/models/batch_feature_table.py
  featurebyte/routes/batch_feature_table/api.py
  featurebyte/routes/batch_feature_table/controller.py
  featurebyte/schema/worker/task/batch_feature_table.py
  featurebyte/service/batch_feature_table.py
  featurebyte/worker/task/batch_feature_table.py
  tests/unit/routes/test_batch_feature_table.py
Labels: documentation, Skip Changelog

#2828 [DEV-3983] Implement dynamic batching when executing feature queries
  featurebyte/exception.py
  featurebyte/models/feature_query_set.py
  featurebyte/session/session_helper.py
  tests/fixtures/expected_feature_query_set.sql
  tests/fixtures/expected_feature_query_set_dynamic_batching.sql
  tests/fixtures/feature_materialize/initialize_new_columns_no_feature_columns.sql
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_historical_features.py
  tests/integration/conftest.py
  tests/unit/conftest.py
  tests/unit/models/test_feature_query_set.py
  tests/unit/session/test_session_helper.py
Labels: Skip Changelog

#2830 [DEV-3988] Implement dynamic batching for stats computation
  featurebyte/exception.py
  featurebyte/query_graph/sql/interpreter/preview.py
  featurebyte/service/preview.py
  tests/fixtures/preview_service/expected_describe_dynamic_batching_queries.sql
  tests/integration/api/test_view_describe.py
  tests/unit/conftest.py
  tests/unit/query_graph/interpreter/test_preview.py
  tests/unit/service/test_preview.py
Labels: Skip Changelog

#2834 [chore] Fix task submission record duplicate
  featurebyte/service/task_manager.py
Labels: bug

#2836 [DEV-3990] Fix ChangeView with timestamp schema error when joined with SCDView
  featurebyte/query_graph/node/generic.py
  tests/integration/api/test_change_view_operations.py
Labels: Skip Changelog

#2835 [DEV-3989] Introduce `AddTimestampSchema` cleaning operation
  featurebyte/__init__.py
  featurebyte/api/base_table.py
  featurebyte/api/feature.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/common/validator.py
  featurebyte/exception.py
  featurebyte/query_graph/enum.py
  featurebyte/query_graph/model/column_info.py
  featurebyte/query_graph/model/critical_data_info.py
  featurebyte/query_graph/node/cleaning_operation.py
  featurebyte/query_graph/node/input.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  featurebyte/query_graph/node/unary.py
  featurebyte/query_graph/sql/ast/unary.py
  featurebyte/service/table_columns_info.py
  tests/fixtures/sdk_code/add_timestamp_schema.py
  tests/integration/api/test_event_view_operations.py
  tests/integration/api/test_view_describe.py
  tests/integration/api/test_view_sample.py
  tests/integration/conftest.py
  tests/unit/api/test_event_table.py
  tests/unit/api/test_time_series_table.py
  tests/unit/query_graph/model/test_table_data.py
  tests/unit/query_graph/test_critical_data_info.py
  tests/unit/test_app.py
Labels: documentation, Skip Changelog

#2844 [chore] Reset semantic if add timestamp schema operation is added
  .changelog/DEV-3989.yaml
  featurebyte/query_graph/node/cleaning_operation.py
  featurebyte/routes/common/base_table.py
  tests/unit/api/test_event_table.py
Labels: documentation, Skip Changelog
