Repository featurebyte/featurebyte, pull requests merged in 2025-01, with the labels that each got.

#2734 [DEV-3924] Update feature job setting handling logic
  featurebyte/exception.py
  featurebyte/models/entity_lookup_feature_table.py
  featurebyte/models/offline_store_feature_table.py
  featurebyte/models/offline_store_ingest_query.py
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/node/nested.py
  featurebyte/query_graph/transform/decompose_point.py
  featurebyte/service/feature_materialize_scheduler.py
  featurebyte/service/feature_materialize_sync.py
  featurebyte/service/feature_offline_store_info.py
  featurebyte/service/offline_store_feature_table_comment.py
  featurebyte/service/offline_store_feature_table_construction.py
  featurebyte/service/version.py
  tests/unit/query_graph/test_feature_job_setting_extractor.py
  tests/unit/query_graph/transform/test_decompose_point.py
Labels: Skip Changelog

#2743 [DEV-3929] Implement sql generation for time series window aggregate
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/model/window.py
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  featurebyte/query_graph/sql/ast/aggregate.py
  featurebyte/query_graph/sql/cron.py
  featurebyte/query_graph/sql/feature_compute.py
  featurebyte/query_graph/sql/feature_historical.py
  featurebyte/query_graph/sql/specifications/time_series_window_aggregate.py
  featurebyte/query_graph/sql/specs.py
  featurebyte/service/cron_helper.py
  featurebyte/service/feature_table_cache.py
  featurebyte/service/historical_features.py
  featurebyte/service/historical_features_and_target.py
  tests/fixtures/aggregator/expected_non_tile_window_aggregator_day.sql
  tests/fixtures/aggregator/expected_non_tile_window_aggregator_day_with_offset.sql
  tests/fixtures/aggregator/expected_non_tile_window_aggregator_month.sql
  tests/fixtures/aggregator/expected_non_tile_window_aggregator_month_with_offset.sql
  tests/fixtures/expected_preview_time_series_window_aggregate.sql
  tests/unit/query_graph/test_extract_operation_structure.py
  tests/unit/query_graph/test_feature_preview.py
  tests/unit/query_graph/test_time_series_window_aggregator.py
  tests/unit/service/conftest.py
  tests/unit/service/test_historical_features.py
Labels: Skip Changelog

#2744 [DEV-3929] Handle quarter feature window unit
  featurebyte/query_graph/model/window.py
  tests/unit/query_graph/model/test_window.py
Labels: Skip Changelog

#2747 [DEV-3932] Support time series view in aggregate_over
  featurebyte/__init__.py
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/api/groupby.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  tests/integration/api/test_time_series_view_operations.py
  tests/unit/api/test_aggregate_over.py
  tests/unit/common/documentation/test_documentation_layout.py
  tests/unit/conftest.py
Labels: documentation, Skip Changelog

#2748 [DEV-3924] Minor update to support cron feature job setting
  featurebyte/query_graph/graph.py
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/node/generic.py
  tests/fixtures/sdk_code/ts_window_aggregate_feature.py
  tests/unit/api/test_sdk_code.py
  tests/unit/conftest.py
  tests/unit/query_graph/model/test_feature_job_setting.py
  tests/unit/service/test_version.py
Labels: Skip Changelog

#2749 [chore] Rename FeatureWindow to CalendarWindow
  featurebyte/__init__.py
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/api/groupby.py
  featurebyte/query_graph/model/window.py
  featurebyte/query_graph/node/generic.py
  featurebyte/query_graph/node/metadata/sdk_code.py
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  featurebyte/query_graph/sql/specifications/time_series_window_aggregate.py
  tests/fixtures/sdk_code/ts_window_aggregate_feature.py
  tests/integration/api/test_time_series_view_operations.py
  tests/unit/api/test_aggregate_over.py
  tests/unit/common/documentation/test_documentation_layout.py
  tests/unit/conftest.py
  tests/unit/query_graph/model/test_window.py
  tests/unit/query_graph/test_time_series_window_aggregator.py
Labels: documentation

#2751 [chore] Bumping vulnerable dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies, Skip Changelog

#2754 [chore] fxing bad publish message
  .github/workflows/publish-dev.yaml
Labels: bug, github_actions, Skip Changelog

#2755 [DEV-3945] Validate calendar window unit is compatible with time interval
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/enum.py
  tests/unit/api/test_aggregate_over.py
Labels: documentation, Skip Changelog

#2759 [DEV-3940] Add reference_timezone to time series table
  featurebyte/api/source_table.py
  featurebyte/api/time_series_table.py
  featurebyte/models/time_series_table.py
  featurebyte/query_graph/model/table.py
  featurebyte/query_graph/node/input.py
  featurebyte/schema/time_series_table.py
  tests/fixtures/request_payloads/time_series_table.json
  tests/fixtures/sdk_code/time_series_table.py
  tests/unit/api/test_time_series_table.py
  tests/unit/models/test_time_series_table.py
Labels: documentation, Skip Changelog

#2762 Revert "[DEV-3940] Add reference_timezone to time series table"
  featurebyte/api/source_table.py
  featurebyte/api/time_series_table.py
  featurebyte/models/time_series_table.py
  featurebyte/query_graph/model/table.py
  featurebyte/query_graph/node/input.py
  featurebyte/schema/time_series_table.py
  tests/fixtures/request_payloads/time_series_table.json
  tests/fixtures/sdk_code/time_series_table.py
  tests/unit/api/test_time_series_table.py
  tests/unit/models/test_time_series_table.py
Labels: documentation, Skip Changelog

#2764 [chore] Update SDK documentation
  featurebyte/__init__.py
  featurebyte/api/event_table.py
  featurebyte/api/groupby.py
  featurebyte/api/scd_table.py
  featurebyte/api/source_table.py
  featurebyte/api/time_series_table.py
  featurebyte/common/documentation/documentation_layout.py
  featurebyte/models/periodic_task.py
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/model/time_series_table.py
  featurebyte/query_graph/model/timestamp_schema.py
  featurebyte/query_graph/model/window.py
  tests/unit/common/documentation/test_documentation_layout.py
Labels: documentation

#2763 [DEV-3950] Handle timestamp schema in date_diff node
  featurebyte/core/series.py
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/sql/ast/datetime.py
  featurebyte/query_graph/sql/ast/generic.py
  tests/fixtures/api/test_datetime_operations/timestamp_diff_with_schema.sql
  tests/fixtures/request_payloads/time_series_table.json
  tests/fixtures/sdk_code/time_series_table.py
  tests/unit/api/conftest.py
  tests/unit/api/test_time_series_table.py
  tests/unit/api/test_time_series_view.py
  tests/unit/conftest.py
  tests/unit/query_graph/test_sql.py
  tests/unit/routes/test_time_series_table.py
Labels: Skip Changelog

#2768 [DEV-3944] Support deployment of time series window aggregate features
  featurebyte/models/entity_universe.py
  featurebyte/models/precomputed_lookup_feature_table.py
  featurebyte/models/sqlglot_expression.py
  featurebyte/query_graph/model/window.py
  featurebyte/query_graph/sql/adapter/base.py
  featurebyte/query_graph/sql/adapter/bigquery.py
  featurebyte/query_graph/sql/adapter/databricks.py
  featurebyte/query_graph/sql/adapter/snowflake.py
  featurebyte/query_graph/sql/online_serving.py
  featurebyte/query_graph/sql/timestamp_helper.py
  featurebyte/service/cron_helper.py
  featurebyte/service/feature_materialize.py
  featurebyte/service/feature_materialize_scheduler.py
  featurebyte/service/offline_store_feature_table_comment.py
  featurebyte/service/offline_store_feature_table_construction.py
  featurebyte/service/online_serving.py
  scripts/enforce_import_rules.py
  tests/fixtures/entity_universe/ts_window_aggregate_bigquery.sql
  tests/fixtures/entity_universe/ts_window_aggregate_databricks_unity.sql
  tests/fixtures/entity_universe/ts_window_aggregate_snowflake.sql
  tests/fixtures/entity_universe/ts_window_aggregate_spark.sql
  tests/integration/api/test_time_series_view_operations.py
  tests/integration/conftest.py
  tests/unit/api/test_offline_ingest_query_graph.py
  tests/unit/models/test_entity_universe.py
  tests/unit/models/test_sqlglot_expression.py
  tests/unit/query_graph/model/test_window.py
  tests/unit/service/test_offline_store_feature_table_manager.py
Labels: Skip Changelog

#2771 [DEV-3953] Improve request table rows deduplication in time series aggregator
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day_with_offset.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_latest.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_mixed_order_dependency.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month_with_offset.sql
  tests/fixtures/expected_preview_time_series_window_aggregate.sql
Labels: Skip Changelog

#2772 [chore] bump vuln dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#2774 [DEV-3940] Add `reference_timezone` attribute to `CronFeatureJobSetting`
  featurebyte/query_graph/model/feature_job_setting.py
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day_with_offset.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_latest.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_mixed_order_dependency.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month_with_offset.sql
  tests/fixtures/expected_preview_time_series_window_aggregate.sql
  tests/unit/api/test_aggregate_over.py
  tests/unit/api/test_time_series_table.py
  tests/unit/models/test_time_series_table.py
  tests/unit/routes/test_time_series_table.py
Labels: documentation, Skip Changelog

#2775 [DEV-3943] Handle timestamp schema in DT_EXTRACT node
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/sql/ast/datetime.py
  tests/fixtures/query_graph/test_datetime_extract/event_table_no_timezone_offset_bigquery.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_no_timezone_offset_databricks_unity.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_no_timezone_offset_snowflake.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_no_timezone_offset_spark.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_column_bigquery.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_column_databricks_unity.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_column_snowflake.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_column_spark.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_literal_bigquery.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_literal_databricks_unity.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_literal_snowflake.sql
  tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_literal_spark.sql
  tests/fixtures/query_graph/test_datetime_extract/time_series_table_timezone_offset_literal_bigquery.sql
  tests/fixtures/query_graph/test_datetime_extract/time_series_table_timezone_offset_literal_databricks_unity.sql
  tests/fixtures/query_graph/test_datetime_extract/time_series_table_timezone_offset_literal_snowflake.sql
  tests/fixtures/query_graph/test_datetime_extract/time_series_table_timezone_offset_literal_spark.sql
  tests/integration/api/test_time_series_view_operations.py
  tests/unit/query_graph/sql/ast/test_datetime_extract.py
Labels: Skip Changelog

#2776 [DEV-3948] Revise `TIMESTAMP_TZ_TUPLE` related datetime operations
  featurebyte/api/feature.py
  featurebyte/core/series.py
  featurebyte/enum.py
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/query_graph/node/binary.py
  tests/unit/api/test_aggregate_over.py
  tests/unit/api/test_timestamp_timezone_tuple.py
Labels: documentation, Skip Changelog

#2779 [DEV-3955] Add sampling option for reading from feature table cache
  featurebyte/service/feature_table_cache.py
  tests/fixtures/feature_table_cache/feature_query_sampled.sql
  tests/unit/service/test_feature_table_cache.py
Labels: Skip Changelog

#2778 [chore] Revise time series table validation logic
  featurebyte/api/source_table.py
  featurebyte/query_graph/model/table.py
  featurebyte/service/time_series_table.py
  tests/unit/api/test_time_series_table.py
  tests/unit/routes/test_time_series_table.py
Labels: documentation, Skip Changelog

#2781 [DEV-3952] Update DT_EXTRACT node to handle timestamp tuple schema
  featurebyte/core/accessor/datetime.py
  featurebyte/query_graph/node/date.py
  featurebyte/query_graph/sql/ast/datetime.py
  featurebyte/query_graph/sql/timestamp_helper.py
  tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_bigquery.sql
  tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_databricks_unity.sql
  tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_snowflake.sql
  tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_spark.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_bigquery.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_databricks_unity.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_snowflake.sql
  tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_spark.sql
  tests/integration/api/test_time_series_view_operations.py
  tests/unit/api/test_timestamp_timezone_tuple.py
  tests/unit/query_graph/sql/ast/test_datetime_extract.py
  tests/unit/query_graph/sql/test_timestamp_handler.py
Labels: Skip Changelog

#2782 [DEV-3958] Enable create new version for time series feature
  featurebyte/service/version.py
  tests/unit/api/test_time_series_table.py
Labels: Skip Changelog

#2784 [DEV-3959] Validate compatibility of window and offset unit and format_string
  featurebyte/api/aggregator/window_aggregator.py
  featurebyte/query_graph/model/timestamp_schema.py
  featurebyte/query_graph/node/schema.py
  tests/unit/api/test_aggregate_over.py
  tests/unit/query_graph/model/test_timestamp_schema.py
Labels: documentation, Skip Changelog

#2783 [DEV-3957] Add support for key-pair authentication for Snowflake feature store
  .changelog/DEV-3957.yaml
  .github/workflows/test.yaml
  featurebyte/feast/model/feature_store.py
  featurebyte/feast/utils/materialize_helper.py
  featurebyte/models/credential.py
  featurebyte/service/feature_materialize.py
  featurebyte/session/snowflake.py
  tests/fixtures/rsa_key.p8
  tests/fixtures/rsa_key_no_passphrase.p8
  tests/integration/conftest.py
  tests/unit/models/test_credential.py
  tests/unit/service/test_feature_materialize.py
Labels: documentation

#2788 [DEV-3954] Use reference_timezone when available for feature computation
  featurebyte/query_graph/model/feature_job_setting.py
  featurebyte/service/cron_helper.py
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_day_with_offset.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_latest.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_mixed_order_dependency.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month.sql
  tests/fixtures/aggregator/expected_time_series_window_aggregator_month_with_offset.sql
  tests/fixtures/expected_preview_time_series_window_aggregate.sql
  tests/integration/conftest.py
  tests/unit/api/test_time_series_table.py
  tests/unit/api/test_time_series_view.py
  tests/unit/query_graph/conftest.py
  tests/unit/query_graph/sql/test_cron.py
  tests/unit/query_graph/test_feature_job_setting_extractor.py
  tests/unit/service/test_cron_helper.py
  tests/unit/service/test_version.py
Labels: Skip Changelog

#2786 [chore] Make some tasks revoccable and rerunnable
  featurebyte/schema/worker/task/batch_feature_table.py
  featurebyte/schema/worker/task/batch_request_table.py
  featurebyte/schema/worker/task/feature_list_batch_feature_create.py
  featurebyte/schema/worker/task/observation_table.py
Labels: Skip Changelog

#2790 [DEV-3931] Handle is_utc_time in calendar aggregation
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  tests/fixtures/aggregator/expected_time_series_window_aggregator_is_utc_time.sql
  tests/unit/api/test_offline_ingest_query_graph.py
  tests/unit/query_graph/test_time_series_window_aggregator.py
Labels: Skip Changelog

#2792 [DEV-3963] Fix catalog cleanup task error
  featurebyte/common/progress.py
  featurebyte/worker/task/catalog_cleanup.py
  tests/unit/common/test_progress.py
Labels: Skip Changelog

#2795 [chore] Update table facade service
  featurebyte/service/table_facade.py
  tests/unit/service/test_table_facade.py
Labels: Skip Changelog

#2796 [DEV-3966] Improve request table rows deduplication in non-tile window aggregator
  featurebyte/enum.py
  featurebyte/query_graph/sql/aggregator/helper.py
  featurebyte/query_graph/sql/aggregator/non_tile_window.py
  featurebyte/query_graph/sql/aggregator/time_series_window.py
  tests/fixtures/aggregator/expected_non_tile_window_aggregator.sql
  tests/fixtures/aggregator/expected_non_tile_window_complex_feature.sql
  tests/fixtures/expected_preview_non_tile_window_aggregate.sql
Labels: Skip Changelog

#2797 [DEV-3967] Fix feature store deletion logic
  featurebyte/routes/common/base.py
  featurebyte/service/base_document.py
  tests/unit/routes/test_feature_store.py
Labels: Skip Changelog

#2799 [chore] bump snowflake
  poetry.lock
  pyproject.toml
Labels: dependencies
